import Link from "next/link";
import type { ReactNode } from "react";
import { Breadcrumbs } from "./Breadcrumbs";
import type { Crumb } from "./Breadcrumbs";

export interface GuideSection { title: string; paragraphs: string[]; bullets?: string[] }

export function GuidePage({ title, intro, updated, sections, takeaway, breadcrumbs, plannerHref = "/garten/gartenhaus-planer/", plannerLabel = "Gartenhaus planen", limitation = "Diese Einordnung ersetzt keine Prüfung von Baurecht, Abständen, Statik, Fundament oder Herstellerangaben für deinen konkreten Standort.", calculator }: { title: string; intro: string; updated: string; sections: GuideSection[]; takeaway: string; breadcrumbs?: Crumb[]; plannerHref?: string; plannerLabel?: string; limitation?: string; calculator?: ReactNode }) {
  return <><article className="guide-page"><Breadcrumbs items={breadcrumbs ?? [{ label: "Start", href: "/" }, { label: "Garten", href: "/garten/" }, { label: title }]} /><header><p className="eyebrow">MachPlan Ratgeber · zuletzt geprüft {updated}</p><h1>{title}</h1><p>{intro}</p></header>{calculator && <div className="guide-calculator">{calculator}</div>}<div className="guide-layout"><aside><strong>Direkt zum Ergebnis</strong><p>{takeaway}</p><Link className="button button--primary" href={plannerHref}>{plannerLabel} →</Link></aside><div className="guide-copy">{sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}</section>)}<div className="guide-limit"><strong>Wichtige Grenze</strong><p>{limitation}</p></div></div></div></article><section className="guide-cta"><div><p className="eyebrow">Vom Wissen zur Auswahl</p><h2>Berechne jetzt deinen Planungsrahmen.</h2><p>Der Rechner übersetzt deinen Bedarf in transparente Auswahlkriterien.</p></div><Link className="button button--light" href={plannerHref}>Planer kostenlos starten →</Link></section></>;
}
