import Link from "next/link";
import type { ReactNode } from "react";
import { CONTENT_UPDATED_AT } from "@/lib/metadata";
import { absoluteUrl, SITE } from "@/lib/site";
import { Breadcrumbs } from "./Breadcrumbs";
import type { Crumb } from "./Breadcrumbs";
import { JsonLd } from "./JsonLd";

export interface GuideSection { title: string; paragraphs: string[]; bullets?: string[] }
export interface GuideSource { label: string; href: string; publisher?: string }

export function GuidePage({ title, intro, path, updated, updatedAt = CONTENT_UPDATED_AT, sections, takeaway, breadcrumbs, plannerHref = "/garten/gartenhaus-planer/", plannerLabel = "Gartenhaus planen", limitation = "Diese Einordnung ersetzt keine Prüfung von Baurecht, Abständen, Statik, Fundament oder Herstellerangaben für deinen konkreten Standort.", calculator, sources = [] }: { title: string; intro: string; path?: string; updated: string; updatedAt?: string; sections: GuideSection[]; takeaway: string; breadcrumbs?: Crumb[]; plannerHref?: string; plannerLabel?: string; limitation?: string; calculator?: ReactNode; sources?: GuideSource[] }) {
  const url = path ? absoluteUrl(path) : undefined;
  const siteRoot = SITE.url.replace(/\/$/, "");
  return <><JsonLd data={{ "@context": "https://schema.org", "@type": "Article", ...(url ? { "@id": `${url}#article`, mainEntityOfPage: { "@type": "WebPage", "@id": url } } : {}), headline: title, description: intro, dateModified: updatedAt, inLanguage: "de-DE", author: { "@type": "Person", "@id": `${siteRoot}/#publisher`, name: "Schayan Yousefian", url: absoluteUrl("/ueber-machplan/") }, publisher: { "@type": "Person", "@id": `${siteRoot}/#publisher`, name: "Schayan Yousefian" }, isPartOf: { "@type": "WebSite", "@id": `${siteRoot}/#website` } }} /><article className="guide-page"><Breadcrumbs items={breadcrumbs ?? [{ label: "Start", href: "/" }, { label: "Garten", href: "/garten/" }, { label: title }]} /><header><p className="eyebrow">MachPlan Ratgeber</p><p className="guide-meta">Von <Link href="/ueber-machplan/" rel="author">Schayan Yousefian</Link> · zuletzt geprüft <time dateTime={updatedAt}>{updated}</time></p><h1>{title}</h1><p>{intro}</p></header>{calculator && <div className="guide-calculator">{calculator}</div>}<div className="guide-layout"><aside aria-labelledby="guide-answer-title"><h2 id="guide-answer-title">Kurzantwort</h2><p>{takeaway}</p><Link className="button button--primary" href={plannerHref}>{plannerLabel} →</Link></aside><div className="guide-copy">{sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}</section>)}{sources.length > 0 && <section className="guide-sources"><h2>Quellen und weiterführende Hinweise</h2><ul>{sources.map((source) => <li key={source.href}><a href={source.href} rel="noopener noreferrer">{source.label}</a>{source.publisher ? ` – ${source.publisher}` : ""}</li>)}</ul></section>}<div className="guide-method"><strong>Nachvollziehbarkeit</strong><p>Wie MachPlan rechnet, Annahmen kennzeichnet und Grenzen behandelt, erklären wir in der <Link href="/methodik/">Methodik</Link>.</p></div><div className="guide-limit"><strong>Wichtige Grenze</strong><p>{limitation}</p></div></div></div></article><section className="guide-cta"><div><p className="eyebrow">Vom Wissen zur Auswahl</p><h2>Berechne jetzt deinen Planungsrahmen.</h2><p>Der Rechner übersetzt deinen Bedarf in transparente Auswahlkriterien.</p></div><Link className="button button--light" href={plannerHref}>Planer kostenlos starten →</Link></section></>;
}
