import { createPageMetadata } from "@/lib/metadata";
import { GuidePage } from "@/components/seo/GuidePage";
export const metadata = createPageMetadata({
  title: "Gartenhaus für Fahrräder planen",
  description: "Gartenhaus für Fahrräder: Türbreite, Stellfläche, Rangieren, Sicherheit und Feuchtigkeit sinnvoll planen.",
  path: "/garten/gartenhaus-fuer-fahrraeder/",
  kind: "article",
});
export default function Page() { return <GuidePage path="/garten/gartenhaus-fuer-fahrraeder/" title="Gartenhaus für Fahrräder: Platz reicht nicht allein" intro="Fahrräder müssen nicht nur hineinpassen. Eine breite Tür, freie Rangierfläche, trockene Lagerung und ein sinnvoller Zugriff machen den Unterschied im Alltag." updated="August 2026" takeaway="Plane pro Fahrrad Standfläche plus Bewegungsreserve und bevorzuge eine bekannte Türbreite von mindestens 80 cm." sections={[{ title: "Tür und Weg nach draußen", paragraphs: ["Eine schmale Tür wird täglich zum Problem, besonders bei breiten Lenkern, Körben, Kindersitzen oder E-Bikes. Der MachPlan-Heuristik zufolge sind bei Fahrrädern mindestens 80 Zentimeter bekannte Türbreite sinnvoll.", "Unbekannte Türbreiten werden nicht automatisch ausgeschlossen. Sie erhalten aber eine Warnung, weil die Eignung nicht sicher bestätigt ist." ] }, { title: "Anordnung statt nur Quadratmeter", paragraphs: ["Fahrräder längs an einer Wand, nebeneinander oder in Halterungen benötigen unterschiedliche Flächen. Berücksichtige, welches Rad wie häufig benutzt wird und ob andere Geräte den Weg blockieren.", "E-Bikes erhöhen nicht nur Gewicht und Wert. Ladegeräte, Akkulagerung und elektrische Installation müssen nach Herstellerangaben und geltenden Sicherheitsregeln geplant werden." ] }, { title: "Sicherheit und Feuchte", paragraphs: ["Eine stabile Verankerungsmöglichkeit im Inneren kann wichtiger sein als ein einfaches Türschloss. Prüfe Konstruktion, Scharniere und mögliche Versicherungsanforderungen.", "Gute Lüftung reduziert Feuchtestau, ersetzt aber keine trockene Gründung und dichte Gebäudehülle. Nasse Räder bringen zusätzlich Feuchte in den Raum." ] }]} />; }
