"use client";
import { useEffect, useState } from "react";
import { CalculatorShell } from "@/components/calculator/CalculatorShell";
import { usePlannerSessionState } from "@/components/calculator/usePlannerSessionState";
import { AffiliateDisclosure } from "@/components/affiliate/AffiliateDisclosure";
import { AffiliateLink } from "@/components/affiliate/AffiliateLink";
import { ProductImage } from "@/components/product/ProductImage";
import { ProductReasons } from "@/components/product/ProductReasons";
import { PriceDisplay } from "@/components/product/PriceDisplay";
import { loadDehumidifierCatalog } from "@/lib/catalog/load-client-catalog";
import { calculateDehumidifierRequirements } from "@/lib/dehumidifier/rules";
import { recommendDehumidifiers } from "@/lib/dehumidifier/recommend";
import { DehumidifierInputSchema, type DehumidifierCatalog, type DehumidifierInput } from "@/lib/dehumidifier/types";

const INITIAL: DehumidifierInput = { roomType: "basement", areaM2: 25, ceilingHeightM: 2.3, approximateTemperatureC: 14, humiditySeverity: "moderate", laundryDrying: false, continuousDrainPossible: true, noisePriority: "medium", budgetMaxEur: 300 };
const ROOMS = [["basement","Keller"],["living","Wohnraum"],["bedroom","Schlafzimmer"],["bathroom","Bad"],["laundry","Waschraum"],["garage","Garage"],["other","Anderer Raum"]] as const;
const parseDehumidifierInput=(value:unknown)=>{const result=DehumidifierInputSchema.safeParse(value);return result.success?result.data:null};

export function DehumidifierPlanner() {
  const [step,setStep] = useState(1); const{value:input,setValue:setInput,reset:resetInput}=usePlannerSessionState("machplan:dehumidifier:v1",INITIAL,parseDehumidifierInput); const [catalog,setCatalog] = useState<DehumidifierCatalog|null>(null); const [status,setStatus] = useState<"idle"|"loading"|"ready"|"error">("idle");
  useEffect(() => { if (step > 1) document.getElementById("calculator-heading")?.focus(); }, [step]);
  const requirements = calculateDehumidifierRequirements(input); const matches = catalog ? recommendDehumidifiers(catalog,input) : [];
  const update = <K extends keyof DehumidifierInput,>(key:K,value:DehumidifierInput[K]) => setInput((current)=>({...current,[key]:value}));
  async function results(){ if(!DehumidifierInputSchema.safeParse(input).success)return; setStep(4); if(catalog)return; setStatus("loading"); try{setCatalog(await loadDehumidifierCatalog());setStatus("ready");}catch{setStatus("error");} }
  const titles=["Welcher Raum soll entfeuchtet werden?","Wie hoch ist die Belastung?","Welche Eigenschaften sind wichtig?","Dein Auswahlrahmen"];
  return <CalculatorShell step={step} totalSteps={4} title={titles[step-1]} label="Luftentfeuchter-Rechner" onReset={()=>{resetInput();setStep(1);setCatalog(null);setStatus("idle")}}>
    {step===1&&<div className="form-step"><div className="field"><label htmlFor="room">Raumtyp</label><select id="room" value={input.roomType} onChange={(e)=>update("roomType",e.target.value as DehumidifierInput["roomType"])}>{ROOMS.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div><div className="field-grid field-grid--two compact-fields"><NumberInput id="area" label="Raumfläche" value={input.areaM2} unit="m²" min={4} max={500} onChange={(v)=>update("areaM2",v)}/><NumberInput id="height" label="Deckenhöhe" value={input.ceilingHeightM} unit="m" min={1.8} max={6} step="0.1" onChange={(v)=>update("ceilingHeightM",v)}/></div><div className="field field--wide"><label htmlFor="temperature">Ungefähre Raumtemperatur <span className="optional">optional</span></label><div className="input-with-unit"><input id="temperature" type="number" value={input.approximateTemperatureC??""} min="0" max="45" onChange={(e)=>update("approximateTemperatureC",e.target.value===""?undefined:e.target.valueAsNumber)}/><span>°C</span></div></div><div className="live-estimate"><span>Berechnetes Raumvolumen</span><strong>{requirements.roomVolumeM3.toLocaleString("de-DE")} m³</strong><small>Fläche × Deckenhöhe</small></div></div>}
    {step===2&&<div className="form-step"><fieldset className="choice-group"><legend>Geschätzte Feuchtebelastung</legend><div className="radio-grid radio-grid--three">{[["mild","Leicht","Nur zeitweise erhöht"],["moderate","Mittel","Regelmäßig spürbar"],["high","Hoch","Deutlich und anhaltend"]].map(([value,label,detail])=><label key={value} className={`radio-card radio-card--detail ${input.humiditySeverity===value?"radio-card--selected":""}`}><input type="radio" name="severity" checked={input.humiditySeverity===value} onChange={()=>update("humiditySeverity",value as DehumidifierInput["humiditySeverity"])}/><span><strong>{label}</strong><small>{detail}</small></span></label>)}</div></fieldset><div className="check-card-grid check-card-grid--two"><Check label="Wäsche wird im Raum getrocknet" detail="Erhöht den Auswahlpuffer." checked={input.laundryDrying} onChange={(v)=>update("laundryDrying",v)}/><Check label="Kontinuierlicher Ablauf ist erforderlich" detail="Nur Geräte mit Schlauchanschluss berücksichtigen." checked={input.continuousDrainPossible} onChange={(v)=>update("continuousDrainPossible",v)}/></div><div className="info-box"><span>i</span><p>Die Belastungsstufe ist eine Auswahlhilfe. Sie diagnostiziert weder Ursache noch Schimmel- oder Bauschäden.</p></div></div>}
    {step===3&&<div className="form-step"><fieldset className="choice-group"><legend>Geräusch hat Priorität</legend><div className="radio-grid radio-grid--three">{[["low","Niedrig"],["medium","Mittel"],["high","Hoch"]].map(([value,label])=><label key={value} className={`radio-card ${input.noisePriority===value?"radio-card--selected":""}`}><input type="radio" name="noise" checked={input.noisePriority===value} onChange={()=>update("noisePriority",value as DehumidifierInput["noisePriority"])}/><span>{label}</span></label>)}</div></fieldset><NumberInput id="dehumidifier-budget" label="Maximales Gesamtbudget" value={input.budgetMaxEur} unit="€" min={50} max={10000} onChange={(v)=>update("budgetMaxEur",v)}/><RequirementGrid input={input}/></div>}
    {step===4&&<div className="results" aria-live="polite"><RequirementGrid input={input}/>{status==="loading"&&<State title="Geprüfte Produktdaten werden geladen." text="Wir laden nur den Luftentfeuchter-Katalog."/>}{status==="error"&&<State title="Produktdaten konnten nicht geladen werden." text="Deine Berechnung bleibt erhalten; bitte später erneut versuchen."/>}{status==="ready"&&catalog?.products.length===0&&<State title="Der geprüfte Gerätekatalog wird noch aufgebaut." text="Dein Auswahlrahmen ist vollständig. Modelle erscheinen erst nach manueller Prüfung ihrer Herstellerangaben."/>}{status==="ready"&&catalog&&catalog.products.length>0&&matches.length===0&&<State title="Kein geprüftes Modell erfüllt alle Kriterien." text="Ändere Budget, Ablaufanforderung oder Raumdaten bewusst – wir lockern keine Kriterien im Hintergrund."/>}{matches.length>0&&<><AffiliateDisclosure/><div className="product-list">{matches.map(({product,offer,reasons},index)=><article className="product-card" key={product.id}><div className="rank-badge">#{index+1}</div><ProductImage src={offer.imageUrl} alt={product.name}/><div className="product-content"><p className="product-brand">{product.brand??"Luftentfeuchter"}</p><h3>{product.name}</h3><dl className="product-facts"><div><dt>Fläche</dt><dd>{product.maxRecommendedAreaM2??"–"} m²</dd></div><div><dt>Ablauf</dt><dd>{product.continuousDrain?"ja":"nein"}</dd></div><div><dt>Geräusch</dt><dd>{product.noiseDb??"–"} dB</dd></div><div><dt>Leistung</dt><dd>{product.powerW??"–"} W</dd></div></dl><ProductReasons reasons={reasons}/><div className="offer-row"><PriceDisplay offer={offer}/><AffiliateLink className="button button--primary" href={offer.affiliateUrl} productId={product.id} verticalRef="dehumidifier">Beim Händler ansehen ↗</AffiliateLink></div></div></article>)}</div></>}</div>}
    <div className="calculator-actions">{step>1&&<button className="button button--back" onClick={()=>setStep((s)=>Math.max(1,s-1))}>← Zurück</button>}{step<3&&<button className="button button--primary" onClick={()=>setStep((s)=>s+1)}>Weiter →</button>}{step===3&&<button className="button button--primary" onClick={results}>Auswahlrahmen berechnen →</button>}{step===4&&<button className="button button--back" onClick={()=>setStep(1)}>Eingaben ändern</button>}</div>
  </CalculatorShell>;
}

function NumberInput({id,label,value,unit,min,max,step,onChange}:{id:string;label:string;value:number;unit:string;min:number;max:number;step?:string;onChange:(value:number)=>void}){return <div className="field"><label htmlFor={id}>{label}</label><div className="input-with-unit"><input id={id} type="number" value={value} min={min} max={max} step={step} onChange={(e)=>onChange(e.target.valueAsNumber)}/><span>{unit}</span></div></div>}
function Check({label,detail,checked,onChange}:{label:string;detail:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className={`check-card ${checked?"check-card--selected":""}`}><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)}/><span className="check-box">{checked?"✓":""}</span><span><strong>{label}</strong><small>{detail}</small></span></label>}
function RequirementGrid({input}:{input:DehumidifierInput}){const r=calculateDehumidifierRequirements(input);return <div className="requirement-summary"><div><span>Raumvolumen</span><strong>{r.roomVolumeM3.toLocaleString("de-DE")} m³</strong></div><div><span>Auswahlziel Fläche</span><strong>{r.requiredAreaM2} m²</strong></div><div><span>Auswahlziel Volumen</span><strong>{r.requiredVolumeM3} m³</strong></div><div><span>Planungspuffer</span><strong>× {r.margin.toLocaleString("de-DE")}</strong></div></div>}
function State({title,text}:{title:string;text:string}){return <div className="result-state"><span className="result-symbol">◇</span><h3>{title}</h3><p>{text}</p><p className="state-note">Keine Diagnose und keine ungeprüften Produktempfehlungen.</p></div>}
