import Link from "next/link";
import { DataReportLinks, ReportBarList, ReportMetricGrid } from "@/components/data-report/DataReportBlocks";
import { ProjectReportFrame } from "@/components/data-report/ProjectReportFrame";
import { carportProjectReport as report } from "@/lib/data-report/project-catalog-insights";

type PageInfo = { slug: string; path: string; title: string; description: string };
const euro = (value: number) => value.toLocaleString("de-DE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 });
const number = (value: number, digits = 0) => value.toLocaleString("de-DE", { minimumFractionDigits: digits, maximumFractionDigits: digits });

function Frame({ info, eyebrow, headline, introduction, takeawayTitle, takeaway, children }: PageInfo & { info: PageInfo; eyebrow: string; headline: React.ReactNode; introduction: string; takeawayTitle: string; takeaway: string; children: React.ReactNode }) {
  return <ProjectReportFrame path={info.path} title={info.title} description={info.description} topicLabel="Carports" eyebrow={eyebrow} headline={headline} introduction={introduction} takeawayTitle={takeawayTitle} takeaway={takeaway} className="project-data-carport" updated={report.updatedLabel} datasetName="PassendPlanen Carportauswertung" datasetDescription={`Auswertung von ${report.total} geprüften Carportprodukten und ${report.kits.count} dokumentierten Bausätzen.`} variables={["Produktart", "Außenbreite", "Außenlänge", "Grundfläche", "Stellplatzzahl", "Angebotspreis"]} method={<><p>Die Daten stammen aus dem geprüften PassendPlanen Produktkatalog. Größenanalysen verwenden ausschließlich die {report.kits.count} als Bausatz erfassten Produkte. Für Preise zählt je Produkt das günstigste verfügbare Angebot.</p><p>Außenmaße beschreiben die belegte Fläche, nicht den lichten Raum zwischen Pfosten. Lieferung, Fundament, Montage und Entwässerung sind im Bausatzpreis nicht automatisch enthalten. Die Stichprobe bildet nicht den gesamten Markt ab.</p><p><Link href="/methodik/">Die vollständige Prüfmethode ansehen</Link>.</p></>} nextTitle="Den benötigten lichten Raum aus dem Fahrzeug ableiten." nextText="Der Carport Planer rechnet mit Fahrzeugbreite, Spiegeln, geöffneten Türen, Länge, Höhe und Rangierreserve. So entsteht ein persönlicher Mindestwert, bevor Außenmaße verglichen werden." plannerHref="/garten/carport-planer/" plannerLabel="Carport planen">{children}</ProjectReportFrame>;
}

function SizeReport({ info }: { info: PageInfo }) {
  return <Frame info={info} {...info} eyebrow="69 Carport Bausätze mit dokumentierten Außenmaßen" headline={<>Ein Stellplatz und zwei Stellplätze unterscheiden sich nicht nur in der <em>Breite</em>.</>} introduction="Die Stichprobe enthält 47 Einzelcarports und 22 Doppelcarports. Wir vergleichen Außenbreite, Außenlänge, belegte Grundfläche und Angebotspreis, ohne das Außenmaß mit der nutzbaren Durchfahrt gleichzusetzen." takeawayTitle="Außenfläche ist kein Nutzmaß" takeaway="Pfosten, Dachüberstand und konstruktive Bauteile können den lichten Raum verkleinern. Für die Fahrzeugprüfung zählt der engste freie Querschnitt.">
    <section className="data-report-section"><div className="data-report-heading"><p className="eyebrow">Die Bausätze in vier Zahlen</p><h2>Der mittlere Carport belegt {number(report.kits.medianFootprintM2, 1)} Quadratmeter Außenfläche.</h2></div><ReportMetricGrid ariaLabel="Carport Kennzahlen" items={[
      { value: `${report.kits.count}`, label: "dokumentierte Bausätze", note: `${report.vehicleGroups[0].count} für ein und ${report.vehicleGroups[1].count} für zwei Fahrzeuge` },
      { value: `${number(report.kits.medianWidthM, 2)} m`, label: "mittlere Außenbreite", note: "Nicht mit der lichten Breite gleichsetzen" },
      { value: `${number(report.kits.medianLengthM, 2)} m`, label: "mittlere Außenlänge", note: "Dachüberstände können enthalten sein" },
      { value: euro(report.kits.medianPriceEur), label: "mittlerer Bausatzpreis", note: "Ohne sichere Aussage zu Nebenkosten" },
    ]} /></section>
    <section className="data-report-section"><div className="data-report-heading"><p className="eyebrow">Einzel und Doppel im direkten Datenvergleich</p><h2>Doppelcarports sind breiter, aber nicht durchgehend länger.</h2><p>Die Medianwerte zeigen die Mitte der jeweiligen Gruppe. Sie beschreiben keine Mindestmaße und keine baurechtliche Eignung.</p></div><div className="data-table-wrap"><table><caption>Außenmaße und Angebotspreise nach Stellplatzzahl</caption><thead><tr><th>Gruppe</th><th>Bausätze</th><th>Außenbreite</th><th>Außenlänge</th><th>Grundfläche</th><th>Preis</th></tr></thead><tbody>{report.vehicleGroups.map((item) => <tr key={item.vehicleCount}><th>{item.vehicleCount === 1 ? "Einzelcarport" : "Doppelcarport"}</th><td>{item.count}</td><td>{number(item.medianWidthM, 2)} m</td><td>{number(item.medianLengthM, 2)} m</td><td>{number(item.medianFootprintM2, 1)} m²</td><td>{euro(item.medianPriceEur)}</td></tr>)}</tbody></table></div></section>
    <section className="data-report-section project-data-band-section"><div className="data-report-heading"><p className="eyebrow">Drei Flächenklassen</p><h2>Die Produktbezeichnung allein erklärt die belegte Fläche nicht.</h2></div><div className="project-data-card-grid">{report.footprintBands.map((item) => <article key={item.label}><span>{item.label}</span><strong>{item.count} Bausätze</strong><p>Mittlere Fläche {number(item.medianFootprintM2, 1)} m²</p><p>Mittlerer Preis {euro(item.medianPriceEur)}</p></article>)}</div></section>
    <DataReportLinks items={[{ href: "/garten/carport-groesse/", label: "Carportgröße berechnen", description: "Fahrzeug und Bewegungsreserve in lichte Maße übersetzen." }, { href: "/garten/carport-fundament/", label: "Fundament einordnen", description: "Raster und Standortbedingungen getrennt prüfen." }, { href: "/ratgeber/daten/carport-datenluecken-lichte-masse-dach/", label: "Datenlücken ansehen", description: "Erkennen, welche Maße im Feed nicht ausreichen." }]} />
  </Frame>;
}

function AssortmentReport({ info }: { info: PageInfo }) {
  const kit = report.kinds.find((item) => item.key === "kit")!;
  return <Frame info={info} {...info} eyebrow="120 Carportprodukte nach Produktart getrennt" headline={<>Ein Preis von 69 Euro gehört nicht automatisch zu einem <em>Carport</em>.</>} introduction="Im gemeinsamen Sortiment stehen vollständige Bausätze neben Seitenwänden, Fundamentteilen, Entwässerung und Elektrik. Eine ungefilterte Preisliste würde diese völlig verschiedenen Produkte miteinander vermischen." takeawayTitle="Der Produkttyp kommt vor dem Preis" takeaway={`Nur ${kit.count} von ${report.total} Treffern sind als Carport Bausatz erfasst. Zubehör erklärt die niedrige Unterkante des Gesamtkatalogs.`}>
    <section className="data-report-section data-split-section"><div><p className="eyebrow">Sortiment statt Rangliste</p><h2>Mehr als zwei von fünf Treffern sind kein vollständiger Bausatz.</h2><p>Seiten und Frontelemente bilden mit 39 Produkten die zweitgrößte Gruppe. Dazu kommen Fundamentteile, Entwässerung und ein Elektroprodukt. Diese Artikel können für ein Projekt wichtig sein, dürfen aber nicht in einen vermeintlichen Carport Durchschnittspreis einfließen.</p></div><ReportBarList ariaLabel="Carport Produktarten" maxValue={report.total} items={report.kinds.map((item) => ({ label: item.label, value: item.count, displayValue: `${item.count} Produkte`, detail: `Mittlerer Artikelpreis ${euro(item.medianPriceEur)}` }))} /></section>
    <section className="data-report-section project-price-corridor"><div><p className="eyebrow">Preiskorridore statt Einzelwert</p><h2>Bausätze liegen in einer anderen Größenordnung als Systemteile.</h2></div><div className="project-price-grid">{report.kinds.filter((item) => item.count > 1).map((item) => <article key={item.key}><h3>{item.label}</h3><strong>{euro(item.medianPriceEur)}</strong><p>Die mittlere Hälfte liegt zwischen {euro(item.lowerPriceEur)} und {euro(item.upperPriceEur)}.</p></article>)}</div></section>
    <section className="data-report-section project-data-note"><div><p className="eyebrow">Für einen vollständigen Projektpreis</p><h2>Vier Positionen müssen separat bestätigt werden.</h2></div><ol><li><strong>Bausatz und Lieferumfang</strong><span>Pfosten, Dachdeckung und Befestigung vollständig prüfen.</span></li><li><strong>Fundament</strong><span>Herstellerfreigabe und Standortnachweis berücksichtigen.</span></li><li><strong>Entwässerung</strong><span>Rinne, Fallrohr und zulässigen Wasserweg planen.</span></li><li><strong>Lieferung und Montage</strong><span>Unbekannte Kosten nicht als null Euro behandeln.</span></li></ol></section>
    <DataReportLinks items={[{ href: "/ratgeber/carport-holz-oder-aluminium/", label: "Carportmaterial einordnen", description: "Gesamtprojekt und Standort statt Bausatzpreis betrachten." }, { href: "/garten/carport-dachentwaesserung/", label: "Dachwasser planen", description: "Fläche und Bemessungsregen zusammenführen." }, { href: "/ratgeber/daten/carport-groessen-stellplaetze/", label: "Bausatzgrößen vergleichen", description: "Einzel und Doppelcarports getrennt auswerten." }]} />
  </Frame>;
}

function GapReport({ info }: { info: PageInfo }) {
  return <Frame info={info} {...info} eyebrow="Datenabdeckung bei 120 Carportprodukten" headline={<>69 Außenmaße. Kein einziges dokumentiertes <em>lichtes Breitenmaß</em>.</>} introduction="Die Produktdaten eignen sich für eine erste Sortierung nach Bausatz und Außenfläche. Für die eigentliche Fahrzeugprüfung fehlen jedoch genau die Maße, die zwischen Pfosten und unter dem niedrigsten Bauteil zählen." takeawayTitle="Die wichtigste Lücke ist praktisch" takeaway="Ein großes Dach kann einen kleinen lichten Querschnitt überspannen. Ohne freie Breite, Länge und Höhe entsteht keine technische Passzusage.">
    <section className="data-report-section project-coverage-hero"><div><p className="eyebrow">Außen dokumentiert, innen offen</p><h2>Die Datenabdeckung fällt an der entscheidenden Stelle ab.</h2><p>Bei 69 Produkten sind Außenbreite und Außenlänge vorhanden. Lichte Breite oder lichte Länge sind bei keinem Produkt strukturiert erfasst. Nur sieben Produkte besitzen eine Höhenangabe, die als lichte Höhe eingeordnet wurde.</p></div><div className="project-coverage-number"><strong>{report.coverage.externalDimensions}</strong><span>Außenmaße</span><i>gegen</i><strong>{report.coverage.clearDimensions}</strong><span>lichte Breite oder Länge</span></div></section>
    <section className="data-report-section data-evidence-gap"><div><p className="eyebrow">Fünf Prüffelder</p><h2>Was aus dem Feed belastbar gelesen werden kann.</h2></div><div className="data-gap-grid"><article><strong>{report.coverage.externalDimensions} von {report.total}</strong><h3>Außenmaße</h3><p>Für Flächenbedarf und erste Grundstücksprüfung nutzbar.</p></article><article><strong>{report.coverage.clearHeight} von {report.total}</strong><h3>Höhenangabe</h3><p>Zu wenig für einen flächendeckenden Vergleich.</p></article><article><strong>{report.coverage.roofType} von {report.total}</strong><h3>Dachform</h3><p>Im strukturierten Datensatz nicht belastbar vorhanden.</p></article></div></section>
    <section className="data-report-section project-measure-route"><div><p className="eyebrow">Gegenprobe am konkreten Modell</p><h2>Vier Werte gehören vor dem Kauf in eine Skizze.</h2></div><ul><li><span>01</span><strong>Engste lichte Breite</strong><p>Zwischen Pfosten, Verkleidung und Anbauteilen messen.</p></li><li><span>02</span><strong>Niedrigste lichte Höhe</strong><p>Dachaufbauten, Gefälle und Fahrzeugaufbauten berücksichtigen.</p></li><li><span>03</span><strong>Nutzbare Länge</strong><p>Stoßfänger, Zugang und mögliche Lagernutzung einzeichnen.</p></li><li><span>04</span><strong>Dach und Wasserweg</strong><p>Dachform, Gefälle und Entwässerung am Standort bestätigen.</p></li></ul></section>
    <DataReportLinks items={[{ href: "/garten/carport-planer/", label: "Lichte Mindestmaße berechnen", description: "Vom Fahrzeug statt vom Dachmaß ausgehen." }, { href: "/garten/carport-dachentwaesserung/", label: "Entwässerung prüfen", description: "Dachfläche und Wasserweg separat planen." }, { href: "/ratgeber/daten/carport-bausatz-zubehoer-preise/", label: "Bausatz und Zubehör trennen", description: "Preisgruppen korrekt einordnen." }]} />
  </Frame>;
}

export function CarportReport({ info }: { info: PageInfo }) {
  if (info.slug === "carport-groessen-stellplaetze") return <SizeReport info={info} />;
  if (info.slug === "carport-bausatz-zubehoer-preise") return <AssortmentReport info={info} />;
  return <GapReport info={info} />;
}
