import Link from "next/link";
import { DataReportLinks, ReportBarList, ReportMetricGrid } from "@/components/data-report/DataReportBlocks";
import { ProjectReportFrame } from "@/components/data-report/ProjectReportFrame";
import { drywallProjectReport as report } from "@/lib/data-report/project-catalog-insights";

type PageInfo = { slug: string; path: string; title: string; description: string };
const euro = (value: number) => value.toLocaleString("de-DE", { style: "currency", currency: "EUR", maximumFractionDigits: 2 });
const number = (value: number, digits = 0) => value.toLocaleString("de-DE", { minimumFractionDigits: digits, maximumFractionDigits: digits });

function Frame({ info, eyebrow, headline, introduction, takeawayTitle, takeaway, children }: { info: PageInfo; eyebrow: string; headline: React.ReactNode; introduction: string; takeawayTitle: string; takeaway: string; children: React.ReactNode }) {
  return <ProjectReportFrame path={info.path} title={info.title} description={info.description} topicLabel="Trockenbau" eyebrow={eyebrow} headline={headline} introduction={introduction} takeawayTitle={takeawayTitle} takeaway={takeaway} className="project-data-drywall" updated={report.updatedLabel} datasetName="PassendPlanen Trockenbauauswertung" datasetDescription={`Auswertung von ${report.total} geprüften Trockenbauprodukten mit Platten, Profilen, Fugenmaterial und Dämmung.`} datasetSize={report.total} variables={["Produktart", "Plattentyp", "Material", "Plattenstärke", "Profilbreite", "Profillänge", "Packungsgröße", "Angebotspreis"]} method={<><p>Die Daten stammen aus dem geprüften PassendPlanen Trockenbaukatalog. Auswertungen nach Plattentyp und Profilmaß verwenden nur ausdrücklich dokumentierte Felder. Pro Produkt zählt das günstigste verfügbare Angebot.</p><p>Bezeichnungen wie Feuchtraum oder Brand und Schallschutz beschreiben eine Produktgruppe, aber keine Freigabe für einen vollständigen Wandaufbau. Platten, Profile, Befestiger, Dämmung und Fugenaufbau müssen aus einem nachgewiesenen System stammen.</p><p><Link href="/methodik/">Die Prüfmethode im Detail ansehen</Link>.</p></>} nextTitle="Wandfläche, Lagen, Öffnungen und Profilraster gemeinsam berechnen." nextText="Der Trockenbau Rechner erzeugt einen nachvollziehbaren Materialrahmen. Sicherheitsrelevante Anforderungen bleiben an das vollständige Herstellersystem und die Fachplanung gebunden." plannerHref="/haus/innenausbau/trockenbau-rechner/" plannerLabel="Trockenbau berechnen">{children}</ProjectReportFrame>;
}

function BoardReport({ info }: { info: PageInfo }) {
  return <Frame info={info} eyebrow="28 Trockenbauplatten nach dokumentiertem Typ" headline={<>Vier Plattengruppen stehen im Katalog. Keine ersetzt die Prüfung des <em>Wandaufbaus</em>.</>} introduction="Standard, Feuchtraum, Brand und Schallschutz sowie Gipsfaser sind als Gruppen erfasst. Wir vergleichen Häufigkeit, dokumentierte Dicke und Angebotspreis, ohne daraus eine technische Austauschbarkeit abzuleiten." takeawayTitle="Plattentyp ist nur eine Systemkomponente" takeaway="Eine Platte erreicht geforderte Eigenschaften erst im passenden Aufbau mit Profilen, Befestigung, Fugen und gegebenenfalls Dämmung.">
    <section className="data-report-section"><div className="data-report-heading"><p className="eyebrow">Der Plattenbestand</p><h2>28 Produkte verteilen sich auf vier klar benannte Typen.</h2></div><ReportMetricGrid ariaLabel="Trockenbauplatten Kennzahlen" items={[{ value: `${report.boards.count}`, label: "geprüfte Platten", note: `${report.boardTypes.reduce((sum, item) => sum + item.count, 0)} mit zugeordnetem Typ` }, { value: `${number(report.boards.medianThicknessMm, 1)} mm`, label: "mittlere dokumentierte Dicke", note: "Nur Produkte mit vorhandenem Wert" }, { value: `${report.boards.dimensionsKnown}`, label: "Platten mit Länge und Breite", note: "Maßdaten sind deutlich lückenhafter" }, { value: euro(report.boards.medianPriceEur), label: "mittlerer Artikelpreis", note: "Einzelplatte und Palette können abweichen" }]} /></section>
    <section className="data-report-section drywall-board-types"><div><p className="eyebrow">Verteilung und Dicke</p><h2>Standard und Brand beziehungsweise Schallschutz stellen die größten Gruppen.</h2></div><div className="project-data-card-grid">{report.boardTypes.map((item) => <article key={item.key}><span>{item.label}</span><strong>{item.count} Produkte</strong><p>Mittlere Dicke {number(item.medianThicknessMm, 1)} mm</p><p>Mittlerer Preis {euro(item.medianPriceEur)}</p></article>)}</div></section>
    <section className="data-report-section"><div className="data-report-heading"><p className="eyebrow">Daten nicht überinterpretieren</p><h2>Artikelpreise besitzen unterschiedliche Verkaufseinheiten.</h2><p>Einzelplatten, großformatige Platten und Palettenangebote stehen gemeinsam im Katalog. Wo Stückzahl und Abmessungen nicht vollständig vorliegen, wäre ein Preis je Quadratmeter spekulativ.</p></div><div className="data-callout"><strong>Für die Mengenrechnung zählt die konkrete Platte</strong><p>Länge, Breite, Lagenzahl, Wandseiten und Öffnungen bestimmen die Stückzahl. Der Plattentyp wird aus der geforderten Funktion des vollständigen Systems gewählt.</p></div></section>
    <DataReportLinks items={[{ href: "/haus/innenausbau/trockenbau-platten-berechnen/", label: "Plattenbedarf berechnen", description: "Wand, Öffnungen und Lagen verbinden." }, { href: "/ratgeber/trockenbauwand-einfach-oder-doppelt-beplankt/", label: "Beplankung einordnen", description: "Lagen und Wandfunktion gemeinsam betrachten." }, { href: "/ratgeber/daten/trockenbau-feuchtraum-brandschutz-datenluecken/", label: "Freigabelücken ansehen", description: "Grenzen der Produktdaten nachvollziehen." }]} />
  </Frame>;
}

function ProfileReport({ info }: { info: PageInfo }) {
  return <Frame info={info} eyebrow="48 Trockenbauprofile im Datencheck" headline={<>50, 75 und 100 Millimeter sind keine Preisstufen, sondern <em>Systemmaße</em>.</>} introduction="40 Profile besitzen eine dokumentierte Länge und Breite. Wir betrachten die drei häufigsten Breiten sowie Packungsgrößen. Profiltyp und Wandfunktion bleiben trotzdem an das gewählte System gebunden." takeawayTitle="Breite folgt der Anforderung" takeaway="Wandhöhe, Installationen, Schall und Brandschutz bestimmen das Profil. Ein günstigeres schmales Profil darf nicht aus der Preisliste heraus ersetzt werden.">
    <section className="data-report-section"><div className="data-report-heading"><p className="eyebrow">Profilbestand</p><h2>Die dokumentierten Breiten verteilen sich nahezu gleichmäßig.</h2></div><ReportMetricGrid ariaLabel="Trockenbauprofile Kennzahlen" items={[{ value: `${report.profiles.count}`, label: "geprüfte Profile", note: `${report.coverage.profileDimensions} mit Länge und Breite` }, { value: `${number(report.profiles.medianLengthMm)} mm`, label: "mittlere Profillänge", note: "Nur dokumentierte Längen" }, { value: `${number(report.profiles.medianPiecesPerPack)}`, label: "mittlere Packungsgröße", note: "Bei Profilen strukturiert vorhanden" }, { value: `${number(report.profiles.medianPackLinearM, 1)} m`, label: "mittlere lineare Packungsmenge", note: "Länge mal Stückzahl" }]} /></section>
    <section className="data-report-section drywall-profile-lines"><div><p className="eyebrow">Drei Breitenklassen</p><h2>Packungsmenge und Länge gehören zum Preisvergleich.</h2><p>Der reine Artikelpreis kann eine Packung mit anderer Stückzahl oder Profillänge abbilden. Deshalb werden die Bezugsgrößen daneben gezeigt.</p></div><div className="data-table-wrap"><table><caption>Profile nach dokumentierter Breite</caption><thead><tr><th>Breite</th><th>Produkte</th><th>Mittlere Länge</th><th>Stück je Packung</th><th>Lineare Packungsmenge</th><th>Artikelpreis</th></tr></thead><tbody>{report.profileWidths.map((item) => <tr key={item.widthMm}><th>{item.widthMm} mm</th><td>{item.count}</td><td>{number(item.medianLengthMm)} mm</td><td>{number(item.medianPiecesPerPack)}</td><td>{number(item.medianPackLinearM, 1)} m</td><td>{euro(item.medianPriceEur)}</td></tr>)}</tbody></table></div></section>
    <section className="data-report-section drywall-profile-role"><div><p className="eyebrow">Profilbreite ist nicht Profiltyp</p><h2>CW, UW und weitere Profile erfüllen unterschiedliche Aufgaben.</h2></div><div><article><strong>CW</strong><p>Ständerprofile bilden das vertikale Raster. Achsabstand und Höhe folgen dem System.</p></article><article><strong>UW</strong><p>Rahmenprofile führen den Wandverlauf an Boden und Decke.</p></article><article><strong>Weitere</strong><p>Sonderprofile dürfen nicht allein anhand ähnlicher Maße ersetzt werden.</p></article></div></section>
    <DataReportLinks items={[{ href: "/haus/innenausbau/trockenbau-profile-staenderwerk/", label: "Profile und Ständerwerk", description: "Raster aus Wandlänge und Systemvorgabe berechnen." }, { href: "/haus/innenausbau/trockenbau-tuer-oeffnungen/", label: "Türöffnungen planen", description: "Unterbrechungen und Verstärkungen berücksichtigen." }, { href: "/ratgeber/daten/trockenbauplatten-typen-dicken/", label: "Plattentypen auswerten", description: "Platten als zweite Systemkomponente betrachten." }]} />
  </Frame>;
}

function GapReport({ info }: { info: PageInfo }) {
  return <Frame info={info} eyebrow="Technische Datenabdeckung bei 85 Produkten" headline={<>Vier Feuchtraumangaben und keine Brandklasse reichen für <em>keine Freigabe</em>.</>} introduction="Der Katalog kann Produkte nach grober Funktion sortieren. Sicherheitsrelevante Eigenschaften eines konkreten Wandaufbaus sind jedoch nur sehr lückenhaft oder gar nicht strukturiert vorhanden." takeawayTitle="Nicht dokumentiert ist weder Nein noch Ja" takeaway="Fehlende Angaben dürfen nicht als ungeeignet gewertet werden. Ebenso wenig dürfen Produktname oder Farbe eine technische Freigabe ersetzen.">
    <section className="data-report-section project-coverage-hero"><div><p className="eyebrow">Produktgruppe gegen Nachweis</p><h2>28 Platten sind einem Typ zugeordnet. Nur vier besitzen eine ausdrückliche Feuchtraumangabe.</h2><p>Die Typisierung hilft bei der Suche. Für Planung und Ausführung zählt weiterhin der aktuelle Nachweis des vollständigen Systems.</p></div><div className="project-coverage-number"><strong>{report.coverage.boardType}</strong><span>Plattentypen</span><i>gegen</i><strong>{report.coverage.moistureApproval}</strong><span>Feuchtraumfreigaben</span></div></section>
    <section className="data-report-section project-coverage-matrix"><div><p className="eyebrow">Sechs Datenfelder</p><h2>Geometrie und technische Freigaben sind unterschiedlich vollständig.</h2></div><div><article><strong>{report.coverage.boardThickness}</strong><span>Plattendicken</span><p>Für 19 Produkte strukturiert erfasst.</p></article><article><strong>{report.coverage.boardDimensions}</strong><span>vollständige Plattenmaße</span><p>Nur acht Produkte besitzen Länge und Breite.</p></article><article><strong>{report.coverage.moistureApproval}</strong><span>Feuchtraumfreigaben</span><p>Vier ausdrückliche Angaben im Datensatz.</p></article><article><strong>{report.coverage.fireClass}</strong><span>Brandklassen</span><p>Keine strukturierte Klasse vorhanden.</p></article></div></section>
    <section className="data-report-section project-system-proof"><div><p className="eyebrow">Was ein belastbarer Nachweis verbindet</p><h2>Die Leistung gehört zum Aufbau, nicht zu einem einzelnen Suchtreffer.</h2></div><p>Platte, Profil, Dämmung, Schrauben, Fugenmaterial, Anschlussdetails und zulässige Wandhöhe wirken zusammen. Türen, Installationen und Lasten können den geprüften Aufbau zusätzlich verändern.</p><div><span>Platte</span><span>Profil</span><span>Dämmung</span><span>Fuge</span><span>Anschluss</span><strong>Systemnachweis</strong></div></section>
    <DataReportLinks items={[{ href: "/haus/innenausbau/trockenbau-rechner/", label: "Materialrahmen berechnen", description: "Mengen transparent ermitteln, Freigabe separat prüfen." }, { href: "/ratgeber/trockenbauwand-einfach-oder-doppelt-beplankt/", label: "Wandaufbau einordnen", description: "Lagen und Anforderungen differenziert betrachten." }, { href: "/ratgeber/daten/trockenbauprofile-breiten-laengen/", label: "Profildaten ansehen", description: "Breite, Länge und Packung vergleichen." }]} />
  </Frame>;
}

export function DrywallReport({ info }: { info: PageInfo }) {
  if (info.slug === "trockenbauplatten-typen-dicken") return <BoardReport info={info} />;
  if (info.slug === "trockenbauprofile-breiten-laengen") return <ProfileReport info={info} />;
  return <GapReport info={info} />;
}
