import Link from "next/link";
import { DataReportLinks, ReportBarList, ReportMetricGrid } from "@/components/data-report/DataReportBlocks";
import { ProjectReportFrame } from "@/components/data-report/ProjectReportFrame";
import { greenhouseProjectReport as report } from "@/lib/data-report/project-catalog-insights";

type PageInfo = { slug: string; path: string; title: string; description: string };
const euro = (value: number) => value.toLocaleString("de-DE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 });
const number = (value: number, digits = 0) => value.toLocaleString("de-DE", { minimumFractionDigits: digits, maximumFractionDigits: digits });

function Frame({ info, eyebrow, headline, introduction, takeawayTitle, takeaway, children }: { info: PageInfo; eyebrow: string; headline: React.ReactNode; introduction: string; takeawayTitle: string; takeaway: string; children: React.ReactNode }) {
  return <ProjectReportFrame path={info.path} title={info.title} description={info.description} topicLabel="Gewächshäuser" eyebrow={eyebrow} headline={headline} introduction={introduction} takeawayTitle={takeawayTitle} takeaway={takeaway} className="project-data-greenhouse" updated={report.updatedLabel} datasetName="PassendPlanen Gewächshausauswertung" datasetDescription={`Auswertung von ${report.total} geprüften Gewächshausprodukten, darunter ${report.kits.count} Bausätze.`} datasetSize={report.total} variables={["Produktart", "Grundfläche", "Höhe", "Verglasung", "Angebotspreis"]} method={<><p>Ausgewertet wurden alle geprüften Gewächshausprodukte im PassendPlanen Katalog. Flächenwerte entstehen aus dokumentierter Außenbreite und Außenlänge. Pro Produkt zählt der günstigste verfügbare Angebotspreis.</p><p>Außenfläche ist nicht gleich nutzbare Beetfläche. Rahmen, Wege, Türbereich und Konstruktion reduzieren den Innenraum. Verglasungsarten werden nur gezählt, wenn sie strukturiert dokumentiert sind. Die Stichprobe ist keine vollständige Marktübersicht.</p><p><Link href="/methodik/">Mehr zur Datenprüfung</Link>.</p></>} nextTitle="Beete, Weg und hohe Kulturen in ein reales Innenlayout übersetzen." nextText="Der Gewächshaus Planer beginnt bei Pflanzen und Bewegungsfläche. Dadurch wird sichtbar, welche Grundfläche und Höhe das persönliche Nutzungskonzept braucht." plannerHref="/garten/gewaechshaus-planer/" plannerLabel="Gewächshaus planen">{children}</ProjectReportFrame>;
}

function AreaReport({ info }: { info: PageInfo }) {
  return <Frame info={info} eyebrow="114 Gewächshäuser mit dokumentierter Grundfläche" headline={<>Mehr Fläche verändert den Preis. Entscheidend bleibt, <em>wie sie genutzt wird</em>.</>} introduction="Die Modelle reichen vom kleinen Tomatenhaus bis zum großen Kulturraum. Wir teilen sie in drei Flächenklassen und betrachten jeweils die Mitte der verfügbaren Angebotspreise." takeawayTitle="Außenfläche braucht einen Kulturplan" takeaway="Ein breites Haus mit zu schmalem Weg oder ungünstiger Tür kann weniger nutzbar sein als ein kleineres Modell mit passender Beetaufteilung.">
    <section className="data-report-section"><div className="data-report-heading"><p className="eyebrow">Die Größenbasis</p><h2>Die mittlere dokumentierte Außenfläche beträgt {number(report.kits.medianAreaM2, 1)} Quadratmeter.</h2></div><ReportMetricGrid ariaLabel="Gewächshaus Kennzahlen" items={[{ value: `${report.kits.count}`, label: "Gewächshaus Bausätze", note: `${report.coverage.area} Produkte mit vollständigen Außenmaßen` }, { value: `${number(report.kits.medianAreaM2, 1)} m²`, label: "mittlere Außenfläche", note: "Nicht als reine Beetfläche lesen" }, { value: euro(report.kits.medianPriceEur), label: "mittlerer Angebotspreis", note: "Fundament und Aufbau können hinzukommen" }, { value: `${report.brands}`, label: "dokumentierte Marken", note: "Unbekannte Marken werden nicht erfunden" }]} /></section>
    <section className="data-report-section greenhouse-area-story"><div><p className="eyebrow">Drei Flächenklassen</p><h2>Der größte Sprung entsteht oberhalb von zehn Quadratmetern.</h2><p>Die Klassen dienen der Orientierung. Ein Preisvergleich innerhalb engerer Modellfamilien bleibt aussagekräftiger als der Vergleich des gesamten Sortiments.</p></div><div className="project-data-card-grid">{report.areaBands.map((item) => <article key={item.label}><span>{item.label}</span><strong>{item.count} Modelle</strong><p>Mittlere Fläche {number(item.medianAreaM2, 1)} m²</p><p>Mittlerer Preis {euro(item.medianPriceEur)}</p></article>)}</div></section>
    <section className="data-report-section project-data-note"><div><p className="eyebrow">Von außen nach innen gegenprüfen</p><h2>Drei Flächen gehen von der Außenfläche ab.</h2></div><ol><li><strong>Weg</strong><span>Er muss auch mit Kisten und Gießkanne nutzbar bleiben.</span></li><li><strong>Rahmen und Sockel</strong><span>Die Konstruktion reduziert die freie Breite.</span></li><li><strong>Tür und Wendebereich</strong><span>Der Eingang braucht eine dauerhaft freie Zone.</span></li></ol></section>
    <DataReportLinks items={[{ href: "/garten/gewaechshaus-groesse/", label: "Gewächshausgröße berechnen", description: "Pflanzen und Wege in Fläche übersetzen." }, { href: "/garten/gewaechshaus-fundament/", label: "Fundament einordnen", description: "Untergrund und Systemvorgaben prüfen." }, { href: "/ratgeber/daten/gewaechshaus-glas-hohlkammerplatten/", label: "Verglasungen vergleichen", description: "Materialgruppen in der Stichprobe ansehen." }]} />
  </Frame>;
}

function GlazingReport({ info }: { info: PageInfo }) {
  const known = report.glazing.filter((item) => item.key !== "unknown").reduce((sum, item) => sum + item.count, 0);
  return <Frame info={info} eyebrow={`${known} Gewächshäuser mit dokumentierter Verglasung`} headline={<>Hohlkammerplatten sind häufiger. Das macht sie nicht automatisch zum <em>Materialsieger</em>.</>} introduction="Die Verglasungsgruppen unterscheiden sich gleichzeitig bei Modellgröße, Konstruktion und Markenmix. Wir zeigen Häufigkeit, mittlere Fläche und Angebotspreis, ohne die Unterschiede als allgemeine Materialwirkung auszugeben." takeawayTitle="Material und Modellklasse sind vermischt" takeaway="Ein Preisunterschied kann von Fläche, Profil, Plattenstärke oder Produktserie stammen. Die Stichprobe isoliert diese Einflüsse nicht.">
    <section className="data-report-section data-split-section"><div><p className="eyebrow">Verglasung im Sortiment</p><h2>Hohlkammerplatten stellen die größte dokumentierte Gruppe.</h2><p>{report.glazing.find((item) => item.key === "polycarbonate")?.count} Bausätze sind mit Hohlkammerplatten erfasst, {report.glazing.find((item) => item.key === "glass")?.count} mit Glas und {report.glazing.find((item) => item.key === "mixed")?.count} mit einer Mischverglasung. Bei weiteren Modellen bleibt die Verglasung unbekannt.</p></div><ReportBarList ariaLabel="Verglasungsarten" maxValue={report.kits.count} items={report.glazing.map((item) => ({ label: item.label, value: item.count, displayValue: `${item.count} Modelle`, detail: item.count > 0 ? `Mittlere Außenfläche ${number(item.medianAreaM2, 1)} m²` : undefined }))} /></section>
    <section className="data-report-section"><div className="data-report-heading"><p className="eyebrow">Preis und Fläche gemeinsam lesen</p><h2>Die Gruppen stehen nicht auf derselben Größenbasis.</h2></div><div className="data-table-wrap"><table><caption>Verglasung, Modellzahl, Fläche und Angebotspreis</caption><thead><tr><th>Verglasung</th><th>Modelle</th><th>Mittlere Fläche</th><th>Mittlerer Preis</th><th>Mittlere Preishälfte</th></tr></thead><tbody>{report.glazing.filter((item) => item.count > 0).map((item) => <tr key={item.key}><th>{item.label}</th><td>{item.count}</td><td>{number(item.medianAreaM2, 1)} m²</td><td>{euro(item.medianPriceEur)}</td><td>{euro(item.lowerPriceEur)} bis {euro(item.upperPriceEur)}</td></tr>)}</tbody></table></div></section>
    <section className="data-report-section project-material-questions"><div><p className="eyebrow">Vier Fragen für das konkrete Datenblatt</p><h2>Die Materialbezeichnung reicht nicht.</h2></div><ul><li><strong>Plattenstärke</strong><span>Sie beeinflusst Eigenschaften und Systemaufbau.</span></li><li><strong>Licht und Beschattung</strong><span>Kultur und Standort bestimmen den Bedarf.</span></li><li><strong>Befestigung</strong><span>Komplette Konstruktion und Austauschbarkeit prüfen.</span></li><li><strong>Schnee und Wind</strong><span>Herstellernachweise für den Standort bestätigen.</span></li></ul></section>
    <DataReportLinks items={[{ href: "/ratgeber/gewaechshaus-glas-oder-polycarbonat/", label: "Materialentscheidung vertiefen", description: "Nutzung und Standort statt pauschalem Sieger betrachten." }, { href: "/garten/gewaechshaus-belueftung/", label: "Lüftung planen", description: "Öffnungen aus Fläche und Nutzung ableiten." }, { href: "/ratgeber/daten/gewaechshaus-flaeche-preise/", label: "Größenklassen ansehen", description: "Fläche und Preis gemeinsam einordnen." }]} />
  </Frame>;
}

function ClimateReport({ info }: { info: PageInfo }) {
  return <Frame info={info} eyebrow="Höhe und Klimadaten im Produktfeed" headline={<>Die Grundfläche ist oft bekannt. Für Pflanzenhöhe und Lüftung bleibt <em>zu viel offen</em>.</>} introduction="114 Produkte besitzen Außenmaße, aber nur 65 eine strukturierte Höhenangabe. Türbreite und Zahl der Dachlüfter fehlen vollständig. Genau diese Werte beeinflussen Alltag und Luftführung." takeawayTitle="Mehr Quadratmeter lösen kein Höhenproblem" takeaway="Tomaten, Rankkulturen und Arbeitsraum benötigen nutzbare Höhe. Eine unbekannte Türbreite erschwert zusätzlich die Planung mit Schubkarre oder breiten Pflanzgefäßen.">
    <section className="data-report-section project-coverage-hero"><div><p className="eyebrow">Die asymmetrische Datenlage</p><h2>Fläche ist fast flächendeckend vorhanden, Klimaangaben nicht.</h2><p>Die mittlere dokumentierte Höhe beträgt {number(report.kits.medianHeightM, 2)} Meter. Dieser Wert beruht nur auf Produkten mit vorhandener Angabe und darf nicht auf die fehlenden Modelle übertragen werden.</p></div><div className="project-coverage-number"><strong>{report.coverage.area}</strong><span>mit Außenfläche</span><i>gegen</i><strong>{report.coverage.height}</strong><span>mit Höhenangabe</span></div></section>
    <section className="data-report-section data-evidence-gap"><div><p className="eyebrow">Was der Katalog nicht beantwortet</p><h2>Drei planungsrelevante Angaben fehlen ganz oder teilweise.</h2></div><div className="data-gap-grid"><article><strong>{report.coverage.height} von {report.total}</strong><h3>Höhe dokumentiert</h3><p>Eine Auswahl für hohe Kulturen benötigt das konkrete Innenprofil.</p></article><article><strong>{report.coverage.doorWidth} von {report.total}</strong><h3>Türbreite dokumentiert</h3><p>Der strukturierte Feed erlaubt keinen belastbaren Zugangsvergleich.</p></article><article><strong>{report.coverage.roofVents} von {report.total}</strong><h3>Dachlüfter gezählt</h3><p>Produktnamen werden nicht in vermeintlich sichere Lüftungswerte übersetzt.</p></article></div></section>
    <section className="data-report-section greenhouse-accessory-strip"><div><p className="eyebrow">Zubehör im selben Katalog</p><h2>Nur vier Produkte sind separat als Lüftung, Tisch oder Beschattung eingeordnet.</h2><p>Das geringe Zubehörangebot bedeutet nicht, dass Zubehör unnötig ist. Es zeigt nur, dass der aktuelle Partnerkatalog in diesem Bereich überwiegend Gewächshaus Bausätze enthält.</p></div><ReportBarList ariaLabel="Gewächshaus Produktarten" maxValue={report.total} items={report.kinds.map((item) => ({ label: item.label, value: item.count, displayValue: `${item.count} Produkte`, detail: item.count > 0 ? `Mittlerer Preis ${euro(item.medianPriceEur)}` : undefined }))} /></section>
    <section className="data-report-section project-measure-route"><div><p className="eyebrow">Klimaprüfung am Modell</p><h2>Vier Angaben gehören in die Gegenprobe.</h2></div><ul><li><span>01</span><strong>Trauf und Firsthöhe</strong><p>Hohe Kulturen und Stehhöhe getrennt prüfen.</p></li><li><span>02</span><strong>Türöffnung</strong><p>Breite und Höhe für den tatsächlichen Zugang messen.</p></li><li><span>03</span><strong>Öffnungsfläche</strong><p>Dachfenster und Zuluft gemeinsam betrachten.</p></li><li><span>04</span><strong>Beschattung</strong><p>Ausrichtung und sommerliche Überhitzung berücksichtigen.</p></li></ul></section>
    <DataReportLinks items={[{ href: "/garten/gewaechshaus-belueftung/", label: "Lüftungsbedarf einordnen", description: "Grundfläche und Öffnungsanteile verbinden." }, { href: "/garten/gewaechshaus-planer/", label: "Kulturplan erstellen", description: "Pflanzenhöhe und Wege gemeinsam planen." }, { href: "/ratgeber/daten/gewaechshaus-glas-hohlkammerplatten/", label: "Verglasungsdaten ansehen", description: "Dokumentierte Materialgruppen vergleichen." }]} />
  </Frame>;
}

export function GreenhouseReport({ info }: { info: PageInfo }) {
  if (info.slug === "gewaechshaus-flaeche-preise") return <AreaReport info={info} />;
  if (info.slug === "gewaechshaus-glas-hohlkammerplatten") return <GlazingReport info={info} />;
  return <ClimateReport info={info} />;
}
