import Link from "next/link";
import { DataReportLinks, ReportBarList, ReportMetricGrid } from "@/components/data-report/DataReportBlocks";
import { ProjectReportFrame } from "@/components/data-report/ProjectReportFrame";
import { privacyProjectReport as report } from "@/lib/data-report/project-catalog-insights";

type PageInfo = { slug: string; path: string; title: string; description: string };
const euro = (value: number) => value.toLocaleString("de-DE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 });
const number = (value: number) => value.toLocaleString("de-DE");

function Frame({ info, eyebrow, headline, introduction, takeawayTitle, takeaway, children }: { info: PageInfo; eyebrow: string; headline: React.ReactNode; introduction: string; takeawayTitle: string; takeaway: string; children: React.ReactNode }) {
  return <ProjectReportFrame path={info.path} title={info.title} description={info.description} topicLabel="Sichtschutz" eyebrow={eyebrow} headline={headline} introduction={introduction} takeawayTitle={takeawayTitle} takeaway={takeaway} className="project-data-privacy" updated={report.updatedLabel} datasetName="PassendPlanen Sichtschutzauswertung" datasetDescription={`Auswertung von ${report.total} geprüften Sichtschutzprodukten und ${report.panels.count} Elementen oder Matten.`} variables={["Produktart", "Elementbreite", "Elementhöhe", "Angebotspreis", "Systemkompatibilität"]} method={<><p>Die Auswertung umfasst alle geprüften Sichtschutzprodukte im PassendPlanen Katalog. Maß und Kostenrechnungen verwenden nur die {report.panels.count} Produkte mit dokumentierter Elementbreite und Höhe. Pro Produkt zählt das günstigste verfügbare Angebot.</p><p>Matten, starre Elemente und Dekorpaneele stehen gemeinsam im Datensatz. Die Zehn Meter Rechnung rundet auf vollständige Produkte auf, berücksichtigt aber weder Pfosten noch Tore, Fugen, Zuschnitt, Fundamente oder Lieferung.</p><p><Link href="/methodik/">Die Prüfmethode ansehen</Link>.</p></>} nextTitle="Die reale Flucht in Elemente, Pfosten und Restfelder aufteilen." nextText="Der Sichtschutz Planer rechnet mit gemessener Strecke, Elementbreite, Fuge, Ecken und Tor. Dadurch wird aus einem Produktmaß ein nachvollziehbares Raster." plannerHref="/garten/sichtschutz-planer/" plannerLabel="Sichtschutz planen">{children}</ProjectReportFrame>;
}

function DimensionsReport({ info }: { info: PageInfo }) {
  return <Frame info={info} eyebrow="80 Elemente und Matten mit dokumentierten Maßen" headline={<>Breite und Höhe erzeugen ein Raster. Der Produktname verrät das <em>Restfeld</em> nicht.</>} introduction="Die Stichprobe reicht von schmalen Elementen bis zu fünf Meter breiten Matten. Wir ordnen beide Maße in Klassen ein und zeigen, warum die reale Strecke vor der Produktauswahl feststehen muss." takeawayTitle="Breite wirkt direkt auf Pfosten und Zuschnitt" takeaway="Zehn schmale Elemente benötigen ein anderes Trag und Fugenraster als zwei breite Matten. Gleiche Gesamtlänge bedeutet deshalb nicht denselben Aufbau.">
    <section className="data-report-section"><div className="data-report-heading"><p className="eyebrow">Das typische Produkt in der Stichprobe</p><h2>Die Mitte liegt bei {number(report.panels.medianWidthCm)} Zentimetern Breite und {number(report.panels.medianHeightCm)} Zentimetern Höhe.</h2></div><ReportMetricGrid ariaLabel="Sichtschutz Maße" items={[{ value: `${report.panels.count}`, label: "Elemente und Matten", note: "Alle mit Breite und Höhe" }, { value: `${number(report.panels.medianWidthCm)} cm`, label: "mittlere Breite", note: "Starre Elemente und Rollenware gemeinsam" }, { value: `${number(report.panels.medianHeightCm)} cm`, label: "mittlere Höhe", note: "Zulässige Höhe lokal prüfen" }, { value: `${report.total - report.panels.count}`, label: "weitere Systemteile", note: "Pfosten, Tore, Halterungen und Fundamente" }]} /></section>
    <section className="data-report-section privacy-dimension-pair"><div><p className="eyebrow">Breitenklassen</p><h2>Breite Rollenware verändert die Statistik deutlich.</h2><ReportBarList ariaLabel="Breitenklassen" maxValue={report.panels.count} items={report.widthBands.map((item) => ({ label: item.label, value: item.count, displayValue: `${item.count} Produkte`, detail: `Mittlere Höhe ${number(item.medianHeightCm)} cm` }))} /></div><div><p className="eyebrow">Höhenklassen</p><h2>Hoher Sichtschutz ist nur ein Teil des Angebots.</h2><ReportBarList ariaLabel="Höhenklassen" maxValue={report.panels.count} items={report.heightBands.map((item) => ({ label: item.label, value: item.count, displayValue: `${item.count} Produkte`, detail: `Mittlere Breite ${number(item.medianWidthCm)} cm` }))} /></div></section>
    <section className="data-report-section project-data-note"><div><p className="eyebrow">Warum das Raster vor dem Kauf zählt</p><h2>Drei kleine Abweichungen summieren sich über die Strecke.</h2></div><ol><li><strong>Montagebreite</strong><span>Nennmaß, Pfosten und Fuge ergeben die tatsächliche Teilung.</span></li><li><strong>Restfeld</strong><span>Der letzte Abschnitt muss bewusst verteilt oder zugeschnitten werden.</span></li><li><strong>Tor und Ecke</strong><span>Beide unterbrechen den regelmäßigen Abstand.</span></li></ol></section>
    <DataReportLinks items={[{ href: "/garten/sichtschutz-elemente-berechnen/", label: "Elemente berechnen", description: "Strecke und Montagebreite zusammenführen." }, { href: "/garten/sichtschutz-gartentor-planen/", label: "Tor einplanen", description: "Öffnung und Anschlüsse im Raster berücksichtigen." }, { href: "/ratgeber/daten/sichtschutz-kosten-zehn-meter/", label: "Zehn Meter Szenario", description: "Rundung auf vollständige Elemente nachvollziehen." }]} />
  </Frame>;
}

function CostReport({ info }: { info: PageInfo }) {
  return <Frame info={info} eyebrow="Ein transparentes Szenario mit zehn Metern Strecke" headline={<>Zehn Meter Sichtschutz kosten nicht einfach zehnmal den <em>Meterpreis</em>.</>} introduction="Elemente und Matten werden vollständig gekauft. Für jedes Produkt berechnen wir deshalb, wie viele Einheiten mindestens zehn Meter Nennbreite abdecken. Restfelder und Systemteile bleiben sichtbar außerhalb der Rechnung." takeawayTitle="Die Rechnung ist eine Materialunterkante" takeaway="Pfosten, Halterungen, Fundament, Tor, Fugen und Lieferung fehlen. Bei starren Elementen kann ein Restfeld außerdem einen Zuschnitt oder eine andere Rasteraufteilung erzwingen.">
    <section className="data-report-section privacy-cost-lead"><div><p className="eyebrow">Alle 80 Maßprodukte</p><h2>Der mittlere reine Produktwert für zehn Meter liegt bei {euro(report.panels.medianTenMeterCostEur)}.</h2><p>Dieser Wert mischt flexible Matten, Dekorpaneele und starre Zaunelemente. Er ist deshalb keine Marktpreisprognose, sondern zeigt die Spannweite unterschiedlicher Produkttypen im aktuellen Katalog.</p></div><aside><span>{euro(report.panels.medianPricePerMeterEur)}</span><strong>rechnerischer Preis je Nennmeter</strong><p>Ohne Pfosten, Fugen und Restmaß.</p></aside></section>
    <section className="data-report-section"><div className="data-report-heading"><p className="eyebrow">Breite verändert die Aufrundung</p><h2>Drei Produktgruppen führen zu unterschiedlichen Einheitenzahlen.</h2></div><div className="project-data-card-grid">{report.widthBands.map((item) => <article key={item.label}><span>{item.label}</span><strong>{euro(item.medianTenMeterCostEur)}</strong><p>Mittlerer Produktwert für zehn Meter</p><p>{item.count} Produkte in der Gruppe</p></article>)}</div><div className="data-callout"><strong>Breite Matten sind nicht mit starren Feldern gleichzusetzen</strong><p>Rollenware kann an einem Stück befestigt werden, während starre Elemente Pfosten und definierte Anschlüsse benötigen. Die Rechnung vergleicht nur die abgedeckte Nennbreite.</p></div></section>
    <section className="data-report-section privacy-cost-formula"><div><p className="eyebrow">Die verwendete Rechnung</p><h2>Auf ganze Produkte runden, bevor der Preis multipliziert wird.</h2></div><div><span>Benötigte Produkte</span><strong>Aufrunden von 1.000 cm geteilt durch Produktbreite</strong><span>Reiner Produktwert</span><strong>Benötigte Produkte mal aktuellem Angebotspreis</strong></div></section>
    <DataReportLinks items={[{ href: "/garten/sichtschutz-planer/", label: "Eigenes Raster berechnen", description: "Pfosten, Fuge, Restfeld und Tor berücksichtigen." }, { href: "/garten/sichtschutz-pfosten-fundament/", label: "Pfosten und Fundament", description: "Konstruktive Fragen separat prüfen." }, { href: "/ratgeber/daten/sichtschutz-systemteile-datenluecken/", label: "Systemdaten prüfen", description: "Kompatibilitätslücken im Katalog verstehen." }]} />
  </Frame>;
}

function SystemReport({ info }: { info: PageInfo }) {
  return <Frame info={info} eyebrow="120 Sichtschutzprodukte nach Funktion getrennt" headline={<>80 Flächenelemente und 40 Systemteile. Trotzdem fehlt die <em>Kompatibilitätskette</em>.</>} introduction="Der Katalog enthält Pfosten, Tore, Halterungen und Fundamentteile. Strukturierte Systemkennungen oder Montagearten sind jedoch nicht vorhanden. Ein automatischer Warenkorb wäre deshalb nicht belastbar." takeawayTitle="Vorhanden bedeutet nicht kompatibel" takeaway="Ein Pfosten im selben Sortiment passt nicht automatisch zu jedem Element. Querschnitt, Nut, Befestiger, Höhe und Herstellerfreigabe müssen zusammengehören.">
    <section className="data-report-section data-split-section"><div><p className="eyebrow">Fünf Produktarten</p><h2>Die Teile eines Projekts sind im Katalog sichtbar.</h2><p>80 Produkte bilden die Fläche. Zwölf Pfosten, acht Tore, dreizehn Halterungen und sieben Fundamentteile ergänzen das Sortiment. Die reine Anzahl sagt jedoch nichts darüber, welche Teile ein freigegebenes System bilden.</p></div><ReportBarList ariaLabel="Sichtschutz Produktarten" maxValue={report.total} items={report.kinds.map((item) => ({ label: item.label, value: item.count, displayValue: `${item.count} Produkte`, detail: `Mittlerer Artikelpreis ${euro(item.medianPriceEur)}` }))} /></section>
    <section className="data-report-section project-system-chain"><div><p className="eyebrow">Die fehlende Verbindung</p><h2>Vier strukturierte Felder wären für eine automatische Kombination nötig.</h2></div><div className="project-system-chain-grid"><article><strong>{report.coverage.material}</strong><span>Materialangaben</span><p>Im aktuellen Datensatz nicht belastbar strukturiert.</p></article><article><strong>{report.coverage.postSystem}</strong><span>Pfostensystem Kennungen</span><p>Element und Pfosten lassen sich nicht sicher verbinden.</p></article><article><strong>{report.coverage.gateCompatible}</strong><span>Torkompatibilitäten</span><p>Ein passendes Tor kann nicht automatisch bestätigt werden.</p></article><article><strong>{report.coverage.mountingType}</strong><span>Montagearten</span><p>Einbetonieren und Aufschrauben bleiben offen.</p></article></div></section>
    <section className="data-report-section project-measure-route"><div><p className="eyebrow">Sichere Reihenfolge</p><h2>Das Systemdatenblatt verbindet die Einzelteile.</h2></div><ul><li><span>01</span><strong>Elementserie bestimmen</strong><p>Maß, Material und Windfreigabe prüfen.</p></li><li><span>02</span><strong>Pfosten zuordnen</strong><p>Profil und Anschluss aus derselben Freigabe wählen.</p></li><li><span>03</span><strong>Montage festlegen</strong><p>Boden, Höhe und Last bestimmen Fuß oder Fundament.</p></li><li><span>04</span><strong>Tor integrieren</strong><p>Beschlag, Öffnung und Anschlagseite mitplanen.</p></li></ul></section>
    <DataReportLinks items={[{ href: "/garten/sichtschutz-planer/", label: "Projektgeometrie planen", description: "Strecke und Unterbrechungen erfassen." }, { href: "/garten/sichtschutz-pfosten-fundament/", label: "Pfostenabstände prüfen", description: "Raster und Fundamentbedarf nachvollziehen." }, { href: "/ratgeber/daten/sichtschutz-elementbreiten-hoehen/", label: "Elementmaße auswerten", description: "Breiten und Höhen im Katalog vergleichen." }]} />
  </Frame>;
}

export function PrivacyReport({ info }: { info: PageInfo }) {
  if (info.slug === "sichtschutz-elementbreiten-hoehen") return <DimensionsReport info={info} />;
  if (info.slug === "sichtschutz-kosten-zehn-meter") return <CostReport info={info} />;
  return <SystemReport info={info} />;
}
