import Link from "next/link";
import { DataReportLinks, ReportBarList, ReportMetricGrid } from "@/components/data-report/DataReportBlocks";
import { ProjectReportFrame } from "@/components/data-report/ProjectReportFrame";
import { terraceProjectReport as report } from "@/lib/data-report/project-catalog-insights";

type PageInfo = { slug: string; path: string; title: string; description: string };
const euro = (value: number) => value.toLocaleString("de-DE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 });
const number = (value: number, digits = 0) => value.toLocaleString("de-DE", { minimumFractionDigits: digits, maximumFractionDigits: digits });

function Frame({ info, eyebrow, headline, introduction, takeawayTitle, takeaway, children }: { info: PageInfo; eyebrow: string; headline: React.ReactNode; introduction: string; takeawayTitle: string; takeaway: string; children: React.ReactNode }) {
  return <ProjectReportFrame path={info.path} title={info.title} description={info.description} topicLabel="Terrassen" eyebrow={eyebrow} headline={headline} introduction={introduction} takeawayTitle={takeawayTitle} takeaway={takeaway} className="project-data-terrace" updated={report.updatedLabel} datasetName="PassendPlanen Terrassenauswertung" datasetDescription={`Auswertung von ${report.total} geprüften Terrassenprodukten und ${report.decking.count} Dielen.`} variables={["Produktart", "Material", "Dielenlänge", "Dielenbreite", "Dielenstärke", "Packungsangaben", "Angebotspreis"]} method={<><p>Die Auswertung umfasst alle geprüften Terrassenprodukte im PassendPlanen Katalog. Abmessungsvergleiche verwenden die als Dielen erfassten Produkte. Preise sind aktuelle Angebotspreise pro gelistetem Produkt.</p><p>Da Paketfläche, lineare Packungsmenge und Stückzahl nur unvollständig dokumentiert sind, wird kein pauschaler Quadratmeterpreis erzeugt. Fuge, Unterkonstruktion, Zuschnitt, Befestigung und Lieferung sind nicht im Dielenpreis enthalten.</p><p><Link href="/methodik/">Die allgemeine Prüfmethode ansehen</Link>.</p></>} nextTitle="Reihen, Laufmeter und Zuschnitt aus der eigenen Terrasse berechnen." nextText="Der Terrassendielen Rechner verbindet Fläche, Verlegerichtung, Dielenbreite, Fuge und Lieferlänge. Unterkonstruktion und Befestigung bleiben eigene Materialgruppen." plannerHref="/garten/terrassen-dielen-rechner/" plannerLabel="Terrasse berechnen">{children}</ProjectReportFrame>;
}

function MaterialReport({ info }: { info: PageInfo }) {
  const wood = report.materials.find((item) => item.key === "wood")!;
  const wpc = report.materials.find((item) => item.key === "wpc")!;
  return <Frame info={info} eyebrow="80 Dielen nach Material und Maß" headline={<>Holz und WPC unterscheiden sich in dieser Stichprobe vor allem bei <em>Breite und Stärke</em>.</>} introduction="46 Dielen sind als Holz und 34 als WPC erfasst. Wir betrachten dokumentierte Abmessungen, ohne aus dem Sortiment einen allgemeinen Materialsieger abzuleiten." takeawayTitle="Maße beeinflussen die Mengenrechnung" takeaway="Eine breitere Diele reduziert die Zahl der Reihen. Länge und Verlegerichtung bestimmen Stöße und Zuschnitt. Das Material allein reicht für keine Bestellmenge.">
    <section className="data-report-section"><div className="data-report-heading"><p className="eyebrow">Der Dielenbestand</p><h2>Die mittlere Diele ist {number(report.decking.medianLengthMm)} Millimeter lang.</h2></div><ReportMetricGrid ariaLabel="Terrassendielen Kennzahlen" items={[{ value: `${report.decking.count}`, label: "geprüfte Dielen", note: `${wood.count} Holz und ${wpc.count} WPC` }, { value: `${number(report.decking.medianLengthMm)} mm`, label: "mittlere Länge", note: "Lieferlänge vor Zuschnitt" }, { value: `${number(report.decking.medianWidthMm)} mm`, label: "mittlere Breite", note: "Fuge noch nicht enthalten" }, { value: `${number(report.decking.medianThicknessMm, 1)} mm`, label: "mittlere Stärke", note: "Keine konstruktive Freigabe" }]} /></section>
    <section className="data-report-section terrace-material-duel"><article><p className="eyebrow">Holz</p><strong>{wood.count} Dielen</strong><dl><div><dt>Länge</dt><dd>{number(wood.medianLengthMm)} mm</dd></div><div><dt>Breite</dt><dd>{number(wood.medianWidthMm)} mm</dd></div><div><dt>Stärke</dt><dd>{number(wood.medianThicknessMm, 1)} mm</dd></div><div><dt>Artikelpreis</dt><dd>{euro(wood.medianPriceEur)}</dd></div></dl></article><div><p>Die Gruppen stammen aus verschiedenen Marken und Produktserien. Ein höherer Artikelpreis kann eine längere oder breitere Diele abbilden. Ohne sichere Verkaufseinheit entsteht daraus kein belastbarer Quadratmetervergleich.</p><span>Abmessungen vergleichbar</span><span>Systemeigenschaften produktbezogen</span><span>Preis je Fläche nicht freigegeben</span></div><article><p className="eyebrow">WPC</p><strong>{wpc.count} Dielen</strong><dl><div><dt>Länge</dt><dd>{number(wpc.medianLengthMm)} mm</dd></div><div><dt>Breite</dt><dd>{number(wpc.medianWidthMm)} mm</dd></div><div><dt>Stärke</dt><dd>{number(wpc.medianThicknessMm, 1)} mm</dd></div><div><dt>Artikelpreis</dt><dd>{euro(wpc.medianPriceEur)}</dd></div></dl></article></section>
    <section className="data-report-section project-material-questions"><div><p className="eyebrow">Vor dem Materialvergleich</p><h2>Vier Systemfragen bleiben außerhalb der Maßdaten.</h2></div><ul><li><strong>Auflagerabstand</strong><span>Herstellerwert für Profil und Lastfall prüfen.</span></li><li><strong>Fugenmaß</strong><span>Deckbreite aus Diele und freigegebener Fuge bilden.</span></li><li><strong>Befestigung</strong><span>Sichtbar oder verdeckt nur im freigegebenen System.</span></li><li><strong>Pflege und Oberfläche</strong><span>Standort und gewünschtes Erscheinungsbild einbeziehen.</span></li></ul></section>
    <DataReportLinks items={[{ href: "/ratgeber/terrassendielen-wpc-oder-holz/", label: "Holz oder WPC", description: "Nutzung und Pflege differenziert vergleichen." }, { href: "/garten/terrassendielen-verschnitt-fugen/", label: "Fugen und Verschnitt", description: "Deckbreite und Reserve berechnen." }, { href: "/ratgeber/daten/terrassendielen-laengen-verschnitt/", label: "Lieferlängen auswerten", description: "Länge und Verlegerichtung gemeinsam betrachten." }]} />
  </Frame>;
}

function LengthReport({ info }: { info: PageInfo }) {
  return <Frame info={info} eyebrow="79 Dielen mit vollständigem Längenmaß" headline={<>Die Lieferlänge entscheidet, wo geschnitten wird und <em>wo ein Stoß entsteht</em>.</>} introduction="Wir teilen die dokumentierten Dielen in drei Längenklassen. Die Häufigkeit zeigt, welche Formate im aktuellen Katalog stehen. Ob ein Format gut passt, entscheidet erst die Verlegerichtung auf der konkreten Fläche." takeawayTitle="Lange Dielen sind nicht automatisch verschnittarm" takeaway="Liegt die Lauflänge knapp über der Lieferlänge, entsteht pro Reihe ein zusätzlicher Abschnitt. Eine kürzere Diele kann bei passendem Raster günstiger aufgehen.">
    <section className="data-report-section terrace-length-map"><div><p className="eyebrow">Drei Lieferlängenbereiche</p><h2>Die mittlere Gruppe von über 2,5 bis 4 Metern ist am stärksten besetzt.</h2><p>Ein fehlendes Längenmaß bleibt außerhalb der Gruppierung. Alle Preise beziehen sich auf den gelisteten Artikel und werden nicht in Quadratmeterkosten umgerechnet.</p></div><ReportBarList ariaLabel="Dielen nach Lieferlänge" maxValue={report.decking.count} items={report.lengthBands.map((item) => ({ label: item.label, value: item.count, displayValue: `${item.count} Dielen`, detail: `Mittlere Länge ${number(item.medianLengthMm)} mm` }))} /></section>
    <section className="data-report-section terrace-cut-scenarios"><div><p className="eyebrow">Drei Geometrien, drei Folgen</p><h2>Verschnitt entsteht aus der Beziehung zwischen Fläche und Lieferlänge.</h2></div><div><article><span>Fall A</span><h3>Eine Diele deckt die Lauflänge</h3><p>Wenige Stöße, aber ein Reststück pro Reihe kann unbrauchbar bleiben.</p></article><article><span>Fall B</span><h3>Zwei Abschnitte je Reihe</h3><p>Stoßposition und Unterkonstruktion müssen im System zulässig sein.</p></article><article><span>Fall C</span><h3>Wechselnde Randlängen</h3><p>Rückschnitt, Hauskante und unregelmäßige Geometrie verändern die Wiederverwendung.</p></article></div></section>
    <section className="data-report-section project-data-note"><div><p className="eyebrow">Rechenweg für das Projekt</p><h2>Lieferlänge wird nicht durch einen pauschalen Prozentsatz ersetzt.</h2></div><ol><li><strong>Verlegerichtung festlegen</strong><span>Sie bestimmt die Lauflänge jeder Reihe.</span></li><li><strong>Reihen aus Deckbreite berechnen</strong><span>Dielenbreite und Fuge gemeinsam verwenden.</span></li><li><strong>Zuschnitt je Reihe planen</strong><span>Reststücke nur bei realer Wiederverwendung anrechnen.</span></li><li><strong>Reserve begründen</strong><span>Sortierung, Schäden und spätere Reparatur getrennt betrachten.</span></li></ol></section>
    <DataReportLinks items={[{ href: "/garten/terrassendielen-verschnitt-fugen/", label: "Verschnitt berechnen", description: "Dielenformat und Terrassengeometrie verbinden." }, { href: "/garten/terrasse-unterkonstruktion/", label: "Unterkonstruktion planen", description: "Stöße und Auflager im System prüfen." }, { href: "/ratgeber/daten/terrassendielen-holz-wpc-abmessungen/", label: "Materialmaße vergleichen", description: "Breite und Stärke nach Material ansehen." }]} />
  </Frame>;
}

function SystemReport({ info }: { info: PageInfo }) {
  return <Frame info={info} eyebrow="120 Terrassenprodukte nach Funktion getrennt" headline={<>Der mittlere Artikelpreis von 55 Euro ist für ein Terrassenprojekt <em>praktisch bedeutungslos</em>.</>} introduction="Dielen, Unterkonstruktion, Befestigung und Verbinder besitzen andere Einheiten und Aufgaben. Zusätzlich fehlen im Feed die Angaben, mit denen Artikelpreise zuverlässig auf Quadratmeter oder Laufmeter normiert werden könnten." takeawayTitle="Ein Preis braucht eine Bezugsgröße" takeaway="Ohne Stückzahl, Paketfläche oder lineare Packungsmenge ist ein Artikelpreis nicht mit einem anderen Produkt vergleichbar. Unbekannte Einheiten dürfen nicht geraten werden.">
    <section className="data-report-section data-split-section"><div><p className="eyebrow">Vier Produktarten</p><h2>Dielen stellen zwei Drittel des Katalogs.</h2><p>Unterkonstruktion und Befestigung sind als eigene Gruppen vorhanden. Das ist für einen vollständigen Materialrahmen wichtig, erlaubt aber noch keine automatische Systemkombination.</p></div><ReportBarList ariaLabel="Terrassen Produktarten" maxValue={report.total} items={report.kinds.map((item) => ({ label: item.label, value: item.count, displayValue: `${item.count} Produkte`, detail: `Mittlerer Artikelpreis ${euro(item.medianPriceEur)}` }))} /></section>
    <section className="data-report-section project-coverage-matrix"><div><p className="eyebrow">Warum kein Quadratmeter Ranking entsteht</p><h2>Die notwendigen Bezugsgrößen fehlen.</h2></div><div><article><strong>{report.coverage.boardDimensions}</strong><span>vollständige Dielenmaße</span><p>Geometrie ist bei fast allen Dielen verfügbar.</p></article><article><strong>{report.coverage.packageCoverage}</strong><span>Paketflächen</span><p>Kein Produkt besitzt eine strukturierte Flächenangabe.</p></article><article><strong>{report.coverage.packageLinearMeters}</strong><span>lineare Packungsmengen</span><p>Auch diese Bezugsgröße fehlt vollständig.</p></article><article><strong>{report.coverage.systemId}</strong><span>Systemkennungen</span><p>Dielen und Zubehör können nicht automatisch freigegeben werden.</p></article></div></section>
    <section className="data-report-section terrace-basket"><div><p className="eyebrow">Ein vollständiger Warenkorb</p><h2>Mindestens vier Mengen werden getrennt berechnet.</h2></div><dl><div><dt>Dielen</dt><dd>Reihen, Lauflänge, Zuschnitt und Reserve</dd></div><div><dt>Unterkonstruktion</dt><dd>Achsraster, Randprofile, Stöße und Auflager</dd></div><div><dt>Befestigung</dt><dd>Clips oder Schrauben je Auflagerpunkt</dd></div><div><dt>Abschlüsse</dt><dd>Blenden, Profile und konstruktive Details</dd></div></dl></section>
    <DataReportLinks items={[{ href: "/garten/terrassen-dielen-rechner/", label: "Vollständigen Bedarf berechnen", description: "Dielen und Unterkonstruktion getrennt ermitteln." }, { href: "/garten/terrasse-kosten/", label: "Projektkosten strukturieren", description: "Alle Materialgruppen und Arbeiten erfassen." }, { href: "/ratgeber/daten/terrassendielen-laengen-verschnitt/", label: "Längen und Verschnitt", description: "Lieferformat an der Geometrie prüfen." }]} />
  </Frame>;
}

export function TerraceReport({ info }: { info: PageInfo }) {
  if (info.slug === "terrassendielen-holz-wpc-abmessungen") return <MaterialReport info={info} />;
  if (info.slug === "terrassendielen-laengen-verschnitt") return <LengthReport info={info} />;
  return <SystemReport info={info} />;
}
