import { createPageMetadata } from "@/lib/metadata";
import { GuidePage } from "@/components/seo/GuidePage";
export const metadata = createPageMetadata({
  title: "Luftentfeuchter für den Keller",
  description: "Luftentfeuchter im Keller nach Raumgröße, Temperaturbereich, Ablauf und Herstellerfreigabe auswählen.",
  path: "/haus/raumklima/luftentfeuchter-keller/",
  kind: "article",
});
export default function Page(){return <GuidePage path="/haus/raumklima/luftentfeuchter-keller/" title="Luftentfeuchter im Keller: Temperatur zuerst prüfen" intro="Kühle Räume stellen andere Anforderungen als beheizte Wohnräume. Entscheidend sind Herstellerfreigabe, Temperaturbereich und eine realistische Einordnung der Feuchteursache." updated="August 2026" breadcrumbs={[{label:"Start",href:"/"},{label:"Haus",href:"/haus/"},{label:"Raumklima",href:"/haus/raumklima/"},{label:"Luftentfeuchter im Keller"}]} plannerHref="/haus/raumklima/luftentfeuchter-rechner/" plannerLabel="Gerätegröße berechnen" takeaway="Wähle kein Gerät nur nach Litern pro Tag. Prüfe zuerst Raumvolumen, minimale Betriebstemperatur und die Möglichkeit eines sicheren Ablaufs." limitation="Ein Entfeuchter behandelt Raumluft, aber nicht automatisch die Ursache von eindringendem Wasser, Leckagen, aufsteigender Feuchte oder Schimmel. Solche Hinweise fachlich untersuchen lassen." sections={[{title:"Kühle Luft verändert die Auswahl",paragraphs:["Die Nennleistung vieler Geräte wird unter warmen, feuchten Testbedingungen ermittelt. In einem kühlen Keller kann die reale Wasserentnahme deutlich niedriger ausfallen.","Der Rechner filtert deshalb anhand der freigegebenen minimalen Betriebstemperatur, sofern diese geprüft vorliegt. Eine hohe Prospektleistung ersetzt diese Freigabe nicht."]},{title:"Dauerablauf für längeren Betrieb",paragraphs:["Ein Schlauchanschluss kann sinnvoll sein, wenn ein geeigneter Ablauf vorhanden ist und Gefälle, Rückstau sowie Frost ausgeschlossen sind. Ein Anschluss allein garantiert keinen sicheren Betrieb.","Wenn du den Dauerablauf als erforderlich markierst, werden Geräte ohne bestätigte Anschlussmöglichkeit ausgeschlossen."]},{title:"Feuchteursache beobachten",paragraphs:["Kondensation, saisonal feuchte Außenluft und baulicher Wassereintritt benötigen unterschiedliche Maßnahmen. Dokumentiere Temperatur und relative Luftfeuchte über Zeit, statt nur einen Einzelwert zu betrachten."]}]} />}
