import type { MetadataRoute } from "next";
import { legalContactComplete } from "@/lib/legal";
import { SITE } from "@/lib/site";
export const dynamic = "force-static";
const siteUrl = SITE.url.replace(/\/$/, "");
export default function sitemap(): MetadataRoute.Sitemap {
  const paths: string[] = ["", "/rechner", "/garten", "/garten/gartenhaus-planer", "/garten/gartenhaus-groesse", "/garten/gartenhaus-fundament", "/garten/gartenhaus-kosten", "/garten/gartenhaus-fuer-fahrraeder", "/garten/gartenhaus-boden", "/garten/gartenhaus-zubehoer", "/garten/bewaesserungs-planer", "/garten/bewaesserung-durchfluss-messen", "/garten/tropfbewaesserung-hecke", "/garten/rasenbewaesserung-planen", "/garten/bewaesserungscomputer-zonen", "/garten/terrassen-dielen-rechner", "/garten/terrassendielen-verschnitt-fugen", "/garten/terrasse-unterkonstruktion", "/garten/terrasse-kosten", "/garten/sichtschutz-planer", "/garten/sichtschutz-elemente-berechnen", "/garten/sichtschutz-pfosten-fundament", "/garten/sichtschutz-gartentor-planen", "/garten/gewaechshaus-planer", "/garten/gewaechshaus-groesse", "/garten/gewaechshaus-fundament", "/garten/gewaechshaus-belueftung", "/garten/maehroboter-rechner", "/garten/maehroboter-flaeche-berechnen", "/garten/maehroboter-steigung-engstellen", "/garten/maehroboter-begrenzungskabel-kabellos", "/haus", "/haus/boden", "/haus/boden/bodenbelag-rechner", "/haus/boden/laminat-verschnitt-berechnen", "/haus/boden/untergrund-trittschall", "/haus/boden/sockelleisten-berechnen", "/haus/raumklima", "/haus/raumklima/luftentfeuchter-rechner", "/haus/raumklima/luftentfeuchter-keller", "/haus/raumklima/luftentfeuchter-stromverbrauch", "/haus/raumklima/luftentfeuchter-waesche", "/methodik", "/ueber-machplan", "/affiliate-transparenz"];
  if (legalContactComplete) paths.push("/impressum", "/datenschutz");
  return paths.map((path, index) => ({ url: `${siteUrl}${path}/`, lastModified: new Date("2026-08-10"), changeFrequency: index < 3 ? "weekly" : "monthly", priority: index === 0 ? 1 : index < 3 ? .9 : .7 }));
}
