import type { SeoGuideDepth } from "@/lib/seo-guide-depth";

type Input = {
  caption: string;
  rows: Array<[string, string, string]>;
  checklist: string[];
  faqs: Array<[string, string]>;
  links: Array<[string, string, string]>;
};

function depth(input: Input): SeoGuideDepth {
  return {
    comparison: { caption: input.caption, columns: ["Planungspunkt", "Bedeutung", "Konkrete Prüfung"], rows: input.rows },
    checklist: input.checklist,
    faqs: [
      ...input.faqs.map(([question, answer]) => ({ question, answer })),
      {
        question: `Wie nutze ich „${input.caption}“ für eine konkrete Entscheidung?`,
        answer: "Übertrage alle Messwerte und Bedingungen deines Projekts in eine einfache Skizze oder Tabelle. Markiere bestätigte Herstellerdaten, eigene Messungen und noch offene Annahmen getrennt. Vergleiche nur Lösungen, die alle harten Anforderungen erfüllen. Preis und Komfort gehören in den Vergleich, sobald die technischen Grenzen geklärt sind. Ein sicherheits-, bau- oder systemrelevanter offener Punkt muss vor der Bestellung fachlich oder anhand der verbindlichen Produktunterlagen geklärt werden.",
      },
    ],
    relatedLinks: input.links.map(([label, href, description]) => ({ label, href, description })),
  };
}

export const GUIDE_DEPTH_EXISTING_FINAL: Record<string, SeoGuideDepth> = {
  "/haus/raumklima/luftentfeuchter-waesche/": depth({
    caption: "Wäschetrocknung im Raum planen",
    rows: [["Raumvolumen", "Bestimmt die zu behandelnde Luftmenge.", "Fläche und lichte Höhe messen."], ["Wäschemenge", "Erzeugt zeitlich begrenzten Feuchtenachschub.", "Ladungen und Schleuderzustand dokumentieren."], ["Temperatur", "Beeinflusst reale Geräteleistung und Trocknung.", "Leistungsdaten bei Raumtemperatur vergleichen."], ["Luftführung", "Feuchte Luft muss das Gerät erreichen.", "Abstände, offene Türen und Wäscheständer anordnen."], ["Kosten", "Leistung mal Laufzeit mal Strompreis.", "Mehrere Trocknungsvorgänge messen statt Nennwert schätzen."]],
    checklist: ["Raum und Temperatur messen.", "Wäschemenge realistisch erfassen.", "Gerät mit freier Luftführung aufstellen.", "Hygrostat und Abschaltziel festlegen.", "Tank oder Dauerablauf sicher planen.", "Stromverbrauch und Trocknungsdauer dokumentieren."],
    faqs: [["Trocknet ein Luftentfeuchter Wäsche schneller?", "Er kann die von der Wäsche abgegebene Feuchte aus der Raumluft entfernen und dadurch die Trocknung unterstützen. Wirkung und Dauer hängen von Raum, Temperatur, Schleuderdrehzahl, Luftbewegung und Gerät ab. Wäschestücke müssen mit Abstand hängen, damit Luft alle Oberflächen erreicht."], ["Welche Ziel-Luftfeuchte ist beim Trocknen sinnvoll?", "Ein sehr niedriger Dauerwert ist nicht automatisch besser. Nutze einen kontrollierten Hygrostatbereich und beende den Betrieb, wenn Wäsche und Raum trocken genug sind. Beachte gleichzeitig Raumoberflächen und mögliche Feuchteursachen außerhalb der Wäschenutzung."], ["Luftentfeuchter oder Wäschetrockner – was kostet weniger?", "Das lässt sich nur mit realen Verbrauchs- und Laufzeitdaten vergleichen. Ein Entfeuchter trocknet Raum und Wäsche gemeinsam, ein Trockner arbeitet als geschlossenes Gerätesystem. Anschaffung, Kilowattstunden, Wäschemenge, Restfeuchte und benötigte Zeit gehören in denselben Vergleich."]],
    links: [["Luftentfeuchter-Rechner", "/haus/raumklima/luftentfeuchter-rechner/", "Raumvolumen und Feuchtelast einordnen."], ["Stromverbrauch", "/haus/raumklima/luftentfeuchter-stromverbrauch/", "Trocknungskosten nachvollziehbar berechnen."], ["Technikvergleich", "/ratgeber/luftentfeuchter-kompressor-oder-adsorption/", "Geräteprinzip für Temperatur und Nutzung wählen."]],
  }),
  "/garten/rasenbewaesserung-planen/": depth({
    caption: "Rasenflächen hydraulisch vorbereiten",
    rows: [["Geometrie", "Bestimmt Regnerposition und Sektoren.", "Fläche, Ecken und Hindernisse skizzieren."], ["Überlappung", "Sichert gleichmäßigere Wasserverteilung.", "Wurfweiten und Herstellerplanung verwenden."], ["Durchfluss", "Begrenzt gleichzeitig aktive Regner.", "Eimertest und Fließdruck messen."], ["Wind", "Verändert Wurfbild und Verteilung.", "Bewässerungszeit und Düsenwahl anpassen."], ["Boden", "Bestimmt Aufnahme und Laufzeit.", "Kurze Zyklen bei geringer Infiltration prüfen."]],
    checklist: ["Rasen in beregnungsfähige Zonen teilen.", "Durchfluss und Fließdruck messen.", "Regnerpositionen mit Überlappung zeichnen.", "Wege und Gebäude vor Fehlwurf schützen.", "Laufzeiten nach Boden und Wetter einstellen.", "Verteilung regelmäßig mit Behältern kontrollieren."],
    faqs: [["Wie viele Regner brauche ich?", "Die Zahl entsteht aus Geometrie, Wurfweite, Sektoren und notwendiger Überlappung. Eine reine Quadratmeterteilung ist unzuverlässig. Plane Regner von den Rändern und Ecken aus und prüfe, ob jede Zone innerhalb von Durchfluss und Fließdruck des Anschlusses bleibt."], ["Warum muss sich die Beregnung überlappen?", "Am Rand des Wurfbilds kommt häufig weniger Wasser an als nahe am Regner. Eine fachgerecht geplante Überlappung gleicht die Verteilung aus. Der notwendige Abstand folgt Düsen- und Herstellerdaten und muss bei Wind und realem Druck kontrolliert werden."], ["Wie lange sollte Rasen bewässert werden?", "Die Laufzeit hängt von Abgaberate, Boden, Wurzeltiefe, Wetter und Pflanzenzustand ab. Ermittle die tatsächlich verteilte Wassermenge mit Messbehältern und passe Intervalle an. Starre tägliche Minutenwerte ohne Messung können zu Oberflächenabfluss oder unnötigem Verbrauch führen."]],
    links: [["Durchfluss messen", "/garten/bewaesserung-durchfluss-messen/", "Anschlussleistung erfassen."], ["Rasen und Beete", "/ratgeber/bewaesserung-fuer-rasen-und-beete/", "Unterschiedliche Zonen gemeinsam planen."], ["Bewässerungsplaner", "/garten/bewaesserungs-planer/", "Materialstruktur und offene Messwerte zusammenführen."]],
  }),
  "/garten/bewaesserungscomputer-zonen/": depth({
    caption: "Steuerungszonen sinnvoll trennen",
    rows: [["Rasen", "Regner benötigen definierten Druck und Durchfluss.", "Nach Geometrie und verfügbarer Leistung aufteilen."], ["Hecke", "Tropfrohr arbeitet mit anderer Laufzeit.", "Länge, Druck und maximale Stranglänge prüfen."], ["Beet", "Pflanzenbedarf und Tropfer variieren.", "Ähnliche Flächen gemeinsam steuern."], ["Höhenlage", "Druck und Entleerung verändern sich.", "Starke Höhenunterschiede separat behandeln."], ["Sonne/Schatten", "Verdunstung und Bedarf unterscheiden sich.", "Nicht allein nach räumlicher Nähe gruppieren."]],
    checklist: ["Verbraucher nach Systemtyp gruppieren.", "Durchfluss je Zone addieren.", "Fließdruck gegen Herstellerbedarf prüfen.", "Laufzeiten getrennt einstellbar machen.", "Manuelle Sperre und Regensignal vorsehen.", "Ventile und Leitungen eindeutig beschriften."],
    faqs: [["Wie viele Bewässerungszonen sind sinnvoll?", "So viele, dass unterschiedliche Abgabesysteme und Pflanzenbedarfe getrennt steuerbar sind und jede Zone die verfügbare Anschlussleistung einhält. Mehr Zonen erhöhen Ventile und Aufwand, zu wenige führen häufig zu falschen Laufzeiten oder unzureichendem Druck."], ["Kann ein Bewässerungscomputer mehrere Ventile steuern?", "Das hängt vom Modell, der Stromversorgung und den kompatiblen Ventilen ab. Vergleiche Zahl unabhängiger Ausgänge, Sensoranschlüsse, Programme, manuelle Bedienung und Verhalten bei Strom- oder Internetausfall. Eine App allein bestätigt keine hydraulische Eignung."], ["Sollten Tropfrohr und Regner getrennt laufen?", "Meist ja, weil benötigter Druck, Durchfluss und Laufzeit unterschiedlich sind. Eine gemeinsame Zone erschwert die richtige Wassermenge für beide Flächen. Prüfe Komponentenkennlinien und verwende gegebenenfalls Filter oder Druckminderer entsprechend dem jeweiligen System."]],
    links: [["Bewässerungsplaner", "/garten/bewaesserungs-planer/", "Mindestzahl sinnvoller Zonen ermitteln."], ["Tropfschlauch oder Regner", "/ratgeber/bewaesserung-tropfschlauch-oder-regner/", "Systeme getrennt einordnen."], ["Durchfluss messen", "/garten/bewaesserung-durchfluss-messen/", "Hydraulische Grundlage schaffen."]],
  }),
  "/garten/terrasse-kosten/": depth({
    caption: "Vollständige Kostenblöcke einer Terrasse",
    rows: [["Dielen", "Fläche, Format, Lieferlänge und Verschnitt.", "Bestellmenge statt Nettofläche kalkulieren."], ["Unterkonstruktion", "Auflagerabstand und Stoßplan.", "Doppelte Träger und Randdetails ergänzen."], ["Untergrund", "Aushub, Frostschutz und Auflager.", "Gefälle, Entwässerung und Entsorgung berücksichtigen."], ["Befestigung", "Clips, Schrauben und Profile.", "Start-, End- und Ersatzteile mitrechnen."], ["Arbeit", "Zuschnitt, Montage und Logistik.", "Eigenleistung mit Werkzeug und Zeit bewerten."]],
    checklist: ["Fläche und Verlegerichtung festlegen.", "Konkretes Profil und Lieferlängen wählen.", "Unterkonstruktion vollständig zeichnen.", "Fundamente und Entwässerung kalkulieren.", "Lieferung, Werkzeug und Entsorgung ergänzen.", "Angebote auf identischen Umfang bringen."],
    faqs: [["Was kostet eine Terrasse pro Quadratmeter?", "Ohne Material, Untergrund, Aufbau und Eigenleistungsanteil ist ein Einzelwert irreführend. Addiere Dielen, Unterkonstruktion, Auflager, Befestigung, Randteile, Lieferung und Montage und teile erst dann durch die nutzbare Fläche. Dokumentiere offene Positionen als Spanne."], ["Warum sind die Dielen nicht der größte Kostenblock?", "Bei schwierigem Untergrund, geringer Aufbauhöhe oder vielen Details können Fundamente, Unterkonstruktion und Arbeit den Dielenpreis erreichen oder übertreffen. Stöße, Treppen, Blenden und Anschlüsse benötigen Material und Zeit, obwohl sie in der Quadratmeterfläche kaum sichtbar sind."], ["Wie vergleiche ich Eigenleistung mit einem Angebot?", "Setze Material, Werkzeug, Transport, Entsorgung, Helfer und realistische Arbeitszeit an. Berücksichtige außerdem das Risiko von Fehlzuschnitt oder Nacharbeit. So vergleichst du einen vollständigen Eigenleistungsrahmen mit einer klar beschriebenen Handwerkerleistung."]],
    links: [["Terrassen-Kostenvergleich", "/ratgeber/terrasse-kosten-materialvergleich/", "Kostenblöcke vertiefen."], ["Terrassen-Rechner", "/garten/terrassen-dielen-rechner/", "Materialmenge berechnen."], ["Unterkonstruktion", "/garten/terrasse-unterkonstruktion/", "Auflager und Stöße planen."]],
  }),
  "/garten/gartenhaus-zubehoer/": depth({
    caption: "Zubehör nach Funktion priorisieren",
    rows: [["Dachrinne", "Führt Niederschlag kontrolliert ab.", "Dachkante, Gefälle, Fallrohr und Überlauf."], ["Regale", "Nutzen Wandhöhe und ordnen Lagergut.", "Tragfähige Befestigung und Bediengang."], ["Lüftung", "Reduziert stehende feuchte Luft.", "Öffnungsposition und Witterungsschutz."], ["Rampe", "Überbrückt Schwelle für rollende Geräte.", "Rutschfestigkeit, Traglast und Wasserweg."], ["Sicherheit", "Beschläge, Schloss und interne Verankerung.", "Türsystem, Nutzung und Versicherungsvorgaben." ]],
    checklist: ["Zubehör aus Nutzung statt Paketwerbung ableiten.", "Befestigungspunkte und Traglast prüfen.", "Dachwasser vor Regentonne planen.", "Türweg und Arbeitsflächen freihalten.", "Elektroinstallation nur fachgerecht ausführen.", "Ersatzteile und Systemkompatibilität prüfen."],
    faqs: [["Welches Zubehör braucht jedes Gartenhaus?", "Eine pauschale Liste gibt es nicht. Fundamentanschluss, Verankerung und geeignete Dachdeckung gehören zum System; Rinne, Lüftung, Regale, Rampe oder Sicherheit folgen Standort und Nutzung. Priorisiere Bauteilschutz und sicheren Zugang vor Komfort- oder Dekorzubehör."], ["Kann ich Regale überall an der Wand befestigen?", "Nein. Bei Elementwänden müssen tragfähige Rahmenpositionen bekannt sein, bei Metallhäusern können Bohrungen Korrosionsschutz und Systemfreigabe beeinflussen, bei Blockbohlen ist Holzbewegung zu beachten. Last, Befestiger und Wandaufbau müssen zusammenpassen."], ["Ist eine Regentonne am Gartenhaus sinnvoll?", "Sie kann Dachwasser für den Garten sammeln, benötigt aber geeignete Dachmaterialien, Rinne, Filter, stabilen Stand, Überlauf und kindersichere Ausführung. Das theoretische Dachwasser ist kein garantierter Ertrag und dimensioniert weder Rinne noch Speicher."]],
    links: [["Gartenhaus-Planer", "/garten/gartenhaus-planer/", "Nutzung und Ausstattung priorisieren."], ["Gartenhaus-Boden", "/garten/gartenhaus-boden/", "Rampe und Schwelle abstimmen."], ["Gartenhaus-Kosten", "/garten/gartenhaus-kosten/", "Zubehör als eigenen Budgetblock erfassen."]],
  }),
  "/garten/gartenhaus-kosten/": depth({
    caption: "Kosten vom Standort bis zur Nutzung",
    rows: [["Haus", "Bausatz und definierter Lieferumfang.", "Boden, Dachdeckung und Anstrich abgleichen."], ["Fundament", "Untergrund und Lastübertragung.", "Aushub, Material, Entsorgung und Fachplanung."], ["Lieferung", "Abladen am vereinbarten Punkt.", "Zufahrt, Kran und Zwischenlagerung."], ["Aufbau", "Montage nach Anleitung.", "Helfer, Werkzeug, Wetter und Anpassungen."], ["Betrieb", "Pflege und Reparaturen über Jahre.", "Rinne, Beschichtung, Schloss und Ersatzteile." ]],
    checklist: ["Zielgröße und Nutzung zuerst bestimmen.", "Lieferumfang jedes Angebots normalisieren.", "Fundament separat kalkulieren.", "Lieferweg und Abladepunkt prüfen.", "Eigen- und Fremdleistung trennen.", "Offene Kosten sichtbar als Spanne führen."],
    faqs: [["Was wird beim Gartenhauskauf häufig vergessen?", "Fundament, Boden, Dachdeckung, Schutzanstrich, Rinne, Lieferung, Montagewerkzeug und Entsorgung sind nicht immer im Produktpreis enthalten. Auch schwieriger Zugang oder Geländeausgleich kann Kosten erzeugen. Vergleiche Angebote deshalb anhand derselben vollständigen Liste."], ["Ist ein günstiger Bausatz langfristig teurer?", "Das kann vorkommen, muss aber nicht. Materialqualität, Wartung, Lieferumfang, Ersatzteile und Montagequalität bestimmen die Folgekosten. Ein niedriger Kaufpreis ist nur dann vergleichbar, wenn Boden, Dach, Beschläge und notwendige Schutzarbeiten denselben Zweck erfüllen."], ["Wie genau kann ich vor dem Kauf kalkulieren?", "Für bekannte Angebote und Mengen sind genaue Werte möglich. Baugrund, Anpassungen und spätere Pflege bleiben unsicher. Trenne bestätigte Preise, nachvollziehbare Mengen und offene Annahmen. So entsteht eine belastbare Spanne statt einer scheinpräzisen Gesamtsumme."]],
    links: [["Kosten vergleichen", "/ratgeber/gartenhaus-kosten-vergleich/", "Angebote normalisieren."], ["Gartenhaus-Größe", "/garten/gartenhaus-groesse/", "Überdimensionierung vermeiden."], ["Gartenhaus-Fundament", "/garten/gartenhaus-fundament/", "Unterbau als Kostenblock planen."]],
  }),
  "/garten/gartenhaus-boden/": depth({
    caption: "Bodenaufbau nach Nutzung",
    rows: [["Leichte Lagerung", "Kisten und Handgeräte.", "Feuchte, Ebenheit und Regalfüße."], ["Fahrräder", "Rollende Last und täglicher Zugang.", "Schwelle, Rampe und rutschfeste Oberfläche."], ["Rasenmäher", "Höhere Punktlast und Verschmutzung.", "Traglast, Kraftstoff/Akku und Reinigung."], ["Werkbank", "Konzentrierte Last und Vibration.", "Verstärkung und tragfähige Stellzone."], ["Betonboden", "Robust und pflegeleicht.", "Feuchte, Gefälle und Hausanschluss." ]],
    checklist: ["Bodenpaket im Lieferumfang prüfen.", "Schwere Einzelgeräte dokumentieren.", "Flächen- und Punktlast klären.", "Schwelle und Rampe planen.", "Unterlüftung und Spritzwasser lösen.", "Fundament- und Bodenmaß abgleichen."],
    faqs: [["Braucht ein Gartenhaus einen Holzboden?", "Nicht zwingend. Die geeignete Nutzfläche kann aus einem freigegebenen Holzboden, einer geeigneten Betonoberfläche oder einem anderen abgestimmten Aufbau entstehen. Entscheidend sind Tragfähigkeit, Feuchte, Ebenheit, Nutzung und Anschluss an das konkrete Haussystem."], ["Wie hoch darf die Türschwelle sein?", "Es gibt keinen allgemeinen Komfortwert für jede Nutzung. Miss Räder und Geräte und prüfe, ob sie sicher über die Schwelle bewegt werden können. Eine Rampe benötigt Tragfähigkeit, rutschfeste Oberfläche, ausreichende Länge und eine Wasserführung weg vom Haus."], ["Wie schütze ich einen Holzboden vor Feuchte?", "Fundament und Unterbau müssen Wasser ableiten und Abstand zu dauerhaft feuchtem Erdreich schaffen. Unterlüftung, Spritzwasserschutz und vom Hersteller vorgesehene Trennlagen gehören zusammen. Eine zusätzliche Folie ohne abgestimmte Anschlüsse kann Feuchte einschließen."]],
    links: [["Mit Boden kaufen", "/ratgeber/gartenhaus-mit-boden-worauf-achten/", "Bodenpakete vergleichen."], ["Gartenhaus-Fundament", "/garten/gartenhaus-fundament/", "Tragende Basis vorbereiten."], ["Fahrrad-Gartenhaus", "/garten/gartenhaus-fuer-fahrraeder/", "Schwelle und Zugang konkret prüfen."]],
  }),
  "/garten/gewaechshaus-belueftung/": depth({
    caption: "Lüftungskomponenten und Aufgaben",
    rows: [["Dachfenster", "Warme Luft oben entweichen lassen.", "Öffnungsfläche, Position und Wind."], ["Tür", "Große Zuluft und Zugang.", "Sicherung, Tiere und unbeaufsichtigter Betrieb."], ["Seitenfenster", "Querlüftung unterstützen.", "Pflanzenhöhe und Niederschlagsschutz."], ["Automatiköffner", "Temperaturabhängig ohne Strom öffnen.", "Einstellbereich, Kraft und Wartung."], ["Beschattung", "Solaren Wärmeeintrag reduzieren.", "Material, Befestigung und Lichtbedarf." ]],
    checklist: ["Gewächshausvolumen und Öffnungen erfassen.", "Dach- und Zuluft gemeinsam planen.", "Automatik mit Fenstergewicht abgleichen.", "Beschattung für Sommerstandort prüfen.", "Pflanzen dürfen Öffnungen nicht blockieren.", "Temperatur und Feuchte regelmäßig messen."],
    faqs: [["Reicht eine offene Gewächshaustür zum Lüften?", "Sie schafft eine große Öffnung, warme Luft sammelt sich jedoch am Dach. Dachfenster unterstützen den natürlichen Auftrieb und können zusammen mit tiefer Zuluft wirksamer sein. Die notwendige Öffnungsfläche hängt von Haus, Standort und Kultur ab."], ["Wie funktioniert ein automatischer Fensteröffner?", "Viele Modelle nutzen ein temperaturabhängig expandierendes Medium und benötigen keinen Strom. Öffnungstemperatur, Hubkraft, Fenstergewicht und Montage müssen zusammenpassen. Der Öffner ersetzt keine Kontrolle und sollte nach Saison und Herstellerangabe gewartet werden."], ["Kann zu viel Lüftung Pflanzen schaden?", "Starker kalter Luftzug oder zu niedrige Temperaturen können Kulturen belasten. Lüftung soll Hitze und Feuchte kontrollieren, nicht unabhängig vom Wetter dauerhaft maximal offenstehen. Beobachte Temperatur, Wind und Pflanzenzustand und sichere Öffnungen gegen Schäden."]],
    links: [["Gewächshaus-Planer", "/garten/gewaechshaus-planer/", "Innenfläche und offene Lüftungsaufgaben erfassen."], ["Tomaten-Gewächshaus", "/ratgeber/gewaechshaus-fuer-tomaten-groesse/", "Lüftung für eine konkrete Kultur planen."], ["Glas oder Polycarbonat", "/ratgeber/gewaechshaus-glas-oder-polycarbonat/", "Material und Wärmeverhalten vergleichen."]],
  }),
  "/garten/sichtschutz-pfosten-fundament/": depth({
    caption: "Lastpfad eines Sichtschutzes",
    rows: [["Feld", "Nimmt Wind auf.", "Fläche, Durchlässigkeit und Systemfreigabe."], ["Halter", "Überträgt Last zum Pfosten.", "Anzahl, Abstand und Befestiger."], ["Pfosten", "Leitet Biegung zum Fundament.", "Querschnitt, Material und freie Höhe."], ["Fundament", "Verteilt Last in den Boden.", "Boden, Geometrie und Frost fachlich bestimmen."], ["Tor", "Zusätzliche bewegliche Lasten.", "Eigene Pfosten, Beschläge und Anschlag." ]],
    checklist: ["Feldhöhe und Winddurchlässigkeit erfassen.", "Pfostensystem und Herstellerabstände wählen.", "Boden und Gefälle prüfen.", "Torpfosten separat behandeln.", "Leitungen im Boden ausschließen.", "Fundamentabmessung fachlich bestätigen."],
    faqs: [["Wie tief muss ein Sichtschutzpfosten einbetoniert werden?", "Eine pauschale Tiefe ist ohne Boden, Höhe, Wind, Pfosten und System nicht belastbar. Herstellerangaben und standortbezogene Bemessung haben Vorrang. Auch Fundamentbreite, Betonqualität, Entwässerung und Frostbedingungen beeinflussen die Ausführung."], ["Sind Bodenhülsen für hohen Sichtschutz geeignet?", "Nur wenn das konkrete System, der Baugrund und die Windlast dafür freigegeben sind. Eine Bodenhülse ist kein allgemeiner Ersatz für ein bemessenes Fundament. Bei geschlossenen hohen Feldern entstehen große Windkräfte, die über alle Verbindungen sicher abgetragen werden müssen."], ["Warum brauchen Tore stärkere Pfosten?", "Torflügel erzeugen Gewicht, Hebel und dynamische Lasten beim Öffnen oder Zuschlagen. Beschläge konzentrieren Kräfte auf wenige Punkte. Verwende die vorgesehenen Torpfosten, Fundamente und Anschläge des Systems und behandle das Tor nicht wie ein normales Sichtschutzfeld."]],
    links: [["Sichtschutz-Planer", "/garten/sichtschutz-planer/", "Felder und Pfosten zählen."], ["Gartentor planen", "/garten/sichtschutz-gartentor-planen/", "Tor-Modul und Zugang einordnen."], ["Elemente berechnen", "/garten/sichtschutz-elemente-berechnen/", "Montageraster und Restfeld bestimmen."]],
  }),
  "/haus/boden/untergrund-trittschall/": depth({
    caption: "Untergrund und Unterlage getrennt prüfen",
    rows: [["Ebenheit", "Sichert gleichmäßige Auflage.", "Nach Produkt- und Fachregel messen."], ["Restfeuchte", "Schützt Belag und Träger.", "Geeignete Messung vor Verlegung."], ["Festigkeit", "Verhindert Bewegung und Schäden.", "Lose Stellen und Altbelag bewerten."], ["Trittschall", "Reduziert Schall in angrenzende Räume.", "Geprüften Systemwert verwenden."], ["Wärme", "Unterlage beeinflusst Heizleistung.", "Gesamt-Wärmewiderstand prüfen." ]],
    checklist: ["Untergrundart und Aufbau dokumentieren.", "Ebenheit und Festigkeit prüfen.", "Restfeuchte fachgerecht messen.", "Belagfreigabe zur Unterlage abgleichen.", "Fußbodenheizung berücksichtigen.", "Integrierte Unterlage nicht ungeprüft doppeln."],
    faqs: [["Gleicht Trittschalldämmung Unebenheiten aus?", "Nur sehr begrenzt und nicht als Ersatz für einen fachgerecht vorbereiteten Untergrund. Zu große Unebenheiten belasten Klickverbindungen und erzeugen Bewegung. Der Untergrund muss die Anforderungen des konkreten Bodenbelags erfüllen, bevor eine Unterlage verlegt wird."], ["Brauche ich unter jedem Laminat eine zusätzliche Unterlage?", "Nein. Manche Produkte besitzen eine integrierte Unterlage oder schreiben eine bestimmte Kombination vor. Eine doppelte Schicht kann Stabilität und Wärmewiderstand verschlechtern. Beachte Verlegeanleitung, Untergrund und Fußbodenheizung des vollständigen Systems."], ["Was ist wichtiger: Raum- oder Trittschall?", "Beide beschreiben unterschiedliche Wirkungen. Raumschall betrifft das Gehgeräusch im Raum, Trittschall die Übertragung in angrenzende Bereiche. Ein Produkt kann in einem Bereich gut und im anderen anders wirken. Vergleiche geprüfte Werte und den realen Gebäudekontext."]],
    links: [["Laminat oder Vinyl", "/ratgeber/bodenbelag-laminat-oder-vinyl/", "Belag nach Raum auswählen."], ["Fußbodenheizung", "/ratgeber/laminat-auf-fussbodenheizung/", "Wärmewiderstand des Aufbaus prüfen."], ["Bodenbelag-Rechner", "/haus/boden/bodenbelag-rechner/", "Unterlage und Materialmenge berechnen."]],
  }),
  "/garten/sichtschutz-gartentor-planen/": depth({
    caption: "Tor als eigenes Systemmodul",
    rows: [["Lichte Breite", "Freier Durchgang.", "Personen, Geräte und Schubkarre messen."], ["Modulmaß", "Tor inklusive Pfosten und Fugen.", "Nicht mit Türblattbreite verwechseln."], ["Öffnungsrichtung", "Bestimmt Schwenkfläche.", "Gefälle, Weg und Grundstücksgrenze."], ["Beschläge", "Tragen und führen den Flügel.", "Gewicht, Material und Justierbarkeit."], ["Anschlag", "Begrenzt und sichert Bewegung.", "Wind und unbeabsichtigtes Zuschlagen." ]],
    checklist: ["Benötigte lichte Durchgangsbreite bestimmen.", "Komplettes Tor-Modulmaß beschaffen.", "Öffnungsrichtung im Grundriss testen.", "Gefälle und Bodenfreiheit prüfen.", "Torpfosten und Fundamente separat planen.", "Schloss, Anschlag und Kindersicherheit berücksichtigen."],
    faqs: [["Wie breit sollte ein Gartentor sein?", "Die lichte Breite richtet sich nach der breitesten regelmäßigen Nutzung: Person, Mülltonne, Fahrrad, Rasenmäher oder Schubkarre. Berücksichtige, dass Geräte nicht immer exakt gerade geführt werden. Das Bestellmaß kann wegen Pfosten und Beschlägen deutlich größer sein."], ["Soll das Tor nach innen oder außen öffnen?", "Die Öffnungsrichtung muss Grundstücksgrenzen, öffentliche Wege, Gefälle, Wind und den verfügbaren Schwenkraum beachten. Ein nach außen öffnender Flügel darf keine unzulässige Gefahr oder Behinderung erzeugen. Prüfe örtliche Situation und Systemvorgaben vor Fundamentbau."], ["Warum zählt das Tor nicht wie ein normales Feld?", "Es besitzt bewegliche Lasten, Beschläge, Anschlag und meist eigene Pfosten. Sein Modulmaß umfasst mehr als die sichtbare Flügelbreite. Ziehe das vollständige Tor-Modul zuerst von der Strecke ab und berechne anschließend die verbleibenden Sichtschutzfelder."]],
    links: [["Sichtschutz-Planer", "/garten/sichtschutz-planer/", "Tor und Felder gemeinsam berechnen."], ["Pfostenfundament", "/garten/sichtschutz-pfosten-fundament/", "Torlasten separat berücksichtigen."], ["Elemente berechnen", "/garten/sichtschutz-elemente-berechnen/", "Reststrecke und Raster abschließen."]],
  }),
  "/haus/innenausbau/trockenbau-tuer-oeffnungen/": depth({
    caption: "Öffnungen verändern das Ständerwerk",
    rows: [["Türbreite", "Unterbricht reguläres Raster.", "Türständer und Sturz nach System."], ["Türgewicht", "Erzeugt dynamische Lasten.", "Geeignete Profile und Zarge."], ["Installationsöffnung", "Entfernt Platten- und Dämmfläche.", "Randprofile und Brandschutzdetails."], ["Fuge", "Darf nicht ungünstig an Ecke enden.", "Plattenaufteilung nach System planen."], ["Zarge", "Benötigt passendes Rohbaumaß.", "Bodenaufbau und Endhöhe berücksichtigen." ]],
    checklist: ["Zargen- und Türdaten vor Profilbau beschaffen.", "Rohbauöffnung inklusive Bodenaufbau festlegen.", "Zusatzständer und Sturz nach System planen.", "Plattenfugen von Öffnungsecken wegführen.", "Elektro und Installationen koordinieren.", "Schall- und Brandschutzdetails beibehalten."],
    faqs: [["Wie wird eine Türöffnung im Trockenbau verstärkt?", "Das hängt von Wandhöhe, Türbreite, Türgewicht, Zarge und System ab. Häufig sind verstärkte Türständer, passende Anschlusswinkel und ein Sturzprofil vorgesehen. Verwende die dokumentierte Systemlösung statt improvisierter Profilkombinationen."], ["Wird die Türfläche von der Plattenmenge abgezogen?", "Rechnerisch ja, doch um die Öffnung entstehen Zuschnitt, Fugenversatz und oft kleine Reststücke. Zusätzlich benötigte Profile und Befestiger bleiben bestehen. Die Nettofläche ist deshalb nur ein Teil der vollständigen Materialplanung."], ["Warum dürfen Plattenfugen nicht direkt an Türecken enden?", "Öffnungsecken sind spannungsreiche Bereiche. Ungünstige Fugen können Risse begünstigen. Plattenaufteilung, Fugenversatz und Befestigung folgen dem gewählten Trockenbausystem. Plane das Format vor dem Zuschnitt, nicht erst während der Montage."]],
    links: [["Trockenbau-Rechner", "/haus/innenausbau/trockenbau-rechner/", "Öffnungen in der Mengenplanung berücksichtigen."], ["Platten berechnen", "/haus/innenausbau/trockenbau-platten-berechnen/", "Zuschnitt und Verschnitt planen."], ["Profile und Ständerwerk", "/haus/innenausbau/trockenbau-profile-staenderwerk/", "Zusatzprofile zum Grundraster ergänzen."]],
  }),
  "/garten/carport-fundament/": depth({
    caption: "Vom Pfosten zur Gründung",
    rows: [["Pfostenraster", "Definiert Lastpunkte.", "Systemzeichnung statt Außenmaß verwenden."], ["Baugrund", "Bestimmt Tragfähigkeit und Setzung.", "Bei Unsicherheit untersuchen lassen."], ["Wind", "Erzeugt Zug- und Horizontallasten.", "Verankerung des Gesamtsystems."], ["Schnee/Dach", "Erzeugt vertikale Last.", "Standort- und Systemfreigabe."], ["Pfostenträger", "Verbindet Tragwerk und Beton.", "Korrosion, Einbauhöhe und Befestigung." ]],
    checklist: ["Exaktes Pfostenraster beschaffen.", "Boden und Leitungen am Standort prüfen.", "Standortlasten fachlich klären.", "Pfostenträger systemgerecht wählen.", "Beton und Abmessungen bemessen lassen.", "Entwässerung und fertige Höhe berücksichtigen."],
    faqs: [["Wie groß muss ein Carportfundament sein?", "Ohne Lasten, Pfosten, Baugrund, Frost und System ist keine pauschale Abmessung seriös. Fundament und Bewehrung müssen die Kräfte des konkreten Carports sicher in den Boden übertragen. Herstellerpläne und standortbezogene Fachplanung sind maßgeblich."], ["Kann ein Carport auf vorhandenes Pflaster gestellt werden?", "Pflaster allein bestätigt keine ausreichende Gründung für Pfostenlasten und Windsog. Häufig benötigen Pfosten eigene Fundamente unter oder durch die Fläche. Prüfe Aufbau, Leitungen, Entwässerung und das vorgesehene Verankerungssystem vor dem Bohren oder Ausschachten."], ["Warum müssen Pfostenträger ausgerichtet werden?", "Sie legen Pfostenposition, Höhe und oft die Montageachse fest. Kleine Abweichungen können Dach, Gefälle und Anschlüsse beeinträchtigen. Verwende eine genaue Vermessung mit Diagonalen und sichere die Träger während des Betonierens gegen Verschieben."]],
    links: [["Carport-Planer", "/garten/carport-planer/", "Pfostenraster aus dem gewählten System vorbereiten."], ["Carport-Größe", "/garten/carport-groesse/", "Lichte und äußere Maße trennen."], ["Holz oder Aluminium", "/ratgeber/carport-holz-oder-aluminium/", "Tragwerksmaterial nach Raumplanung wählen."]],
  }),
  "/garten/tropfbewaesserung-hecke/": depth({
    caption: "Tropfrohr entlang einer Hecke",
    rows: [["Heckenlänge", "Grundlage der Rohrmenge.", "Reale Pflanzstrecke messen."], ["Tropferabstand", "Bestimmt Abgabepunkte.", "Produktwert und Pflanzabstand abgleichen."], ["Stranglänge", "Begrenzt gleichmäßige Versorgung.", "Herstellermaximum und Druck beachten."], ["Höhenunterschied", "Verändert Druckverteilung.", "Zonen oder druckkompensierende Produkte prüfen."], ["Boden", "Beeinflusst Wasserverteilung.", "Laufzeit und Linienzahl anpassen." ]],
    checklist: ["Hecke und Höhenprofil messen.", "Tropfrohrdaten beschaffen.", "Maximale Stranglänge prüfen.", "Filter und Druckminderer planen.", "Enden spülbar und zugänglich halten.", "Laufzeit über Bodenfeuchte kontrollieren."],
    faqs: [["Wie viel Tropfrohr brauche ich für eine Hecke?", "Ausgangspunkt ist die gemessene Heckenlänge, ergänzt um Anschluss- und Verlegereserve. Bei breiten oder mehrreihigen Pflanzungen können mehrere Linien nötig sein. Maximale Stranglänge und Höhenunterschied entscheiden, ob die Strecke geteilt werden muss."], ["Wie lange darf ein Tropfrohr sein?", "Das hängt von Rohr, Tropferabstand, Druck, Abgabe und Höhenprofil ab. Verwende den maximalen Wert des konkreten Produkts und bleibe bei schwierigen Bedingungen darunter oder teile in Zonen. Eine universelle Meterzahl ist hydraulisch nicht belastbar."], ["Soll das Tropfrohr unter Mulch liegen?", "Das kann Verdunstung und Sichtbarkeit reduzieren, muss aber mit Produktfreigabe, Kontrolle und Schutz vor Beschädigung vereinbar sein. Anschlüsse und Spülenden sollten zugänglich bleiben. Prüfe regelmäßig, ob Tropfer funktionieren und Wurzeln gleichmäßig versorgt werden."]],
    links: [["Bewässerungsplaner", "/garten/bewaesserungs-planer/", "Rohrmenge und Zonen erfassen."], ["Tropfschlauch oder Regner", "/ratgeber/bewaesserung-tropfschlauch-oder-regner/", "Systemwahl begründen."], ["Durchfluss messen", "/garten/bewaesserung-durchfluss-messen/", "Anschlussleistung prüfen."]],
  }),
  "/garten/gewaechshaus-fundament/": depth({
    caption: "Fundamentaufgaben beim Gewächshaus",
    rows: [["Ebenheit", "Hält Rahmen rechtwinklig.", "Diagonalen und Höhen kontrollieren."], ["Verankerung", "Sichert gegen Wind.", "Vollständiges Herstellersystem verwenden."], ["Frost/Setzung", "Schützt Ausrichtung und Scheiben.", "Baugrund und Standort berücksichtigen."], ["Entwässerung", "Verhindert stehendes Wasser.", "Gefälle und Außenbereich planen."], ["Innenboden", "Bestimmt Wege und Beete.", "Nicht mit tragender Gründung verwechseln." ]],
    checklist: ["Sockelmaß aus Montageplan übernehmen.", "Boden und Gefälle dokumentieren.", "Fundamentvariante freigeben lassen.", "Verankerung und Rahmenanschluss planen.", "Wege und Beete innerhalb des Rasters festlegen.", "Regenwasser vom Fundament wegführen."],
    faqs: [["Braucht jedes Gewächshaus ein Betonfundament?", "Nein. Hersteller bieten je nach Größe und System unterschiedliche Lösungen an, etwa Fundamentrahmen oder andere verankerte Aufbauten. Entscheidend sind Ebenheit, Lastübertragung, Wind, Baugrund und dauerhafte Ausrichtung. Verwende nur eine für das konkrete Haus freigegebene Lösung."], ["Warum ist die Verankerung so wichtig?", "Ein Gewächshaus besitzt große Flächen, an denen Wind angreifen kann. Rahmen, Scheiben und Fundament müssen Kräfte gemeinsam übertragen. Ein schwerer Sockel ohne passenden Rahmenanschluss ist keine vollständige Verankerung. Beachte Standort- und Montagevorgaben."], ["Kann ich im Gewächshaus Pflaster als Weg verwenden?", "Ein geeigneter Weg kann Pflege und Sauberkeit erleichtern. Er muss zum Fundament und Beetaufbau passen, Wasser ableiten und darf Rahmen oder Verankerung nicht behindern. Plane fertige Höhen vor dem Aufbau, damit Tür und Schwelle zugänglich bleiben."]],
    links: [["Gewächshaus-Planer", "/garten/gewaechshaus-planer/", "Sockelprofile und Innenaufteilung vorbereiten."], ["Gewächshaus-Größe", "/garten/gewaechshaus-groesse/", "Außenmaß aus Beeten und Wegen ableiten."], ["Glas oder Polycarbonat", "/ratgeber/gewaechshaus-glas-oder-polycarbonat/", "Gewicht und System vor der Gründung wählen."]],
  }),
  "/haus/boden/sockelleisten-berechnen/": depth({
    caption: "Sockelleistenmenge aus Raumumfang",
    rows: [["Wände", "Summe aller relevanten Wandlängen.", "Nischen und Vorsprünge einzeln messen."], ["Türen", "Öffnungen ohne Leiste abziehen.", "Zargenanschluss und Endstücke beachten."], ["Lieferlänge", "Bestimmt Zahl voller Leisten.", "Stöße und nutzbare Reststücke planen."], ["Ecken", "Benötigen Gehrung oder Formteile.", "Innen- und Außenecken zählen."], ["Reserve", "Deckt Zuschnitt und Schäden.", "Nach Raumform und Material begründen." ]],
    checklist: ["Alle Wandabschnitte einzeln messen.", "Türöffnungen und feste Unterbrechungen abziehen.", "Innen- und Außenecken zählen.", "Lieferlänge des Produkts übernehmen.", "Stoß- und Zuschnittplan erstellen.", "Befestiger, Verbinder und Endstücke ergänzen."],
    faqs: [["Wie berechne ich laufende Meter Sockelleiste?", "Addiere alle Wandabschnitte, an denen eine Leiste montiert wird, und ziehe Türöffnungen oder feste Unterbrechungen ab. Ergänze eine begründete Reserve für Zuschnitt und teile durch die Lieferlänge. Runde auf ganze Leisten auf."], ["Kann ich kurze Reststücke weiterverwenden?", "Technisch passende Stücke können verwendet werden, wenn Stöße sauber angeordnet und Mindestlängen eingehalten werden. Zu viele kurze Stücke wirken unruhig und erhöhen Verbindungspunkte. Plane sichtbare Wände möglichst mit langen Leisten und nutze Reste in geeigneten kurzen Abschnitten."], ["Was muss ich außer Leisten kaufen?", "Je nach System gehören Innen- und Außenecken, Verbinder, Endkappen, Clips, Schrauben oder Kleber dazu. Zargenanschlüsse und Heizungsrohre können Sonderteile oder Zuschnitt erfordern. Zähle diese Elemente anhand des Raumplans getrennt."]],
    links: [["Bodenbelag-Rechner", "/haus/boden/bodenbelag-rechner/", "Leisten zusammen mit Paketen berechnen."], ["Laminat-Verschnitt", "/haus/boden/laminat-verschnitt-berechnen/", "Bodenmenge separat bestimmen."], ["Untergrund und Trittschall", "/haus/boden/untergrund-trittschall/", "Aufbau vor der Verlegung prüfen."]],
  }),
  "/garten/carport-dachentwaesserung/": depth({
    caption: "Dachwasser vom Carport führen",
    rows: [["Dachprojektion", "Grundlage des theoretischen Volumens.", "Wirksame horizontale Fläche ermitteln."], ["Niederschlag", "Liter je Quadratmeter und Millimeter.", "Örtliche Bemessungswerte fachlich verwenden."], ["Rinne", "Sammelt Wasser an der Traufe.", "Gefälle, Querschnitt und Befestigung."], ["Fallrohr", "Leitet Wasser nach unten.", "Querschnitt, Übergang und Frost."], ["Ziel", "Speicher, Versickerung oder zulässige Ableitung.", "Überlauf und örtliche Regeln klären." ]],
    checklist: ["Dachfläche und Ablaufseite bestimmen.", "Rinne und Fallrohr bemessen lassen.", "Regentonne standsicher aufstellen.", "Überlauf für Starkregen planen.", "Wasser von Fundamenten fernhalten.", "Zulässige Versickerung oder Einleitung klären."],
    faqs: [["Wie viel Regenwasser liefert ein Carportdach?", "Geometrisch entspricht ein Millimeter Niederschlag auf einem Quadratmeter einem Liter. Eine 18-m²-Projektion liefert bei zehn Millimetern theoretisch 180 Liter. Wind, Spritzwasser, Rinne und Speicher reduzieren den nutzbaren Ertrag. Der Wert dimensioniert keine Bauteile."], ["Kann das Wasser einfach neben dem Carport versickern?", "Das hängt von Boden, Abstand zu Gebäuden und Grenzen sowie örtlichen Anforderungen ab. Unkontrolliertes Wasser kann Fundamente oder Nachbarflächen belasten. Plane ein definiertes Ziel und kläre Versickerung oder Einleitung standortbezogen."], ["Wie groß sollte eine Regentonne sein?", "Größe entsteht aus Dachfläche, typischem Niederschlag, Gartenbedarf, verfügbarem Platz und sicherem Überlauf. Eine sehr große Tonne bleibt ohne Verbrauch voll, eine kleine läuft oft über. Standsicherheit, Abdeckung und geeigneter Anschluss sind ebenso wichtig wie Volumen."]],
    links: [["Carport-Planer", "/garten/carport-planer/", "Dachfläche im Gesamtprojekt erfassen."], ["Carport-Größe", "/garten/carport-groesse/", "Außenmaß und Dachprojektion unterscheiden."], ["Carport-Material", "/ratgeber/carport-holz-oder-aluminium/", "Dachsystem und Tragwerk gemeinsam vergleichen."]],
  }),
  "/haus/innenausbau/trockenbau-profile-staenderwerk/": depth({
    caption: "Profile im Wandaufbau",
    rows: [["Randprofile", "Führen Wand an Boden und Decke.", "Anschluss, Dichtung und Befestigung."], ["Ständer", "Tragen Platten und bilden Raster.", "Profil, Abstand, Höhe und Ausrichtung."], ["Türständer", "Nehmen Türlasten auf.", "Systemprofil und Anschlusswinkel."], ["Sturz", "Überbrückt Öffnung.", "Breite, Profil und Befestigung."], ["Verstärkung", "Trägt besondere Lasten.", "Position vor Beplankung dokumentieren." ]],
    checklist: ["Freigegebenes Wandsystem auswählen.", "Wandhöhe und Anforderungen prüfen.", "Grundraster aus Plattenformat ableiten.", "Öffnungen und Zusatzständer ergänzen.", "Anschlüsse und Dichtungsband planen.", "Installationen und Lastverstärkungen koordinieren."],
    faqs: [["Welcher Ständerabstand ist richtig?", "Der Abstand folgt Trockenbausystem, Plattenformat, Wandhöhe, Plattentyp und Lagen. Eine pauschale Zahl darf nicht auf jedes System übertragen werden. Verwende Tabellen und Montageunterlagen des ausgewählten Herstellers für die konkrete Konstruktion."], ["Werden Türständer im normalen Raster mitgezählt?", "Die rechnerischen Grundständer bilden nur das ungestörte Raster. Türen benötigen zusätzliche oder verstärkte Profile und einen Sturz. Zähle Öffnungsprofile separat, damit der Materialbedarf nicht durch die Nettofläche unterschätzt wird."], ["Wo plane ich Verstärkungen für Hängeschränke?", "Vor der Beplankung an den späteren Befestigungspunkten. Last, Ausladung und Befestiger bestimmen, ob Traversen, zusätzliche Profile oder andere Lösungen erforderlich sind. Dokumentiere Lage und Maße, damit die Verstärkung nach dem Schließen der Wand auffindbar bleibt."]],
    links: [["Trockenbau-Rechner", "/haus/innenausbau/trockenbau-rechner/", "Grundständer und Randprofile berechnen."], ["Türen und Öffnungen", "/haus/innenausbau/trockenbau-tuer-oeffnungen/", "Zusatzprofile detailliert planen."], ["Einfach oder doppelt", "/ratgeber/trockenbauwand-einfach-oder-doppelt-beplankt/", "Lagen und Anforderungen abstimmen."]],
  }),
};
