import type { SeoGuide } from "@/lib/seo-guides";

export const SEO_GUIDES_WAVE2 = [
  {
    slug: "gartenhaus-blockbohlen-oder-elementbauweise",
    title: "Blockbohlenhaus oder Elementhaus: Gartenhaus-Bauweisen vergleichen",
    description: "Blockbohlenhaus und Elementhaus vergleichen: Montage, Wandaufbau, Setzung, Stabilität, Pflege und Nutzung vor dem Gartenhauskauf prüfen.",
    heading: "Blockbohlenhaus oder Elementhaus: Der Wandaufbau bestimmt mehr als die Optik",
    intro: "Beide Bauweisen können ein belastbares Gartenhaus ergeben. Unterschiede entstehen bei Montage, Fugen, Setzungsverhalten, Anpassbarkeit und dem vorgesehenen Nutzungsniveau.",
    takeaway: "Vergleiche vollständigen Wandaufbau, Verbindung, Wind- und Schneelastfreigabe, Bodenanschluss und Montageablauf. Die beworbene Wandstärke allein entscheidet nicht über die Qualität.",
    plannerHref: "/garten/gartenhaus-planer/",
    plannerLabel: "Gartenhaus planen",
    sections: [
      { title: "Blockbohlen werden Lage für Lage verbunden", paragraphs: ["Bei einem Blockbohlenhaus greifen profilierte Bohlen an den Ecken und über Nut-und-Feder-Verbindungen ineinander. Der Aufbau erzeugt eine massive Holzwirkung und erlaubt je nach System relativ freie Innenbefestigungen. Gleichzeitig müssen Bohlen trocken, gerade und nach Montageanleitung verarbeitet werden.", "Holz arbeitet mit wechselnder Feuchte. Türen, Fenster, Dachanschlüsse und fest montierte Einbauten müssen das konstruktiv vorgesehene Bewegungs- oder Setzungsverhalten berücksichtigen. Schrauben oder Regale dürfen nicht ungeprüft mehrere bewegliche Bohlen starr verbinden."] },
      { title: "Elementbauweise arbeitet mit vormontierten Flächen", paragraphs: ["Elementhäuser bestehen aus vorbereiteten Wandfeldern oder Rahmen, die auf dem Boden- beziehungsweise Sockelsystem ausgerichtet und verbunden werden. Das kann die Montage beschleunigen, verlangt aber einen sehr ebenen Untergrund und exakt passende Anschlüsse.", "Die sichtbare Wandstärke beschreibt nicht automatisch Rahmen, Bekleidung, Aussteifung oder Tragfähigkeit. Für Regale und schwere Halterungen muss bekannt sein, wo tragfähige Rahmenteile liegen und welche Befestigung der Hersteller erlaubt."] },
      { title: "Montage und spätere Nutzung gemeinsam bewerten", paragraphs: ["Ein vermeintlich einfacher Bausatz kann durch Gewicht, lange Bauteile, Dachhöhe oder fehlenden Arbeitsraum anspruchsvoll werden. Prüfe Paketmaße, benötigte Helfer, Werkzeug, Wetterschutz während des Aufbaus und die Reihenfolge von Boden, Wänden und Dach.", "Für die Nutzung zählen anschließend echte Innenmaße, Tür, Bodenlast, Lüftung und Schutz vor Feuchte. Eine Bauweise ist nicht pauschal besser; sie muss zu Standort, Eigenleistung und geplanter Ausstattung passen."] },
      { title: "Datenblatt statt Bauweisen-Label", paragraphs: ["Vergleiche Sockelmaß, Außenmaß, Dachüberstand, Wandaufbau, Holzfeuchtehinweise, Verbindungsmittel und Lastfreigaben. Auch Garantie und Reklamationsbedingungen können davon abhängen, dass Fundament, Oberflächenbehandlung und Montage exakt dokumentiert wurden."] },
    ],
  },
  {
    slug: "gartenhaus-pultdach-oder-satteldach",
    title: "Gartenhaus mit Pultdach oder Satteldach: Welches Dach passt?",
    description: "Pultdach und Satteldach beim Gartenhaus vergleichen: Innenhöhe, Regenwasser, Schneelast, Dachdeckung, Standort und Nutzung verständlich prüfen.",
    heading: "Pultdach oder Satteldach: Dachform nach Standort und Nutzung wählen",
    intro: "Die Dachform beeinflusst Innenhöhe, Wasserführung, Aufbau und Außenmaß. Optik ist wichtig, aber Gefälle, Dachdeckung und Entwässerung entscheiden über die Funktion.",
    takeaway: "Wähle die Dachform erst nach Standort, gewünschter Innenhöhe, zulässigem Außenmaß, Wasserführung und freigegebener Dachdeckung. Plane Rinne und Ablauf vor der Fundamentposition.",
    plannerHref: "/garten/gartenhaus-planer/",
    plannerLabel: "Gartenhaus planen",
    sections: [
      { title: "Pultdach bündelt Wasser auf einer Seite", paragraphs: ["Ein Pultdach besitzt eine geneigte Dachfläche. Dadurch lässt sich Niederschlag gezielt zu einer Traufseite führen, sofern Rinne, Gefälle und Dachdeckung zusammenpassen. Die hohe Wandseite kann innen mehr nutzbare Höhe für Regale oder lange Gegenstände bieten.", "Die Ausrichtung der Traufe muss zum Grundstück passen. Wasser darf nicht unkontrolliert auf Nachbarflächen, Wege oder empfindliche Bauteile gelangen. Auch die hohe Seite, Dachüberstand und Arbeitsraum verändern den tatsächlichen Platzbedarf."] },
      { title: "Satteldach verteilt Höhe und Entwässerung", paragraphs: ["Beim Satteldach treffen zwei geneigte Flächen am First zusammen. Die Form wirkt klassisch und bietet in der Mitte zusätzliche Höhe, während Wasser zu zwei Traufseiten abläuft. Für Rinnen entstehen dadurch gegebenenfalls zwei getrennte Sammelstrecken.", "Die nutzbare Höhe an den Seiten kann geringer sein als der First vermuten lässt. Vergleiche deshalb Wandhöhe, Firsthöhe, Türhöhe und geplante Regale anhand einer Schnittzeichnung statt nur der maximalen Außenhöhe."] },
      { title: "Dachdeckung und Lastfreigabe gehören zusammen", paragraphs: ["Bitumenbahn, Schindeln, Metall oder andere Deckungen stellen unterschiedliche Anforderungen an Mindestgefälle, Untergrund und Befestigung. Eine schwerere oder abweichende Deckung darf nicht ungeprüft auf einen Bausatz übertragen werden.", "Wind- und Schneelast werden für das vollständige System angegeben. Standort, Verankerung und regelmäßige Kontrolle bleiben relevant, unabhängig davon, welche Dachform optisch bevorzugt wird."] },
      { title: "Regenwasser als Teil der Planung", paragraphs: ["Rinne, Fallrohr, Regentonne, Überlauf und zulässige Versickerung benötigen Platz. Lege die Ablaufseite fest, bevor Fundament und Türposition endgültig bestimmt werden. So vermeidest du, dass Wasserweg und täglicher Zugang miteinander kollidieren."] },
    ],
  },
  {
    slug: "gartenhaus-fuer-vier-fahrraeder",
    title: "Gartenhaus für vier Fahrräder: Größe, Tür und Stellplan",
    description: "Gartenhaus für vier Fahrräder planen: Stellfläche, Türbreite, Bewegungsraum, Halterungen, Akkus und Diebstahlschutz sinnvoll bestimmen.",
    heading: "Vier Fahrräder im Gartenhaus: Zugang ist wichtiger als reine Bodenfläche",
    intro: "Vier Fahrräder passen rechnerisch schnell in einen kleinen Raum. Alltagstauglich wird er erst, wenn jedes Rad ohne gefährliches Stapeln und möglichst ohne komplettes Umräumen erreichbar bleibt.",
    takeaway: "Plane Fahrradlänge, Lenkerbreite, Tür, Schwenkfläche und den Zugriff auf jedes Rad. E-Bike-Gewicht, Ladeort und Wandhalterungen verändern die benötigte Aufteilung.",
    plannerHref: "/garten/gartenhaus-planer/",
    plannerLabel: "Fahrrad-Gartenhaus planen",
    sections: [
      { title: "Vier Räder sind nicht vier identische Rechtecke", paragraphs: ["Citybike, Mountainbike, Lastenrad und Kinderfahrrad unterscheiden sich bei Länge, Lenker, Gewicht und täglicher Nutzung. Miss die vorhandenen Räder einschließlich Körben, Kindersitzen und Spiegeln. Ein zukünftiges größeres Kinder- oder E-Bike sollte als Reserve sichtbar eingeplant werden.", "Die reine Standfläche reicht nicht. Ein Fahrrad wird durch die Tür geschoben, gedreht und aus einer Halterung gehoben. Dieser Bewegungsraum darf nicht gleichzeitig dauerhaft durch Rasenmäher, Regale oder Getränkekisten blockiert sein."] },
      { title: "Tür und Schwelle bestimmen den täglichen Komfort", paragraphs: ["Eine breite Doppeltür kann mehrere Räder zugänglich machen, benötigt außen aber Schwenkraum. Eine einzelne Tür kann funktionieren, wenn der Stellplan klare Fahrgassen bietet. Prüfe lichte Öffnung und nicht nur das Rohbau- oder Türblattmaß.", "Hohe Schwellen sind bei schweren E-Bikes unangenehm. Eine sichere, rutschfeste Rampe muss zur Tür und zum Boden passen und darf Wasser nicht in das Haus leiten."] },
      { title: "Halterungen sparen nur mit passender Bedienfläche", paragraphs: ["Vertikale Wandhalter können Bodenfläche sparen, verlangen aber Tragfähigkeit, ausreichende Wandhöhe und Kraft zum Anheben. Versetzte Lenkerhöhen reduzieren Konflikte, erschweren jedoch den unabhängigen Zugriff, wenn die Räder zu dicht stehen.", "Bodenständer sind einfach, benötigen aber mehr Tiefe. Deckenhalter oder sehr hohe Systeme sind für schwere E-Bikes oft unpraktisch. Plane die Halterung nach dem schwersten und meistgenutzten Fahrrad."] },
      { title: "Akkus, Feuchte und Diebstahlschutz", paragraphs: ["Akkus sollten nach Herstellerhinweisen bei geeigneter Temperatur und trocken gelagert werden; das Gartenhaus ist nicht automatisch ein guter Ladeort. Für Diebstahlschutz zählen Tür, Beschläge, Verankerung und ein geeigneter interner Anschlusspunkt. Lüftung und trockener Boden schützen außerdem Kette, Bremse und Elektronik."] },
    ],
  },
  {
    slug: "maehroboter-rtk-oder-lidar",
    title: "Mähroboter mit RTK oder LiDAR: Navigation im Vergleich",
    description: "RTK- und LiDAR-Mähroboter vergleichen: Satellitenempfang, Bäume, Gebäude, Kartierung, Grenzen, Störungen und Gartenstruktur richtig bewerten.",
    heading: "RTK oder LiDAR: Welche Navigation passt zu deinem Garten?",
    intro: "RTK bestimmt Positionen über Satellit und Korrekturdaten, LiDAR erfasst die Umgebung mit Lasersensoren. Beide Prinzipien haben starke Einsatzfelder und klare Standortgrenzen.",
    takeaway: "RTK braucht verlässliche Sicht- und Funkbedingungen; LiDAR braucht eine ausreichend erfassbare Umgebung. Prüfe kritische Stellen im Garten und das Verhalten bei Störung, bevor du Komfortfunktionen vergleichst.",
    plannerHref: "/garten/maehroboter-rechner/",
    plannerLabel: "Gartenprofil prüfen",
    sections: [
      { title: "RTK arbeitet mit globaler Position und Korrektur", paragraphs: ["RTK-Systeme nutzen Satellitensignale und Korrekturdaten, um eine virtuelle Karte mit präzisen Grenzen aufzubauen. Je nach Hersteller stammt die Korrektur von einer lokalen Referenzstation oder einem Netzwerkdienst. Die Qualität hängt von Empfang, Antennenposition und Verbindung ab.", "Dichte Baumkronen, hohe Gebäude, enge Gebäudegassen und überdachte Flächen können die Bedingungen verändern. Gute Systeme kombinieren zusätzliche Sensoren, doch die Werbeangabe RTK allein beschreibt nicht, wie ein Modell bei kurzfristigem Signalverlust reagiert."] },
      { title: "LiDAR misst die Umgebung relativ zum Roboter", paragraphs: ["LiDAR sendet Lichtimpulse aus und erstellt aus den Reflexionen ein räumliches Bild. Das kann unter Bäumen oder ohne freie Satellitensicht Vorteile bieten. Sensorposition, Reichweite und Software entscheiden, wie Grenzen und Hindernisse verarbeitet werden.", "Sehr offene, strukturarme Bereiche oder Veränderungen durch Gartenmöbel, hohe Vegetation und Baustellen können die Kartierung beeinflussen. Auch Verschmutzung und Regentropfen am Sensor gehören in Wartung und Alltagstest."] },
      { title: "Die härtesten Stellen entscheiden", paragraphs: ["Markiere zuerst Baumgruppen, Hauskanten, Durchgänge, überdachte Bereiche, Mauern, Teichränder und öffentliche Wege. Prüfe für jedes System, ob genau diese Stellen sicher kartiert und befahren werden können. Eine Technologie kann auf 95 Prozent der Fläche funktionieren und an einer kritischen Grenze trotzdem ausscheiden.", "Achte außerdem auf Mehrzonen, Kartenbearbeitung, temporäre Sperrflächen und Wiederaufnahme nach Störung. Software und Updateversorgung sind bei beiden Prinzipien ein wesentlicher Teil des Produkts."] },
      { title: "Rückgabe und Testmöglichkeit einplanen", paragraphs: ["Signalbedingungen lassen sich nicht vollständig aus einer Produktseite ableiten. Kläre deshalb Installationsservice, Testmöglichkeit, Rückgabebedingungen und die Dokumentation problematischer Bereiche. Ein nachvollziehbarer Standorttest ist wertvoller als eine pauschale Navigationsrangliste."] },
    ],
  },
  {
    slug: "maehroboter-fuer-500-qm",
    title: "Mähroboter für 500 m²: Welche Flächenklasse wirklich passt",
    description: "Mähroboter für 500 Quadratmeter auswählen: Nettofläche, Reserve, Hindernisse, Zonen, Steigung, Laufzeit und Navigation richtig einordnen.",
    heading: "Mähroboter für 500 m²: Die Nennfläche ist nur der Anfang",
    intro: "Eine beworbene Kapazität von 500 m² bedeutet nicht automatisch, dass das Gerät jeden 500-m²-Garten komfortabel bearbeitet. Form, Hindernisse und gewünschte Mähzeiten verändern die passende Klasse.",
    takeaway: "Berechne zuerst die echte Netto-Rasenfläche. Ergänze danach eine sichtbare Reserve für Komplexität, getrennte Zonen und Zeitfenster und prüfe harte Grenzen wie Steigung und Passagen separat.",
    plannerHref: "/garten/maehroboter-rechner/",
    plannerLabel: "500-m²-Garten prüfen",
    sections: [
      { title: "500 Quadratmeter Grundstück sind selten 500 Quadratmeter Rasen", paragraphs: ["Ziehe Haus, Terrasse, Wege, Beete, Teich, Gartenhaus und andere dauerhaft nicht gemähte Flächen ab. Messe getrennte Teilflächen einzeln und dokumentiere, ob sie durch befahrbare Passagen verbunden sind. Das Ergebnis ist die Netto-Rasenfläche.", "Ein Grundstück mit 500 m² kann nur 250 m² Rasen besitzen. Umgekehrt kann eine Nettofläche nahe 500 m² durch Hindernisse und schmale Bereiche deutlich anspruchsvoller sein als eine offene rechteckige Fläche."] },
      { title: "Reserve wird aus Komplexität begründet", paragraphs: ["Hersteller-Nennflächen beruhen auf definierten Annahmen. Viele Hindernisse, mehrere Zonen, starke Wachstumsphasen oder eingeschränkte Mähzeiten können mehr Kapazität sinnvoll machen. Die Reserve sollte sichtbar und anpassbar sein, nicht als scheinbar exakte Universalzahl erscheinen.", "Eine größere Klasse kann kürzere tägliche Laufzeiten ermöglichen, kostet aber möglicherweise mehr und ist körperlich größer. Prüfe deshalb auch Wendigkeit, Passagen und Kanten statt nur eine höhere Zahl zu bevorzugen."] },
      { title: "Navigation und Gartenform", paragraphs: ["Ein einfacher Garten kann mit Kabel oder kabelloser Navigation funktionieren. Unter Bäumen, an langen Hauswänden oder bei getrennten Bereichen müssen Empfang und Systemlogik genauer geprüft werden. Die Entscheidung RTK, Kamera, LiDAR oder Kabel entsteht aus dem Standort.", "Notiere, wo die Ladestation stehen kann und wie der Roboter sie aus jeder Zone erreicht. Ein theoretisch ausreichender Mäher ist ungeeignet, wenn die Verbindung zur Station nicht zuverlässig befahrbar ist."] },
      { title: "Vergleich mit identischen Bedingungen", paragraphs: ["Vergleiche mindestens Fläche, Steigung, Mindestpassage, Navigation, Geräusch, Kantenlösung, Schutzfunktionen, Lieferumfang und Service. Preise sind erst aussagekräftig, wenn Installation und notwendiges Zubehör mitgerechnet werden."] },
    ],
  },
  {
    slug: "maehroboter-fuer-hanglage",
    title: "Mähroboter für Hanglage: Steigung, Traktion und Kanten prüfen",
    description: "Mähroboter für Hanggrundstücke auswählen: Prozent und Grad, Übergänge, Seitenhang, Boden, Nässe, Allrad und Absturzkanten richtig prüfen.",
    heading: "Mähroboter am Hang: Nicht der Durchschnitt, sondern die härteste Stelle zählt",
    intro: "Ein Hang ist mehr als ein Prozentwert. Übergang, Fahrtrichtung, Feuchte, Boden und eine Kante am Gefälle können schwieriger sein als die gemessene Neigung allein.",
    takeaway: "Miss die steilste zu mähende Stelle in der richtigen Einheit und dokumentiere Übergänge, Seitenhang, Boden und kritische Ränder. Vergleiche diese Situation mit den Bedingungen des konkreten Modells.",
    plannerHref: "/garten/maehroboter-rechner/",
    plannerLabel: "Hanglage einordnen",
    sections: [
      { title: "Prozent und Grad nicht verwechseln", paragraphs: ["Steigung in Prozent beschreibt das Verhältnis von Höhenunterschied zu waagerechter Strecke. Grad beschreibt einen Winkel. Beide Angaben sind nicht identisch und dürfen nicht direkt gleichgesetzt werden. Übernimm die Einheit, die der Hersteller für das konkrete Modell verwendet.", "Miss nicht nur den durchschnittlichen Hang. Kurze Rampen, Kuppen, Mulden und der Übergang von Ebene zu Steigung können die Traktion stärker fordern als eine gleichmäßige Fläche."] },
      { title: "Feuchter Boden verändert die Situation", paragraphs: ["Nasser Lehm, lockerer Boden, Moos und Laub reduzieren den Halt. Ein Modell, das eine trockene Teststeigung bewältigt, muss deshalb nicht an jeder feuchten Gartenstelle sicher arbeiten. Profil, Gewicht, Antrieb und Fahrstrategie wirken zusammen.", "Allrad kann Traktion verbessern, löst aber keine unsichere Absturzkante und verhindert nicht automatisch Schäden am weichen Boden. Prüfe außerdem, ob kräftige Wendemanöver die Grasnarbe aufreißen."] },
      { title: "Seitenhang und Kanten separat bewerten", paragraphs: ["Fährt der Roboter quer zum Hang, wirken andere Kräfte als bei gerader Bergfahrt. An einer Mauer, Stufe, Straße oder einem Teich kann ein seitliches Abrutschen besonders kritisch sein. Die vorgeschriebenen Sicherheitsabstände des Systems müssen eingehalten werden.", "Auch Ladestation und Passagen sollten nicht an ungeeigneten Übergängen liegen. Plane eine sichere, ausreichend ebene Anfahrt und beachte Wasserablauf sowie Bodenstabilität."] },
      { title: "Herstellerwert unter Bedingungen lesen", paragraphs: ["Prüfe, ob der Maximalwert für Flächenmitte, Rand, Kabelbereich oder eine bestimmte Fahrtrichtung gilt. Ein einzelner Spitzenwert ist kein Versprechen für das komplette Hanggrundstück. Dokumentierte Praxiserfahrung auf vergleichbarem Gelände und ein Vor-Ort-Test sind besonders wertvoll."] },
    ],
  },
  {
    slug: "wpc-vollprofil-oder-hohlkammer",
    title: "WPC Vollprofil oder Hohlkammer: Terrassendielen vergleichen",
    description: "WPC-Vollprofil und Hohlkammerdielen vergleichen: Gewicht, Wasser, Schnittkanten, Unterkonstruktion, Temperatur, Befestigung und Kosten prüfen.",
    heading: "WPC Vollprofil oder Hohlkammer: Das Profil beeinflusst den gesamten Aufbau",
    intro: "Hohlkammerdielen sparen Material und Gewicht, Vollprofile besitzen einen massiveren Querschnitt. Beide benötigen passende Unterkonstruktion, Befestigung und Wasserführung.",
    takeaway: "Vergleiche nicht nur den Dielenpreis. Prüfe freigegebene Spannweite, Schnittkanten, Wasserführung, Befestigung, Wärmeausdehnung, Gewicht und Einsatzgrenzen des kompletten Systems.",
    plannerHref: "/garten/terrassen-dielen-rechner/",
    plannerLabel: "Terrassenbedarf berechnen",
    sections: [
      { title: "Hohlkammerprofile reduzieren Material", paragraphs: ["Im Inneren verlaufen Hohlräume, die Gewicht und Materialeinsatz reduzieren. Dadurch können Transport und Verarbeitung leichter werden. Die Kammern benötigen jedoch passende Abschlussprofile und eine sichere Wasserführung nach Herstellerangabe.", "Offene oder falsch verschlossene Schnittkanten können Schmutz und Wasser aufnehmen. Das bedeutet nicht, dass jedes Hohlkammerprofil problematisch ist, sondern dass Zuschnitt und Randdetails Teil des freigegebenen Systems bleiben müssen."] },
      { title: "Vollprofile sind massiver, aber nicht grenzenlos", paragraphs: ["Ein Vollprofil besitzt Material über den gesamten Querschnitt und kann bei bestimmten Anwendungen oder Zuschnitten flexibler sein. Es ist schwerer und häufig teurer. Wärmeausdehnung, Auflagerabstand und Befestigung bleiben auch hier verbindliche Planungsdaten.", "Massiv bedeutet nicht automatisch tragfähig für beliebige Spannweiten. Terrassendielen sind kein Ersatz für eine passend dimensionierte Unterkonstruktion und dürfen nicht mit frei gewählten Abständen montiert werden."] },
      { title: "Unterkonstruktion und Temperatur", paragraphs: ["Dunkle WPC-Dielen können sich in direkter Sonne stark erwärmen. Temperatur verändert außerdem die Länge des Profils. Randabstände, Stoßausbildung und Clip-System müssen diese Bewegung zulassen.", "Die Unterkonstruktion sollte material- und systemspezifisch gewählt werden. Stöße, Treppen, Blenden und schwere Aufbauten wie Pflanzkübel benötigen eigene Details, die im einfachen Quadratmeterpreis fehlen."] },
      { title: "Kosten mit vollständigem System vergleichen", paragraphs: ["Addiere Dielen, Clips, Start- und Endteile, Abschlussprofile, Unterkonstruktion, Fundamente und Lieferung. Ein günstiges Hohlkammerprofil kann mit umfangreichen Randteilen anders abschneiden als der reine Dielenpreis vermuten lässt."] },
    ],
  },
  {
    slug: "terrassen-unterkonstruktion-holz-oder-aluminium",
    title: "Terrassen-Unterkonstruktion aus Holz oder Aluminium?",
    description: "Holz- und Aluminium-Unterkonstruktion für Terrassen vergleichen: Materialverträglichkeit, Aufbauhöhe, Feuchte, Spannweite, Befestigung und Kosten.",
    heading: "Holz oder Aluminium unter der Terrasse: Das Deckmaterial entscheidet mit",
    intro: "Die Unterkonstruktion trägt die Dielen und bestimmt Entwässerung, Aufbauhöhe und Befestigung. Ihr Material muss zu Deckbelag, Untergrund und Systemfreigabe passen.",
    takeaway: "Wähle die Unterkonstruktion nicht isoliert. Prüfe Kompatibilität mit der Diele, zulässige Auflagerabstände, Feuchteschutz, Aufbauhöhe, Stoßdetails und Befestiger als Gesamtsystem.",
    plannerHref: "/garten/terrassen-dielen-rechner/",
    plannerLabel: "Unterkonstruktion berechnen",
    sections: [
      { title: "Holz-Unterkonstruktion", paragraphs: ["Holz lässt sich gut bearbeiten und kann bei passender Dauerhaftigkeit und konstruktivem Schutz eine wirtschaftliche Lösung sein. Unterkonstruktion und Deckbelag sollten hinsichtlich Lebensdauer und Feuchteverhalten aufeinander abgestimmt werden.", "Direkter Kontakt zu dauerhaft nassem Untergrund, fehlende Hinterlüftung oder Wasserfallen verkürzen die Nutzungsdauer. Hirnholz, Anschlüsse und Bohrungen benötigen besondere Aufmerksamkeit."] },
      { title: "Aluminium-Unterkonstruktion", paragraphs: ["Aluminiumprofile sind formstabil und können bei niedriger Aufbauhöhe interessant sein. Profilhöhe, Wandstärke, Auflagerabstand und Verbindung folgen jedoch einem konkreten System. Ein beliebiges Profil ist keine automatisch geeignete Terrassen-Unterkonstruktion.", "Bei Befestigern und Kontakt zu anderen Metallen müssen Materialverträglichkeit und Korrosion berücksichtigt werden. Clips und Schrauben müssen zum Profil und zur Deckdiele passen."] },
      { title: "Stöße und Lasten planen", paragraphs: ["Dielenstöße benötigen häufig doppelte Auflager oder definierte Profilanordnungen. Schwere Pflanzkübel, Treppen, Geländer und punktuelle Lasten gehören nicht ungeprüft in ein Standardraster.", "Der Untergrund bestimmt, wo Auflager oder Fundamente möglich sind. Gefälle und Entwässerung müssen erhalten bleiben, ohne dass Ausgleichspads oder Träger Wasser einschließen."] },
      { title: "Kosten und Reparatur", paragraphs: ["Holz kann günstiger und einfacher anpassbar sein, Aluminium langlebig und maßhaltig. Vergleiche Material, Verbindung, Arbeitszeit, Aufbauhöhe, erwartete Nutzungsdauer und die Möglichkeit, einzelne Bereiche später zu öffnen oder zu reparieren."] },
    ],
  },
  {
    slug: "bewaesserung-fuer-rasen-und-beete",
    title: "Bewässerung für Rasen und Beete gemeinsam planen",
    description: "Rasen und Beete automatisch bewässern: Regner, Tropfrohr, Druck, Durchfluss, Zonen, Laufzeiten und Steuerung als Gesamtsystem planen.",
    heading: "Rasen und Beete bewässern: Gemeinsam versorgen, getrennt steuern",
    intro: "Rasen und Beete haben unterschiedliche Abgabesysteme und Laufzeiten. Eine gemeinsame Wasserquelle funktioniert am besten, wenn die Flächen in nachvollziehbare Zonen getrennt werden.",
    takeaway: "Miss Druck und Durchfluss, plane Rasenregner und Tropfbewässerung als getrennte Zonen und stimme Laufzeit, Filterung und Steuerung auf die jeweiligen Komponenten ab.",
    plannerHref: "/garten/bewaesserungs-planer/",
    plannerLabel: "Bewässerungszonen planen",
    sections: [
      { title: "Flächen zuerst getrennt erfassen", paragraphs: ["Zeichne Rasen, Beete, Hecken und Kübel als eigene Bereiche ein. Notiere Maße, Höhenunterschiede, Sonne, Boden und Anschlussweg. Pflanzen mit ähnlichem Wasserbedarf können später zu einer Zone zusammengefasst werden.", "Rasenregner benötigen eine geplante Überlappung, Tropfrohre arbeiten entlang von Reihen oder Flächen. Beide Komponenten aus einer Zone zu betreiben erschwert die Abstimmung, weil Durchfluss und erforderliche Laufzeit stark abweichen können."] },
      { title: "Anschlussleistung begrenzt die gleichzeitige Nutzung", paragraphs: ["Messe den Durchfluss am vorgesehenen Anschluss und ermittle den Fließdruck unter definierter Entnahme. Ein hoher statischer Druck ohne ausreichenden Durchfluss sagt nicht, wie viele Regner gleichzeitig funktionieren.", "Teile Komponenten so auf, dass jede Zone innerhalb der verfügbaren Leistung bleibt. Lange Leitungen, Höhenunterschiede, Filter, Ventile und Rohrdurchmesser verursachen zusätzliche Verluste, die eine reine Eimerrechnung nicht vollständig abbildet."] },
      { title: "Steuerung nach Bedarf statt gleicher Minuten", paragraphs: ["Rasen und Tropfbewässerung benötigen häufig unterschiedliche Laufzeiten und Intervalle. Wetter, Jahreszeit, Boden und Pflanzenentwicklung verändern den Bedarf. Eine Steuerung sollte einzelne Zonen separat schalten und eine einfache manuelle Pause ermöglichen.", "Bodenfeuchte oder Regensensoren können unterstützen, ersetzen aber keine Kontrolle auf verstopfte Tropfer, verschobene Regner oder undichte Verbindungen."] },
      { title: "Trinkwasserschutz und Wartung", paragraphs: ["Außeninstallationen müssen gegen Rückfließen und Verunreinigung fachgerecht abgesichert sein. Filter, Druckminderer, Entleerung und Frostschutz folgen dem konkreten System. Plane zugängliche Ventile und dokumentiere jede Zone für Wartung und Winterbetrieb."] },
    ],
  },
  {
    slug: "gewaechshaus-fuer-tomaten-groesse",
    title: "Gewächshaus für Tomaten: Welche Größe und Lüftung passt?",
    description: "Gewächshaus für Tomaten planen: Pflanzabstand, Beetbreite, Wege, Höhe, Tür, Dachlüftung, Bewässerung und Regenwasser sinnvoll bestimmen.",
    heading: "Tomaten im Gewächshaus: Von Pflanzenzahl und Arbeitsweg zur Größe",
    intro: "Die Außenfläche allein sagt wenig über die Nutzbarkeit. Tomaten brauchen erreichbare Beete, ausreichende Höhe, Luftaustausch und einen Weg, auf dem Pflege und Ernte möglich bleiben.",
    takeaway: "Lege Pflanzenzahl, Beetbreite, Weg und Arbeitshöhe zuerst fest. Ergänze Dach- und Türlüftung, Bewässerung und Zugang, bevor du ein Außenmaß auswählst.",
    plannerHref: "/garten/gewaechshaus-planer/",
    plannerLabel: "Tomaten-Gewächshaus planen",
    sections: [
      { title: "Pflanzenzahl wird zu Beetfläche", paragraphs: ["Lege fest, wie viele Tomatenpflanzen gleichzeitig wachsen sollen und welche Sorten vorgesehen sind. Pflanzabstände und Reihenführung hängen von Sorte, Erziehung und Kulturführung ab; allgemeine Werte dürfen die Angaben zu Saatgut oder Jungpflanze nicht ersetzen.", "Beete sollten vom Weg aus erreichbar sein, ohne den Wurzelraum zu betreten. Sehr tiefe Randbeete wirken flächeneffizient, sind aber bei Ausgeizen, Binden, Gießen und Ernte unpraktisch."] },
      { title: "Höhe und Rankhilfe", paragraphs: ["Stabtomaten benötigen Höhe für Wachstum und Rankhilfe. Entscheidend ist die nutzbare Innenhöhe an der tatsächlichen Pflanzposition, nicht nur die maximale Firsthöhe. Bei niedrigen Seitenwänden kann ein großer Teil des Hauses für hohe Pflanzen ungeeignet sein.", "Rankdrähte oder Schnüre erzeugen Lasten am Rahmen. Verwende nur vorgesehene Befestigungspunkte und berücksichtige, dass Pflanzen, Früchte und Bewässerung zusätzliche Kräfte einbringen."] },
      { title: "Lüftung begrenzt Hitze und Feuchte", paragraphs: ["Tomaten profitieren vom Regenschutz, benötigen aber Luftaustausch. Dachfenster lassen aufsteigende warme Luft entweichen, Tür- oder Seitenöffnungen unterstützen die Zufuhr. Öffnungsfläche, Automatik und Beschattung müssen zum konkreten Haus passen.", "Dauerhaft hohe Feuchte begünstigt Probleme. Gieße bodennah, halte Wege zugänglich und kontrolliere, ob Blätter Wände oder Dach dauerhaft berühren."] },
      { title: "Wasser und Alltag", paragraphs: ["Plane Anschluss, Tropfbewässerung oder Gießweg so, dass keine Schläuche den Zugang blockieren. Eine Regentonne kann Wasser sammeln, benötigt aber Überlauf und geeignete Dachmaterialien. Ablage, Werkzeug und Erntekisten beanspruchen ebenfalls Platz, der in einer reinen Beetflächenrechnung fehlt."] },
    ],
  },
  {
    slug: "luftentfeuchter-fuer-unbeheizten-keller",
    title: "Luftentfeuchter für unbeheizte Keller richtig auswählen",
    description: "Luftentfeuchter im unbeheizten Keller auswählen: Temperatur, Sommerkondensation, Kompressor oder Adsorption, Ablauf und Stromkosten prüfen.",
    heading: "Unbeheizter Keller: Temperatur entscheidet über Entfeuchtung und Lüften",
    intro: "Kalte Keller reagieren im Sommer anders als Wohnräume. Warme feuchte Außenluft kann an kalten Oberflächen zusätzliche Feuchte erzeugen, und Geräte leisten bei niedriger Temperatur unterschiedlich viel.",
    takeaway: "Messe Temperatur und Feuchteverlauf, kläre die Ursache und vergleiche Entfeuchterleistung bei der realen Kellertemperatur. Ein Dauerablauf und kontrollierte Luftführung sind oft wichtiger als der maximale Nennwert.",
    plannerHref: "/haus/raumklima/luftentfeuchter-rechner/",
    plannerLabel: "Kellerbedarf berechnen",
    sections: [
      { title: "Relative Feuchte allein erklärt nicht die Ursache", paragraphs: ["Relative Luftfeuchte hängt von der Temperatur ab. Kalte Kellerwände können Oberflächen erreichen, an denen feuchte Außenluft kondensiert. Deshalb kann langes Lüften an warmen schwülen Tagen die Situation verschlechtern.", "Messe Raumluft und möglichst kritische Oberflächen über mehrere Tage. Sichtbares Wasser, muffiger Geruch oder Schimmel erfordern zusätzlich eine fachliche Ursachenprüfung auf Leckage, aufsteigende Feuchte, Wärmebrücken oder andere Bauschäden."] },
      { title: "Gerätetechnik bei niedriger Temperatur", paragraphs: ["Kompressorgeräte werden häufig mit Nennleistungen unter warmen, feuchten Bedingungen beworben. In einem kalten Keller kann die reale Wasserentnahme deutlich geringer sein. Daten bei passender Temperatur und Abtauverhalten sind deshalb wichtig.", "Adsorptionsgeräte können bei niedrigeren Temperaturen besser arbeiten, nehmen aber je nach Modell mehr Strom auf und geben Wärme ab. Die Wahl entsteht aus Temperatur, Ziel, Laufzeit, Geräusch und Kosten, nicht nur aus Litern pro Tag."] },
      { title: "Aufstellung und Dauerablauf", paragraphs: ["Luft muss im Raum zirkulieren können. Ein Gerät zwischen vollen Regalen oder direkt an einer Wand kann die tatsächliche Wirkung begrenzen. Mehrere geschlossene Kellerräume benötigen offene Türen, Luftführung oder getrennte Betrachtung.", "Für längeren Betrieb ist ein sicherer Ablauf praktisch. Schlauchgefälle, Rückstau, Frost, Bodenablauf und Wiederanlauf nach Stromunterbrechung müssen geprüft werden. Ein voller Tank beendet sonst die Entfeuchtung unbemerkt."] },
      { title: "Zielwert und Betrieb kontrollieren", paragraphs: ["Ein Hygrostat sollte die Laufzeit begrenzen, sobald der gewählte Bereich erreicht ist. Zu trockenes Dauerentfeuchten erhöht Kosten und kann Materialien beeinflussen. Dokumentiere Verbrauch, Laufzeit und Feuchteverlauf, damit die Einstellung auf Wirkung statt Gefühl basiert."] },
    ],
  },
  {
    slug: "laminat-auf-fussbodenheizung",
    title: "Laminat auf Fußbodenheizung: Aufbau und Materialbedarf planen",
    description: "Laminat auf Fußbodenheizung verlegen: Herstellerfreigabe, Wärmewiderstand, Unterlage, Restfeuchte, Aufheizprotokoll und Materialmenge prüfen.",
    heading: "Laminat und Fußbodenheizung: Der gesamte Aufbau muss Wärme übertragen",
    intro: "Nicht nur das Laminat, sondern auch Unterlage, Dampfbremse, Untergrund und Verlegeart bestimmen, ob ein System für die Fußbodenheizung geeignet ist.",
    takeaway: "Verwende nur freigegebene Kombinationen und prüfe den Wärmedurchlasswiderstand des gesamten Aufbaus. Restfeuchte und Aufheizprotokoll müssen vor der Verlegung geklärt sein.",
    plannerHref: "/haus/boden/bodenbelag-rechner/",
    plannerLabel: "Laminatbedarf berechnen",
    sections: [
      { title: "Freigabe gilt für das konkrete Produkt", paragraphs: ["Die allgemeine Aussage Laminat ist für Fußbodenheizung geeignet reicht nicht. Produkt, Unterlage, Heizsystem und zulässige Oberflächentemperatur müssen zusammenpassen. Datenblatt und Verlegeanleitung sind verbindliche Ausgangspunkte.", "Eine ungeeignete oder doppelte Trittschallunterlage kann den Wärmewiderstand erhöhen. Bei Produkten mit integrierter Unterlage darf nicht automatisch eine weitere Schicht ergänzt werden."] },
      { title: "Untergrund und Restfeuchte", paragraphs: ["Der Estrich muss eben, fest, sauber und ausreichend trocken sein. Zulässige Restfeuchte und Messmethode hängen von Estrich und System ab. Eine oberflächliche Trockenheit bestätigt nicht die Belegreife.", "Bei neuen Heizestrichen gehört ein dokumentiertes Auf- und Abheizen zum Bauablauf. Zuständige Fachleute müssen bestätigen, welche Prüfungen und Protokolle für den konkreten Aufbau erforderlich sind."] },
      { title: "Fugen und Temperaturänderung", paragraphs: ["Laminat reagiert auf Raumklima. Randfugen, Übergänge und maximale zusammenhängende Flächen folgen der Verlegeanleitung. Schwere Einbauten oder Küchenzeilen dürfen einen schwimmenden Boden nicht ungeprüft fixieren.", "Die Heizung sollte innerhalb der zulässigen Vorlauf- und Oberflächentemperaturen betrieben und nicht abrupt verändert werden. Teppiche oder dichte Auflagen können lokal Wärme stauen."] },
      { title: "Materialmenge vollständig berechnen", paragraphs: ["Addiere Teilflächen, ziehe feste Aussparungen mit Bedacht ab und ergänze Verschnitt nach Raumform und Verlegerichtung. Pakete werden aufgerundet. Unterlage, Dampfbremse, Sockelleisten und Übergangsprofile benötigen eigene Mengen und müssen technisch zum Heizaufbau passen."] },
    ],
  },
] satisfies readonly SeoGuide[];
