import { createPageMetadata } from "@/lib/metadata";
import { GuidePage } from "@/components/seo/GuidePage";
export const metadata = createPageMetadata({
  title: "Gartenhaus mit oder ohne Boden",
  description: "Gartenhaus-Boden verstehen: Lieferumfang, Bodenset, Fundament und Nutzungsanforderungen klar unterscheiden.",
  path: "/garten/gartenhaus-boden/",
  kind: "article",
});
export default function Page() { return <GuidePage path="/garten/gartenhaus-boden/" title="Gartenhaus-Boden: enthalten, als Set oder selbst geplant?" intro="Ein Produktbild zeigt nicht zuverlässig, ob ein begehbarer Boden enthalten ist. Für Preis und Aufbau musst du Lieferumfang und Fundament getrennt betrachten." updated="August 2026" takeaway="Prüfe in der Stückliste, ob Bodenbalken und Dielen enthalten sind. Ein Bodenset ersetzt in der Regel kein tragfähiges Fundament." sections={[{ title: "Drei klare Zustände", paragraphs: ["MachPlan behandelt Bodeninformationen nicht als einfaches Ja oder Nein. Ein Boden kann enthalten, als kompatibles Set erhältlich oder unbekannt sein. Fehlt die Information, wird sie nicht als ‚ohne Boden‘ ausgegeben.", "Bei der Auswahl ‚Boden erforderlich‘ kommen nur Produkte infrage, für die ein enthaltener Boden oder ein passendes Set bestätigt ist." ] }, { title: "Nutzung bestimmt den Aufbau", paragraphs: ["Für Gartengeräte, Fahrräder und Werkbank zählen Belastbarkeit, Ebenheit und Feuchteschutz. Punktlasten durch Regale oder schwere Geräte sollten mit den freigegebenen Lasten des Bodens abgeglichen werden.", "Auch Schwellenhöhe und Türanschluss beeinflussen die Nutzbarkeit, besonders bei schweren Geräten, Rollern oder eingeschränkter Mobilität." ] }, { title: "Unter dem Boden", paragraphs: ["Zwischen Erdreich, Fundament, Unterkonstruktion und Bodenaufbau muss Feuchtigkeit kontrolliert abgeführt werden. Direkter Erdkontakt oder eingeschlossene Nässe verkürzen die Lebensdauer.", "Die konkrete Schichtenfolge gehört zur Standort- und Herstellerplanung und wird vom Produktfinder bewusst nicht berechnet." ] }]} />; }
