import { createPageMetadata } from "@/lib/metadata";
import { GuidePage } from "@/components/seo/GuidePage";
export const metadata = createPageMetadata({
  title: "Gartenhaus-Kosten realistisch kalkulieren",
  description: "Gesamtkosten eines Gartenhauses planen: Produkt, Versand, Fundament, Boden, Aufbau, Schutz und Zubehör.",
  path: "/garten/gartenhaus-kosten/",
  kind: "article",
});
export default function Page() { return <GuidePage path="/garten/gartenhaus-kosten/" title="Was kostet ein Gartenhaus insgesamt?" intro="Der sichtbare Produktpreis ist nur ein Teil des Projekts. Lieferung, Fundament, Boden, Aufbau und Pflege können die Gesamtkosten deutlich verändern." updated="August 2026" takeaway="Lege ein Gesamtbudget fest und reserviere darin eigene Töpfe für Lieferung, Fundament, Aufbau und notwendiges Zubehör." sections={[{ title: "Die fünf Kostenblöcke", paragraphs: ["Ein belastbares Budget trennt Kaufpreis, Versand, Fundament, Montage und Ausstattung. So vergleichst du Modelle nicht auf Basis eines günstigen Grundpreises, während wesentliche Projektkosten fehlen."], bullets: ["Haus und gegebenenfalls Bodenset", "Lieferung, Zufahrt und Abladen", "Erdarbeiten und Fundamentmaterial", "Aufbau oder Montageleistung", "Holzschutz, Dachentwässerung, Elektrik und Sicherung"] }, { title: "Versandkosten nie als null annehmen", paragraphs: ["Gerade große Gartenhäuser können hohe oder regionsabhängige Lieferkosten haben. Fehlt der Versandpreis im Händlerfeed, zeigt MachPlan den Budgetstatus deshalb als unbekannt.", "Sind Versandkosten bekannt, vergleicht der Planer den Gesamtpreis. Sind sie bei allen Angeboten unbekannt, kann nur ein Ab-Preis mit klarer Warnung gezeigt werden." ] }, { title: "Folgekosten passend zum Material", paragraphs: ["Holzhäuser können regelmäßigen Oberflächenschutz benötigen. Bei Metall und Kunststoff stehen andere Themen wie Kondensat, Verankerung und Reparierbarkeit im Vordergrund.", "Der günstigste Kaufpreis ist daher nicht automatisch die wirtschaftlichste Projektlösung. Prüfe die Herstellerhinweise und plane Pflege über mehrere Jahre mit ein." ] }]} />; }
