"use client";
import { useEffect, useState } from "react";
import { CalculatorShell } from "@/components/calculator/CalculatorShell";
import { buildIrrigationPlan } from "@/lib/irrigation/rules";
import { IrrigationInputSchema, type IrrigationInput } from "@/lib/irrigation/types";

const INITIAL:IrrigationInput={lawnAreaM2:100,bedAreaM2:20,hedgeLengthM:15,automaticControl:true,smartControl:false,rainSensorWanted:true,budgetMaxEur:600};

export function IrrigationPlanner(){
  const[step,setStep]=useState(1);const[input,setInput]=useState<IrrigationInput>(INITIAL);const[error,setError]=useState("");const plan=buildIrrigationPlan(input);
  useEffect(()=>{if(step>1)document.getElementById("calculator-heading")?.focus()},[step]);
  const update=<K extends keyof IrrigationInput,>(key:K,value:IrrigationInput[K])=>setInput((current)=>({...current,[key]:value}));
  const next=()=>{if(step===1&&input.lawnAreaM2+input.bedAreaM2+input.hedgeLengthM<=0){setError("Bitte mindestens eine Rasen-, Beet- oder Heckenfläche angeben.");return}setError("");setStep((s)=>Math.min(4,s+1))};
  const titles=["Welche Flächen sollen bewässert werden?","Was liefert dein Wasseranschluss?","Wie soll das System gesteuert werden?","Dein erster Komponentenplan"];
  return <CalculatorShell step={step} totalSteps={4} title={titles[step-1]} label="Bewässerungsplaner">
    {step===1&&<div className="form-step"><div className="field-grid field-grid--two"><NumberField id="lawn" label="Rasenfläche" value={input.lawnAreaM2} unit="m²" onChange={(v)=>update("lawnAreaM2",v)}/><NumberField id="beds" label="Beetfläche" value={input.bedAreaM2} unit="m²" onChange={(v)=>update("bedAreaM2",v)}/><NumberField id="hedge" label="Heckenlänge" value={input.hedgeLengthM} unit="m" onChange={(v)=>update("hedgeLengthM",v)}/></div>{error&&<p className="field-error" role="alert">{error}</p>}<div className="info-box"><span>i</span><p>Flächen dürfen grob geschätzt sein. Für Rasenregner brauchen wir später zusätzlich Form, Hindernisse und gewünschte Zonen.</p></div></div>}
    {step===2&&<div className="form-step"><div className="field-grid field-grid--two"><OptionalField id="flow" label="Gemessener Durchfluss" value={input.waterFlowLMin} unit="l/min" onChange={(v)=>update("waterFlowLMin",v)}/><OptionalField id="pressure" label="Fließdruck" value={input.waterPressureBar} unit="bar" onChange={(v)=>update("waterPressureBar",v)}/></div><div className="measurement-card"><h3>Eimertest für den Durchfluss</h3><p>Miss, wie viele Sekunden dein Anschluss zum Füllen eines bekannten Volumens benötigt. Durchfluss in l/min = Liter × 60 ÷ Sekunden.</p><p><strong>Den Fließdruck misst du während Wasser entnommen wird</strong> – statischer Ruhedruck ist kein Ersatz.</p></div><div className="info-box"><span>!</span><p>Ohne belastbare Messwerte erstellen wir nur die Materialstruktur. Rohrdimensionen und Rasen-Zonen bleiben ausdrücklich offen.</p></div></div>}
    {step===3&&<div className="form-step"><div className="check-card-grid check-card-grid--two"><Check label="Automatische Steuerung" detail="Ventile und Controller einplanen" checked={input.automaticControl} onChange={(value)=>{update("automaticControl",value);if(!value){update("smartControl",false);update("rainSensorWanted",false)}}}/><Check label="Smarte Steuerung" detail="App-/Netzwerkfunktion gewünscht" checked={input.smartControl} disabled={!input.automaticControl} onChange={(value)=>update("smartControl",value)}/><Check label="Regen- oder Feuchtesensor" detail="Nur systemkompatible Sensoren" checked={input.rainSensorWanted} disabled={!input.automaticControl} onChange={(value)=>update("rainSensorWanted",value)}/></div><NumberField id="irrigation-budget" label="Maximales Systembudget" value={input.budgetMaxEur} unit="€" min={50} onChange={(v)=>update("budgetMaxEur",v)}/><div className="live-estimate"><span>Voraussichtlicher Systemstil</span><strong>{plan.style==="combined"?"Kombiniertes System":plan.style==="sprinkler"?"Rasensprenger-System":"Tropfbewässerung"}</strong><small>{input.automaticControl?`Steuerung mit mindestens ${plan.controllerZones} Zonen vorgesehen`:"Manuelle Steuerung gewählt"}</small></div></div>}
    {step===4&&<div className="results"><div className="requirement-summary"><div><span>System</span><strong>{plan.style==="combined"?"Kombiniert":plan.style==="sprinkler"?"Rasen":"Tropf"}</strong></div><div><span>Nutzungsbereiche</span><strong>{plan.activeCategories}</strong></div><div><span>Steuerungszonen</span><strong>{plan.controllerZones||"manuell"}</strong></div><div><span>Budgetrahmen</span><strong>{input.budgetMaxEur.toLocaleString("de-DE")} €</strong></div></div><div className="component-plan"><div className="result-heading"><div><p className="eyebrow">Erste Materialstruktur</p><h3>Diese Kategorien solltest du einplanen.</h3></div></div>{plan.components.map((component)=><article key={`${component.kind}-${component.label}`}><span className="component-icon" aria-hidden="true">{component.kind==="dripline"?"≈":component.kind==="controller"?"⌁":"○"}</span><div><h4>{component.label}</h4><strong>{component.quantity}</strong><p>{component.note}</p></div></article>)}</div><div className="warning-panel"><h3>Vor der Produktauswahl prüfen</h3><ul>{plan.warnings.map((warning)=><li key={warning}>{warning}</li>)}</ul></div><div className="result-state result-state--compact"><h3>Produktsets folgen nach Systemprüfung.</h3><p>Wir kombinieren später nur Komponenten mit bestätigter System-ID. Bis dahin zeigt der Planer bewusst keine zufällige Einkaufsliste.</p></div></div>}
    <div className="calculator-actions">{step>1&&<button className="button button--back" onClick={()=>setStep((s)=>Math.max(1,s-1))}>← Zurück</button>}{step<4&&<button className="button button--primary" onClick={next}>{step===3?"Komponentenplan erstellen":"Weiter"} →</button>}{step===4&&<button className="button button--back" onClick={()=>setStep(1)}>Eingaben ändern</button>}</div>
  </CalculatorShell>
}

function NumberField({id,label,value,unit,min=0,onChange}:{id:string;label:string;value:number;unit:string;min?:number;onChange:(value:number)=>void}){return <div className="field"><label htmlFor={id}>{label}</label><div className="input-with-unit"><input id={id} type="number" min={min} max="10000" value={value} onChange={(e)=>onChange(e.target.valueAsNumber)}/><span>{unit}</span></div></div>}
function OptionalField({id,label,value,unit,onChange}:{id:string;label:string;value?:number;unit:string;onChange:(value:number|undefined)=>void}){return <div className="field"><label htmlFor={id}>{label} <span className="optional">optional</span></label><div className="input-with-unit"><input id={id} type="number" min="0.1" step="0.1" value={value??""} onChange={(e)=>onChange(e.target.value===""?undefined:e.target.valueAsNumber)}/><span>{unit}</span></div></div>}
function Check({label,detail,checked,disabled=false,onChange}:{label:string;detail:string;checked:boolean;disabled?:boolean;onChange:(value:boolean)=>void}){return <label className={`check-card ${checked?"check-card--selected":""} ${disabled?"check-card--disabled":""}`}><input type="checkbox" checked={checked} disabled={disabled} onChange={(e)=>onChange(e.target.checked)}/><span className="check-box">{checked?"✓":""}</span><span><strong>{label}</strong><small>{detail}</small></span></label>}
