import { createPageMetadata } from "@/lib/metadata";
import { GuidePage } from "@/components/seo/GuidePage";
export const metadata = createPageMetadata({
  title: "Gartenhaus-Fundament planen",
  description: "Fundamentarten für Gartenhäuser einordnen: Untergrund, Last, Entwässerung und Herstelleranforderungen prüfen.",
  path: "/garten/gartenhaus-fundament/",
  kind: "article",
});
export default function Page() { return <GuidePage path="/garten/gartenhaus-fundament/" title="Gartenhaus-Fundament: stabil beginnt vor dem Aufbau" intro="Das Fundament hält das Haus eben, trocken und dauerhaft tragfähig. Welche Lösung passt, hängt von Untergrund, Haus, Last und Herstellervorgaben ab." updated="August 2026" takeaway="Prüfe zuerst Untergrund und Herstelleranforderung. Entscheide erst danach zwischen Platten-, Streifen-, Punkt- oder Schraubfundament." sections={[{ title: "Was ein Fundament leisten muss", paragraphs: ["Ein Gartenhaus braucht eine ebene, tragfähige und entwässerte Grundlage. Setzungen oder Staunässe können Türen verziehen, Holzteile dauerhaft befeuchten und die Konstruktion belasten.", "Die erforderliche Ausführung hängt nicht nur vom Gewicht ab. Bodenart, Frost, Hanglage, lokale Niederschläge und Verankerung spielen ebenfalls eine Rolle."], bullets: ["Last gleichmäßig in den Boden ableiten", "Spritz- und Stauwasser vom Haus fernhalten", "Vorgegebene Verankerung sicher ermöglichen"] }, { title: "Fundamentarten grob eingeordnet", paragraphs: ["Plattenfundamente schaffen eine durchgehende Fläche, benötigen aber sorgfältigen Aufbau und Entwässerung. Streifen- und Punktfundamente konzentrieren die Last an definierten Stellen. Schraubfundamente können Erdarbeiten reduzieren, sind aber vom Boden und vom freigegebenen System abhängig.", "Eine Terrassenfläche oder lose Platten sind nicht automatisch ein geeignetes Gartenhausfundament. Maßgeblich sind Aufbau, Ebenheit, Tragfähigkeit und die Vorgaben des konkreten Hauses." ] }, { title: "Boden im Lieferumfang ist nicht das Fundament", paragraphs: ["Ein mitgelieferter Fußboden oder ein separat erhältliches Bodenset bildet die nutzbare Innenfläche. Darunter bleibt eine geeignete Gründung erforderlich.", "MachPlan unterscheidet deshalb zwischen enthaltenem Boden, verfügbarem Bodenset und unbekannter Bodenoption – trifft aber keine Fundamententscheidung." ] }]} />; }
