export const DATA_REPORTS = [
  {
    slug: "gartenhaus-preise-groessen",
    topic: "gartenhaus",
    eyebrow: "Gartenhäuser im Datencheck",
    title: "Was Größe, Material und Preis im aktuellen Gartenhauskatalog zeigen",
    description: "Eine datenbasierte Einordnung von Grundflächen, Materialien, Dachformen und Angebotspreisen mit offen ausgewiesenen Datenlücken.",
    path: "/ratgeber/daten/gartenhaus-preise-groessen/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "gartenhaus-aussenmasse-grundstuecksbreite",
    topic: "gartenhaus",
    eyebrow: "Gartenhaus Außenmaße im Datencheck",
    title: "Welche Grundstücksbreite Gartenhäuser wirklich beanspruchen",
    description: "Kurze und lange Außenseite, Baukörperform und Grundfläche gemeinsam auswerten, damit die Vorauswahl nicht an einem unpassenden Außenmaß scheitert.",
    path: "/ratgeber/daten/gartenhaus-aussenmasse-grundstuecksbreite/",
    updatedAt: "2026-09-21",
  },
  {
    slug: "bodenbelaege-fussbodenheizung-feuchtraum",
    topic: "bodenbelag",
    eyebrow: "Bodenbeläge im Datencheck",
    title: "Fußbodenheizung, Feuchtraum und Paketmengen im Datenvergleich",
    description: "Laminat, Klickvinyl und Fertigparkett nach dokumentierten Freigaben, Paketgrößen und einer konkreten Materialrechnung vergleichen.",
    path: "/ratgeber/daten/bodenbelaege-fussbodenheizung-feuchtraum/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "bodenbelag-formate-paketrundung",
    topic: "bodenbelag",
    eyebrow: "Bodenformate im Datencheck",
    title: "Wie Dielenformat und volle Pakete die Bestellmenge verändern",
    description: "Dielenlänge, Breite und Paketinhalt gemeinsam auswerten und die zusätzliche Rundung bei drei Flächengrößen sichtbar machen.",
    path: "/ratgeber/daten/bodenbelag-formate-paketrundung/",
    updatedAt: "2026-09-21",
  },
  {
    slug: "luftentfeuchter-leistung-lautstaerke",
    topic: "luftentfeuchter",
    eyebrow: "Luftentfeuchter im Datencheck",
    title: "Welche Leistungsdaten bei Luftentfeuchtern wirklich vergleichbar sind",
    description: "Entfeuchtungsleistung, Geräusch, Stromaufnahme und Betriebstemperatur anhand der tatsächlich dokumentierten Produktdaten einordnen.",
    path: "/ratgeber/daten/luftentfeuchter-leistung-lautstaerke/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "maehroboter-navigation-flaechenleistung",
    topic: "maehroboter",
    eyebrow: "Mähroboter im Datencheck",
    title: "Navigation, Flächenleistung und Engstellen bei 15 Mährobotern",
    description: "Kabel, Kamera, LiDAR, RTK und hybride Navigation anhand der dokumentierten Flächenleistung, Steigung, Engstellen und Angebotspreise einordnen.",
    path: "/ratgeber/daten/maehroboter-navigation-flaechenleistung/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "sicherheitskameras-verbindung-strom-setgroesse",
    topic: "sicherheitskameras",
    eyebrow: "Sicherheitskameras im Datencheck",
    title: "Verbindung, Stromversorgung und Setgröße bei 20 Kameras",
    description: "WLAN, PoE und Mobilfunk gemeinsam mit der Stromversorgung betrachten und die Produktkosten für vier Überwachungszonen nachvollziehen.",
    path: "/ratgeber/daten/sicherheitskameras-verbindung-strom-setgroesse/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "sicherheitskameras-schwenken-licht-aufloesung",
    topic: "sicherheitskameras",
    eyebrow: "Kamerafunktionen im Datencheck",
    title: "Wie Schwenken, Licht und Auflösung die Kameraauswahl verkleinern",
    description: "Kameraprodukte nach Einsatzort, Schwenkfunktion, Licht und Auflösung auswerten und kombinierte Anforderungen sichtbar machen.",
    path: "/ratgeber/daten/sicherheitskameras-schwenken-licht-aufloesung/",
    updatedAt: "2026-09-21",
  },
  {
    slug: "bewaesserung-komponenten-systeme",
    topic: "bewaesserung",
    eyebrow: "Bewässerung im Datencheck",
    title: "84 Bewässerungsprodukte zeigen, warum Einzelteile noch kein System ergeben",
    description: "Rohre, Verbinder, Regner, Tropfleitungen und Steuerungen nach Sortimentsschwerpunkt und dokumentierter Planungstiefe untersuchen.",
    path: "/ratgeber/daten/bewaesserung-komponenten-systeme/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "carport-groessen-stellplaetze",
    topic: "carport",
    eyebrow: "Carportgrößen im Datencheck",
    title: "Einzelcarport und Doppelcarport anhand von 69 Bausätzen vergleichen",
    description: "Außenmaße, Grundfläche, Stellplatzzahl und Angebotspreise der dokumentierten Carport Bausätze datenbasiert einordnen.",
    path: "/ratgeber/daten/carport-groessen-stellplaetze/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "carport-bausatz-zubehoer-preise",
    topic: "carport",
    eyebrow: "Carportsortiment im Datencheck",
    title: "Warum günstige Carport Treffer häufig Zubehör und keine Bausätze sind",
    description: "Bausätze, Seitenwände, Fundamente, Entwässerung und Elektrik im aktuellen Katalog getrennt betrachten.",
    path: "/ratgeber/daten/carport-bausatz-zubehoer-preise/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "carport-datenluecken-lichte-masse-dach",
    topic: "carport",
    eyebrow: "Carportdaten auf dem Prüfstand",
    title: "Außenmaße sind häufig vorhanden, lichte Maße und Dachangaben kaum",
    description: "Welche Carportdaten für eine belastbare Fahrzeug und Standortprüfung fehlen und warum Außenmaße allein nicht reichen.",
    path: "/ratgeber/daten/carport-datenluecken-lichte-masse-dach/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "gewaechshaus-flaeche-preise",
    topic: "gewaechshaus",
    eyebrow: "Gewächshausgrößen im Datencheck",
    title: "114 Gewächshäuser nach Grundfläche und Angebotspreis ausgewertet",
    description: "Kleine, mittlere und große Gewächshäuser anhand dokumentierter Außenmaße und verfügbarer Preise vergleichen.",
    path: "/ratgeber/daten/gewaechshaus-flaeche-preise/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "gewaechshaus-glas-hohlkammerplatten",
    topic: "gewaechshaus",
    eyebrow: "Gewächshausverglasung im Datencheck",
    title: "Glas und Hohlkammerplatten in der aktuellen Gewächshausstichprobe",
    description: "Verglasungsarten nach Häufigkeit, mittlerer Grundfläche und Preis einordnen, ohne daraus einen pauschalen Materialsieger abzuleiten.",
    path: "/ratgeber/daten/gewaechshaus-glas-hohlkammerplatten/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "gewaechshaus-hoehe-lueftung-zubehoer",
    topic: "gewaechshaus",
    eyebrow: "Gewächshausplanung im Datencheck",
    title: "Höhe, Lüftung und Zubehör bleiben in Produktfeeds oft unvollständig",
    description: "Dokumentierte Höhen, Lüftungsangaben und Zubehöranteile prüfen und ihre Bedeutung für Kulturplan und Klima erklären.",
    path: "/ratgeber/daten/gewaechshaus-hoehe-lueftung-zubehoer/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "sichtschutz-elementbreiten-hoehen",
    topic: "sichtschutz",
    eyebrow: "Sichtschutzmaße im Datencheck",
    title: "80 Sichtschutzelemente und Matten nach Breite und Höhe ausgewertet",
    description: "Elementmaße in sinnvolle Breiten und Höhenklassen einordnen und ihre Wirkung auf Raster und Restfelder zeigen.",
    path: "/ratgeber/daten/sichtschutz-elementbreiten-hoehen/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "sichtschutz-kosten-zehn-meter",
    topic: "sichtschutz",
    eyebrow: "Sichtschutzkosten im Datencheck",
    title: "Was zehn Meter Sichtschutz mit unterschiedlichen Elementbreiten rechnerisch kosten",
    description: "Vollständige Elemente auf zehn Meter aufrunden und zeigen, warum Höhe, Restfeld und Systemteile den reinen Elementpreis verändern.",
    path: "/ratgeber/daten/sichtschutz-kosten-zehn-meter/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "sichtschutz-systemteile-datenluecken",
    topic: "sichtschutz",
    eyebrow: "Sichtschutzsysteme im Datencheck",
    title: "Elemente, Pfosten, Tore und Halterungen bilden noch kein freigegebenes System",
    description: "Das Sortiment nach Produktarten und dokumentierter Kompatibilität untersuchen und offene Planungsfragen sichtbar machen.",
    path: "/ratgeber/daten/sichtschutz-systemteile-datenluecken/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "terrassendielen-holz-wpc-abmessungen",
    topic: "terrasse",
    eyebrow: "Terrassendielen im Datencheck",
    title: "Holz und WPC Dielen nach Länge, Breite und Stärke verglichen",
    description: "80 dokumentierte Terrassendielen nach Material und Abmessungen auswerten und die Folgen für Reihen und Zuschnitt einordnen.",
    path: "/ratgeber/daten/terrassendielen-holz-wpc-abmessungen/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "terrassendielen-laengen-verschnitt",
    topic: "terrasse",
    eyebrow: "Dielenlängen im Datencheck",
    title: "Welche Lieferlängen im Terrassenkatalog häufig sind und was das für Verschnitt bedeutet",
    description: "Dielen in drei Längenklassen untersuchen und zeigen, weshalb Verlegerichtung und Terrassenmaß gemeinsam gerechnet werden müssen.",
    path: "/ratgeber/daten/terrassendielen-laengen-verschnitt/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "terrasse-systemteile-preisvergleich",
    topic: "terrasse",
    eyebrow: "Terrassensysteme im Datencheck",
    title: "Dielen, Unterkonstruktion und Befestigung dürfen preislich nicht vermischt werden",
    description: "Produktarten und Datenabdeckung des Terrassenkatalogs prüfen und erklären, warum ein belastbarer Quadratmeterpreis noch nicht möglich ist.",
    path: "/ratgeber/daten/terrasse-systemteile-preisvergleich/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "trockenbauplatten-typen-dicken",
    topic: "trockenbau",
    eyebrow: "Trockenbauplatten im Datencheck",
    title: "Standard, Feuchtraum, Brand und Gipsfaserplatten im Vergleich",
    description: "28 geprüfte Platten nach dokumentiertem Typ, Material, Dicke und Angebotspreis auswerten.",
    path: "/ratgeber/daten/trockenbauplatten-typen-dicken/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "trockenbauprofile-breiten-laengen",
    topic: "trockenbau",
    eyebrow: "Trockenbauprofile im Datencheck",
    title: "Profilbreiten, Lieferlängen und Packungsgrößen richtig lesen",
    description: "48 Profile nach Breite, Länge, Typ und Packungsumfang untersuchen und die Grenzen eines reinen Preisvergleichs zeigen.",
    path: "/ratgeber/daten/trockenbauprofile-breiten-laengen/",
    updatedAt: "2026-09-16",
  },
  {
    slug: "trockenbau-feuchtraum-brandschutz-datenluecken",
    topic: "trockenbau",
    eyebrow: "Trockenbaudaten auf dem Prüfstand",
    title: "Feuchtraum und Brandschutz lassen sich nicht aus unvollständigen Produktfeeds freigeben",
    description: "Datenabdeckung für Maße, Feuchtraumfreigabe und Brandklasse offenlegen und die notwendige Systemprüfung erklären.",
    path: "/ratgeber/daten/trockenbau-feuchtraum-brandschutz-datenluecken/",
    updatedAt: "2026-09-16",
  },
] as const;

export function getDataReportsForTopic(topic: string) {
  return DATA_REPORTS.filter((report) => report.topic === topic);
}
